### PR TITLE
Add support for LaTeX Expl3 and DocTeX

### PR DESCRIPTION
**Pull request by Stone-Zeng**
**Changes proposed:**

- [x] Add
- [ ] Delete
- [ ] Fix
- [ ] Prepare

Recently, [LaTeX-Workshop](https://github.com/James-Yu/LaTeX-Workshop) has added support for DocTeX and LaTeX Expl3. So it's time to add the icon support too.

I use the same icon for them. Maybe we need something else, e.g. the hummingbird in <https://www.latex-project.org/latex3> for LaTeX Expl3? (personally, I think the original tex icon is enough).

By the way, #1271 requires support for LaTeX Beamer, LaTeX Log, LaTeX Memoir. It seems that LaTeX Log has been removed, but should I support Beamer and Memoir too? I think there are not so many people use them.

### CODE REVIEW

**Comment by Stone-Zeng** [comment]
So how to add icon for the expl3 files? At present they are labelled with the default icon.

**Comment by JimiC** [comment]
No file extension, no icon, no support, simple.

**Comment by JimiC** [comment]
@Stone-Zeng Can you please follow up with the requested changes?

**Comment by Stone-Zeng** [comment]
By the way, I'm still confusing about the relation of languages, extensions and icons. For example, language `json` and `jsonc` share the same extension `.json`. For latex and latex-expl3, the situation is the similar. Could you give some explanations in detail? Thanks very much.

**Comment by JimiC** [comment]
@Stone-Zeng The `defaultExtension` attribute in https://github.com/vscode-icons/vscode-icons/blob/master/src/icon-manifest/languages.ts#L88 does not correctly reflect the file extension(s) of the `language id` used. That attribute is just a helper for our `exampleGenerator` tool.

The correct file extensions and filenames are those declared here: 
https://github.com/Microsoft/vscode/blob/master/extensions/json/package.json#L43

P.S.: While mentioning it, the `defaultExtension` for `jsonc` should have been `.jsonc` but it slipt me by when reviewing @robertohuertasm  PR at that time.

**Comment by Stone-Zeng** [comment]
Can this PR be merged?

**Comment by jens1o** [comment]
cc @robertohuertasm

**Pull request merged**
