### PR TITLE
feat(icon): add SST icon

### PR DESCRIPTION
**Pull request by teriu**
This adds the SST logo (a serverless IaC language: https://sst.dev/).

**Changes proposed:**

- [x] Add
- [ ] Delete
- [ ] Fix
- [ ] Prepare

### CODE REVIEW

**Review by mackdelany — APPROVED** [review]

**Comment by robertohuertasm** [comment]
@JimiC did you close this intentionally?

**Comment by JimiC** [comment]
@robertohuertasm Yes. It was faulty anyways.

**Comment by robertohuertasm** [comment]
But they can fix it, right?

**Comment by JimiC** [comment]
OP needs to create a new branch on his repo other than `master` and request a pull. Safest way is to recreate the PR.

**Comment by robertohuertasm** [comment]
The way I see it, although not committing from master is a good practice, it's more for the one doing the PR that for the ones receiving it, to the point that GitHub allows this kind of practice and we will be able to merge the PR. What I mean is that it's ultimately a decision of the contributor, and shouldn't affect the viability of us merging the PR. Using master can complicate contributor's life if he wants to bring changes from the source, but this is their problem, not ours.

**Comment by JimiC** [comment]
PR from another branch other than `master` is a good practice that all devs should learn, imo.

**Comment by robertohuertasm** [comment]
I agree but imo it shouldn’t be the cause of closing an issue given the before mentioned arguments.

**Comment by JimiC** [comment]
I closed it mainly for case #1

**Comment by robertohuertasm** [comment]
I see, but that could be fixed, right? It doesn’t require the user to go through the hassle of recreate the PR, but maybe I’m missing something.

**Comment by JimiC** [comment]
I'm not sure the PR can be changed if the branch changes.

**Comment by robertohuertasm** [comment]
But again, the branch being changed is a nice to have. It’s not really a requirement on our side.

**Comment by robertohuertasm** [comment]
Agree on that, too.

**Comment by robertohuertasm** [comment]
It’s more about deciding where we draw the line to make the decision on when to close a PR.

**Comment by robertohuertasm** [comment]
Final comment :) I’m not going to unilaterally reopen this PR. I just wanted to make my point about that decision clear. If it was up to me, I wouldn’t have closed the PR for the reasons I mentioned above. Nothing else to add at this point. @teriu feel free to open a new one referring this one, please.

**Comment by teriu** [comment]
Lol. Yea I can do that.

**Comment by teriu** [comment]
FWIW I don't get why it matters what branch in the fork I PR from, as @robertohuertasm that doesn't affect anything here, it's my preference given the nature of the change (and something I've done in other OS projects when there is a small correction/feature).

**Comment by teriu** [comment]
Re-opened in https://github.com/vscode-icons/vscode-icons/pull/3451

**Comment by JimiC** [comment]
It is a good practice to PR from a branch other than `master`. You can rebase or merge any changes made to `master` easier this way.

**Comment by JimiC** [comment]
@robertohuertasm I didn't had a clear mind this morning so I couldn't pinpoint my main reason for using a branch other than `master` for PR's. It just stroke me. We require that all PR's need to be up to date with `master` before they get merged. So if a contributor PR's from his `master` it screws us over.

**Comment by robertohuertasm** [comment]
That only means that the contributor must sync our master changes with his/herd before merging. He or she has to be sure to comply with that. If not the PR won’t be merged. So I don’t see how this could be a problem for us tbh.

**Comment by JimiC** [comment]
We will have to ask the contributor to do the work anyways. See where I'm getting at?

**Comment by robertohuertasm** [comment]
Honestly, I don't. You don't want to change your mind, that's fine. I gave already my arguments. The contributor will have an indication via github that he has to update the branch, so it's clear, we don't have to ask if we don't want, the platform will do that for us. I don't see the point on going on with this discussion anymore.

**Comment by JimiC** [comment]
Eventually, you will see my logic in the long run.

**Comment by robertohuertasm** [comment]
Man, if you have to close the PR for that, which is already an interaction, what's the cost of a potential extra warning to the user (given that GitHub kindly does that for us and we could even avoid that). It makes no sense. By closing like that the PR, the contributor may be perceiving that as hostile act and we may lose his/her interest in contributing. For me this is crystal clear, and I prefer to care for the contributor, take the time to explain if that's the case, than blindly pushing the close button with a very cold message. But that's a matter of style in communication, which clearly you and I differ a lot, and hence, this kind of discussions which lead to nowhere. You have your way, and I have a very different one. That's it. It's not a matter of seeing your logic nor mine. Each of us function in a very different way, for better or worse.

**Comment by JimiC** [comment]
> take the time to explain if that's the case
I did here https://github.com/vscode-icons/vscode-icons/pull/3449#issuecomment-1965893887
If you perceive it as a "cold message" that's your opinion.

**Pull request closed without merging**
