### PR TITLE
Add more jest extensions

### PR DESCRIPTION
**Pull request by 9KwHCUDP**
**Changes proposed:**

- [x] Add

### CODE REVIEW

**Comment by robertohuertasm** [comment]
@9KwHCUDP can you provide more information about this addition? Are this supported or common `jest` config files?

**Comment by robertohuertasm** [comment]
A quick search at Google for these extensions show almost no significant results at all. I'm under the impression that this may be a use case of custom extensions and we should close this. Waiting for @9KwHCUDP to make his/her case.

**Comment by 9KwHCUDP** [comment]
@robertohuertasm These are common jest config files, which are currently used by community. Since it doesn't support `.jsonrc` because config files should end with either `js` or `json`. Links: [#1](https://github.com/search?q=%22.jestrc.json%22&type=Code), [#2](https://github.com/search?q=%22.jestrc.js%22&type=Code)

**Comment by JimiC** [comment]
https://jestjs.io/docs/en/configuration
>Jest's configuration can be defined in the package.json file of your project, or through a jest.config.js file or through the --config <path/to/js|json> option.

**Comment by robertohuertasm** [comment]
These links you provided gave only 283 hits vs a total of 24484 for the official `jest.config.js|json` oficial extension, which roughly means that these extensions represent just the 1.15% of the total usage. It doesn't seem to me like a widely used extesions at all. 

I understand that some people are using it but, as @JimiC pointed out, it's not even the official extension. What do you think about this @vscode-icons/development ?

**Comment by robertohuertasm** [comment]
@9KwHCUDP don't get me wrong. I really appreciate the time you took to do this PR. It's just that we have a policy of only allow documented or widely used extensions. If not, we have support for custom extensions so people can use the icon and extension combination they want.

**Comment by 9KwHCUDP** [comment]
Why does it include `.jestrc` then, it's also not official extension, and no one can use it, since jest can't even read it.

**Comment by robertohuertasm** [comment]
This was a legacy thing. We kept it just because of backwards compatibility.

**Comment by robertohuertasm** [comment]
Just for the sake of history #828. Here we were already debating if we should introduce or not the unofficial `.jestrc`. Back in the day, 2017, `Jest` was not so widely used but there was a significant amount of repos using this extension. That's why I voted in favor of including it. This just doesn't seem the same case to me. But let's hear what the other team members have to say if they want to comment on this. 😊

**Comment by JimiC** [comment]
Basically, I'm in favor of: Since it's a custom config name it falls under the customization feature support. But this is so trivial that I don't mind merging it even if it's for the 1.15% of the repo base.

**Comment by robertohuertasm** [comment]
Ok then. It goes in.

**Pull request merged**
