### PR TITLE
feat(icon): add .objidconfig icon

### LINKED ISSUE #3003: [Icon Request] Support for AL Object ID Ninja configuration file
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:

  - Type: `filename`
  - Icon Name: `objidconfig`
  - Sample original Icon: logo
  - Filenames: `.objidconfig`

- More info: https://marketplace.visualstudio.com/items?itemName=vjeko.vjeko-al-objid

### PR DESCRIPTION
**Pull request by vjekob**
_**Fixes #3003 **_

**Changes proposed:**

- [x] Add

Adds AL Object ID Ninja configuration file (.objidconfig)

### CODE REVIEW

**Review by sasial-dev — CHANGES_REQUESTED** [review]
Why do you have three files?
You can remove `icons/file_type_light_objidconfig-light.svg`!

**Review by sasial-dev — DISMISSED** [review]
LGTM!

**Comment by vjekob** [comment]
> LGTM!

Any chance this gets included in the next release? I mean, all checks are passing, please let me know if there is anything I can do to make this satisfy any requirements this PR doesn't already satisfy. Thanks a bunch! :)

**Comment by robertohuertasm** [comment]
@vjekob it looks good. I will just try to optimize the icons and that's it. Ideally, this will be in today's release. Thanks for the contribution!

**Comment by robertohuertasm** [comment]
Just to clarify. We always try to prepare icons so their size is max 2Kb. These icons are huge: 21 and 16 Kb. Let's see if Illustrator can optimize them.

**Comment by robertohuertasm** [comment]
In a first pass, I've halved their size but it's still big (around 10Kb). I see the circle of the ninja has lots of points. I guess we could simplify that.

**Comment by robertohuertasm** [comment]
I've just optimized the icons to weight under 2kb. While at it, I've realized that the icon is slightly different from the one in #3003. Specially the knot in the left. It's a minor detail, but it would be nice to get the original one at some point. @vjekob do you know where to get it?

**Review by robertohuertasm — APPROVED** [review]

**Comment by vjekob** [comment]
> I've just optimized the icons to weight under 2kb. While at it, I've realized that the icon is slightly different from the one in #3003. Specially the knot in the left. It's a minor detail, but it would be nice to get the original one at some point. @vjekob do you know where to get it?

@robertohuertasm Thanks for optimizing the icons, and sorry for sending you large icons. I only had the originals in the PNG format, and I used an online tool to convert them to SVG.

I've now converted them to SVG using Illustrator, and they are both 3KB in size. Do you want to include them, or should I create another pull request?

file_type_light_objidconfig svg
file_type_objidconfig

**Comment by robertohuertasm** [comment]
@vjekob if they're better than the ones that we've included, yes, I'd really appreciate if you could create a new PR. I'm planning to release again this week.

**Pull request merged**
