### PR TITLE
Update extensions for Stylelint icon

### PR DESCRIPTION
**Pull request by ModyQyW**
https://stylelint.io/user-guide/configure/

image

**Changes proposed:**

- [ ] Add
- [ ] Delete
- [x] Fix
- [ ] Prepare

### CODE REVIEW

**Comment by JimiC** [comment]
DO NOT commit on master. Always use a branch.

**Comment by ModyQyW** [comment]
Sorry, but I don't get your point. Which branch should I merge into? It looks like the master is the only active branch.

image

**Comment by JimiC** [comment]
1. Create a new branch on your forked repo.
2. Commit your changed on the new branch.
3. Request a pull from your branch to `vscode/master`.

**Comment by ModyQyW** [comment]
Get it. I will send another one. Thank you.

**Pull request closed without merging**
