### PR TITLE
Add support for Wenyan Lang

### PR DESCRIPTION
**Pull request by antfu**
[Wenyan Lang](https://github.com/LingDong-/wenyan-lang) is a programming language for the ancient Chinese which grows rapidly in recent weeks.

Thanks.

### CODE REVIEW

**Comment by KingDarBoja** [comment]
Just as extra info: [wenyan-lang vscode](https://github.com/antfu/wenyan-lang-vscode)

**Comment by antfu** [comment]
> 1.Icon needs adjustment.

What can I do to improve the icon? The icon is a Chinese letter `言` made by ASCII.

> 2.Either usage of language id or file extensions, not both.

Sorry I am not very familiar with the pipeline. Should I remove language or file extension in this case?

Thanks!

**Comment by KingDarBoja** [comment]
@antfu The icon is okay, the only issue is related to size. Don't worry, I can fix it 💯

**Comment by KingDarBoja** [comment]
Hey @antfu, any reason of closing this PR? It was ready for merge on next release!

**Comment by JimiC** [comment]
Was wondering the same think.

**Comment by antfu** [comment]
Sorry for that, I thought this is kinda "inactive". Happy to see it get merged, thanks!

**Pull request merged**
