### PR TITLE
Add support for tox 

### LINKED ISSUE #2065: [Icon Request] Support for tox file
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `tox`
  - Sample original Icon: tox
  - Filenames: `tox.ini`

- More info: https://tox.readthedocs.io/en/latest/

### PR DESCRIPTION
**Pull request by oriash93**
_**Fixes #2065**_

**Changes proposed:**

- [x] Add

### CODE REVIEW

**Comment by JimiC** [comment]
Nope. A `png` wrapped around an `svg` is not the way to do it.

**Comment by oriash93** [comment]
> Nope. A `png` wrapped around an `svg` is not the way to do it.

Is there any tool to convert .png to .svg? I only have that one image.

**Comment by JimiC** [comment]
No free tool I'm afraid. But still, you are better of finding a true `svg` version of the icon. If not exists ask the project owner to provide you with one.

**Comment by JimiC** [comment]
It isn't that hard to find it. https://github.com/tox-dev/tox/blob/master/docs/_static/img/tox.svg

**Comment by JimiC** [comment]
Still needs adjustment.
@KingDarBoja Are you up for it?

**Comment by KingDarBoja** [comment]
> Still needs adjustment.
> @KingDarBoja Are you up for it?

Sure, let me get some time and I will fix it asap.

**Comment by JimiC** [comment]
We want only the graphics part of the logo.

**Comment by KingDarBoja** [comment]
> We want only the graphics part of the logo.

Done:

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><title>file_type_tox</title><path d="M21.68,27.41c-.078-.083-.145-.223-.235-.24-2.108-.405-4.187-.962-6.326-1.194L15.826,30H17.97c.08-.214.292-.1.429-.176L21.68,27.41Z" style="fill:#769788"/><polygon points="9.527 25.543 9.527 25.543 9.527 25.543 9.527 25.543" style="fill:#8ba97b"/><path d="M15.119,25.976q-.009-.071-.015-.141h0c-1.86.009-3.713-.126-5.564-.286h0l-.013-.006c1.1,1.006,2.186,2.021,3.3,3.013a7.894,7.894,0,0,1,1.287,1.316h0a.393.393,0,0,1,0,.128h1.715l-.707-4.024Z" style="fill:#8ba97b"/><polygon points="18.952 8.885 18.952 8.885 18.952 8.885 18.952 8.885" style="fill:#555f61"/><path d="M30,15.335h0a.5.5,0,0,0-.037-.119q-2.682-.865-5.363-1.733c-1.027-.336-1.024-.342-.4-1.2q1.6-2.193,3.2-4.388a4.361,4.361,0,0,0-.969-1.181h0c-2.456.814-4.943,1.517-7.442,2.178l-.037-.009.018.148c1.59,1.3,3.092,2.707,4.553,4.153h0q-.229,2.184-.46,4.367c-.081.751-.168,1.5-.252,2.253l.028,0c2.371-.914,4.7-1.931,7.112-2.743h0L30,16.805q0-.735,0-1.47Z" style="fill:#555f61"/><path d="M10.819,8.455h0a1.382,1.382,0,0,0,.9.143,49.978,49.978,0,0,1,5.19.206,11.689,11.689,0,0,1,2.045.081h0l.037.009q-.579-2.155-1.156-4.312h0A15.49,15.49,0,0,1,17.084,2.9a.95.95,0,0,0-1.149-.767,6.33,6.33,0,0,1-.848-.015c.065-.013.13-.023.2-.034a1.639,1.639,0,0,0-.2.034.126.126,0,0,0-.115.025q-1.89,2.854-3.78,5.709C11.061,8.046,10.943,8.252,10.819,8.455Z" style="fill:#7e813d"/><path d="M10.666,8.609h0l.153-.154h0c.124-.2.242-.409.373-.607q1.889-2.856,3.78-5.709a7.2,7.2,0,0,0-2.3.293A13.077,13.077,0,0,0,5.5,6.859l5.162,1.75Z" style="fill:#abb130"/><path d="M6.963,14.968c.117.283.277.547.417.82h0q1.5-3.243,3-6.484c.089-.192.2-.373.3-.559a1.231,1.231,0,0,0-.016-.136h0L5.5,6.859a5.988,5.988,0,0,0-1.235,1.6h0Q5.615,11.716,6.963,14.968Z" style="fill:#c2ca37"/><path d="M26.005,22.915c-1.02-1.03-2.057-2.041-3.16-2.981h0a26.059,26.059,0,0,0-.437,3.175c-.176,1.273-.3,2.554-.445,3.832a.576.576,0,0,1-.283.469h0L18.4,29.824a13.834,13.834,0,0,0,5.057-1.953,11.727,11.727,0,0,0,3.94-3.746A5.46,5.46,0,0,1,26.005,22.915Z" style="fill:#587789"/><path d="M9.527,25.543h0l.013.006h0l-.01-.143h0c-.623-2.251-1.033-4.551-1.56-6.823-.205-.881-.374-1.77-.559-2.656l-.031,0h0l-.121.009c-.374,1.388-1.022,2.671-1.522,4.01-.359.961-.779,1.9-1.165,2.851-.1.243-.151.511-.444.606h0A9.429,9.429,0,0,0,5.95,25.7C7.147,25.763,8.333,25.569,9.527,25.543Z" style="fill:#bcd05f"/><path d="M22.845,19.933h0c1.1.94,2.14,1.951,3.16,2.981a5.46,5.46,0,0,0,1.391,1.21,12.042,12.042,0,0,0,2.555-7.065h0c-2.41.812-4.741,1.829-7.112,2.743A.936.936,0,0,0,22.845,19.933Z" style="fill:#2e4880"/><path d="M24.6,13.483q2.679.873,5.363,1.733A12.52,12.52,0,0,0,27.4,7.9h0q-1.6,2.194-3.2,4.388C23.571,13.141,23.568,13.147,24.6,13.483Z" style="fill:#364673"/><path d="M4.572,22.794c.386-.952.806-1.89,1.165-2.851.5-1.339,1.148-2.622,1.522-4.01L2,15.927H2A13.5,13.5,0,0,0,4.128,23.4h0C4.421,23.305,4.474,23.037,4.572,22.794Z" style="fill:#d4e64e"/><path d="M7.259,15.933l.121-.009h0a.772.772,0,0,0,0-.136h0c-.14-.273-.3-.537-.417-.82q-1.355-3.25-2.694-6.507h0A13.393,13.393,0,0,0,2,15.927H2Z" style="fill:#d5e238"/><path d="M17.833,4.582h0q.578,2.156,1.156,4.312c2.5-.661,4.986-1.364,7.442-2.178h0a4.213,4.213,0,0,0-1.16-1.137q-2.877-.394-5.753-.788C18.957,4.715,18.4,4.651,17.833,4.582Z" style="fill:#5a614f"/><path d="M15.935,2.129a.95.95,0,0,1,1.149.767,15.49,15.49,0,0,0,.749,1.686h0c.562.069,1.124.133,1.685.209q2.877.39,5.753.788a12.066,12.066,0,0,0-5.92-3.141,10.743,10.743,0,0,0-4.068-.358c-.066.011-.131.021-.2.034A6.33,6.33,0,0,0,15.935,2.129Z" style="fill:#656945"/><path d="M12.823,28.556c-1.11-.992-2.2-2.007-3.3-3.013h0c-1.194.026-2.38.22-3.577.161a13.447,13.447,0,0,0,8.16,4.168h0A7.894,7.894,0,0,0,12.823,28.556Z" style="fill:#9fb96e"/><path d="M22.688,19.8h0a10.538,10.538,0,0,1-2.028,1.668c-1.707,1.364-3.439,2.7-5.165,4.037a2.012,2.012,0,0,1-.378.186h0c0,.047-.007.094-.013.141h0q.006.071.015.141h0c2.139.232,4.218.789,6.326,1.194.09.017.157.157.235.24h0a.576.576,0,0,0,.283-.469c.143-1.278.269-2.559.445-3.832a26.059,26.059,0,0,1,.437-3.175h0a.936.936,0,0,1-.006-.13l-.028,0Z" style="fill:#6e897c"/><path d="M15.117,25.694h0A1.412,1.412,0,0,1,14.971,25c.1-2.342-.217-4.676-.136-7.016.039-1.128-.189-2.236-.159-3.359a41.11,41.11,0,0,0-1.912,3.919c-1.114,2.269-2.16,4.573-3.234,6.862h0l.01.143h0c1.851.16,3.7.3,5.564.286h0C15.11,25.788,15.114,25.741,15.117,25.694Z" style="fill:#899f66"/><path d="M16.613,14.156c-.562.083-1.2-.047-1.642.474h0q3.543,2.354,7.084,4.709c.218.144.422.309.633.464h0l.123,0c.084-.751.171-1.5.252-2.253q.233-2.184.46-4.367C21.219,13.507,18.914,13.816,16.613,14.156Z" style="fill:#647665"/><path d="M18.952,8.885h0A11.689,11.689,0,0,0,16.907,8.8a49.978,49.978,0,0,0-5.19-.206,1.382,1.382,0,0,1-.9-.143h0l-.153.154h0a1.231,1.231,0,0,1,.016.136,31.6,31.6,0,0,1,2.241,3.1c.609.816,1.174,1.665,1.758,2.5,1.056-1.1,1.879-2.385,2.842-3.558q.722-.879,1.447-1.755h0l-.018-.148Z" style="fill:#869048"/><path d="M17.523,10.788c-.963,1.173-1.786,2.46-2.842,3.558l-.016.148h0l.033,0h0l.273.141h0c.443-.521,1.08-.391,1.642-.474,2.3-.34,4.606-.649,6.91-.97h0c-1.461-1.446-2.963-2.848-4.553-4.153h0Q18.247,9.911,17.523,10.788Z" style="fill:#727f5f"/><path d="M14.665,14.494l.016-.148c-.584-.834-1.149-1.683-1.758-2.5a31.6,31.6,0,0,0-2.241-3.1c-.1.186-.213.367-.3.559q-1.5,3.24-3,6.484h0a.772.772,0,0,1,0,.136h0l.031,0Z" style="fill:#a5b14b"/><path d="M12.764,18.544a41.11,41.11,0,0,1,1.912-3.919c.006-.046.014-.091.022-.136l-.033,0h0L7.411,15.927c.185.886.354,1.775.559,2.656.527,2.272.937,4.572,1.56,6.823h0C10.6,23.117,11.65,20.813,12.764,18.544Z" style="fill:#a4b558"/><polygon points="14.698 14.489 14.698 14.489 14.698 14.489 14.698 14.489" style="fill:#a4b558"/><path d="M14.676,14.625c-.03,1.123.2,2.231.159,3.359-.081,2.34.237,4.674.136,7.016a1.412,1.412,0,0,0,.145.694h0a2.012,2.012,0,0,0,.378-.186c1.726-1.34,3.458-2.673,5.165-4.037A10.538,10.538,0,0,0,22.688,19.8h0c-.211-.155-.415-.32-.633-.464q-3.54-2.358-7.084-4.709h0l-.273-.141h0C14.69,14.534,14.682,14.579,14.676,14.625Z" style="fill:#7b916e"/></svg>
```

**Pull request merged**
