### PR TITLE
Update dependencies.

### PR DESCRIPTION
**Pull request by JimiC**
I suggest we keep this PR open until we are about to release. We can add more commits as dependencies updates are released.

### CODE REVIEW

**Comment by JimiC** [comment]
I wanted to update this PR for npm5 but...

**Comment by jens1o** [comment]
do a second one as long as he didn't released 😄

**Comment by JimiC** [comment]
I thought the next release date was on 12th June.

**Comment by JimiC** [comment]
Looks like I had already updated `package-lock.json`.

**Pull request merged**
