### PR TITLE
Add support for Jenkinsfile

### PR DESCRIPTION
**Pull request by chuongtrh**
**Changes proposed:**

- [x] Add
- [ ] Delete
- [ ] Fix
- [ ] Prepare

Screen Shot 2020-05-18 at 4 03 51 PM

### CODE REVIEW

**Comment by JimiC** [comment]
Already supported via marketplace extension https://github.com/vscode-icons/vscode-icons/wiki/ListOfFiles

**Comment by chuongtrh** [comment]
hi @JimiC I have checked this list but still not work with file **Jenkinsfile**
Can you double-check again? Thanks

**Comment by JimiC** [comment]
https://marketplace.visualstudio.com/items?itemName=ivory-lab.jenkinsfile-support

**Comment by chuongtrh** [comment]
Why need to install **JenkinsFile Support** extension?

**Comment by JimiC** [comment]
Use customization feature if you don't want to. 
https://github.com/vscode-icons/vscode-icons/wiki/FineTuning

**Comment by chuongtrh** [comment]
Agree, we have few ways to achieve a goal. But I think that file **Jenkinsfile** supported by vscode-icons is better. 

Anyway, have an issue with file **Jenkinsfile** and [ListOfFiles](https://marketplace.visualstudio.com/items?itemName=ivory-lab.jenkinsfile-support) not correct.

Thank you reply!

**Pull request closed without merging**
