### PR TITLE
refactor(icon): update css icon

### PR DESCRIPTION
**Pull request by jonrandahl**
With the [official release of the CSS icon](https://github.com/CSS-Next/logo.css), this PR he updates the css and cssmap icons currently using the old icon to use the new icon.

**Changes proposed:**

- icons/file_type_css.svg
   - The icon was positioned to sit on the document the same as the previous icon.
   - The file was optimized and minified using SVGOMG.
- icons/file_type_cssmap.svg
   - All colors were updated to use rebeccapurple.
   - The file was optimized and minified using SVGOMG.

### CODE REVIEW

**Review by KingDarBoja — APPROVED** [review]
LGTM 🚀 Love the new official logo :)

**Comment by prakal** [comment]
Screenshot 2024-12-22 at 2 59 24 PM

Should the folder icon also change? :) I updated to the latest and it still shows the old icon.

**Comment by jonrandahl** [comment]
Thanks @prakal I'm working on the two specific to the CSS extension, stay tuned!

**Comment by acefhiloptu** [comment]
I see the folder icon is being shown in the ListOfFolders wiki-page, but it's still not showing up in the current version?

**Pull request merged**
