### PR TITLE
Feat(icon): Added safetensors extension support

### LINKED ISSUE #3499: [Icon Request]: Add icon for safetensors
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Icon Type

- [X] File Icon
- [ ] Folder Icon

### Icon Type

- [X] Extension
- [ ] Filename
- [ ] Language ID

### Original Icon

safetensor logo

### Icon Information

Safetensors has become a prominent file format for saving tensors for deep learning.
This issue is for adding the safetensors icon to vscode-icons.

### More Information:

_No response_

### PR DESCRIPTION
**Pull request by SHADOW-LIGHTS**
_**Fixes #3499**_

**Changes proposed:**

- [x] Add
- [ ] Delete
- [ ] Fix
- [ ] Prepare

**Safetensors** is a file format for storing and distributing tensors, which are multi-dimensional arrays often used in machine learning algorithms.

### CODE REVIEW

**Comment by mayank31398** [comment]
@robertohuertasm can you take a look at this PR?
people from HuggingFace would love this icon support :)

**Comment by mayank31398** [comment]
Hi, any updates on this? 🤗

**Comment by SHADOW-LIGHTS** [comment]
Yeah added icon for dark and light mode

**Review by robertohuertasm — APPROVED** [review]
LGTM 🚀 Thanks for your contribution ❤️

**Comment by mayank31398** [comment]
awesome 🥳

**Pull request merged**
