### PR TITLE
Fix typescript-eslint plugin 2.22.0

### LINKED ISSUE #2396: An in-range update of @typescript-eslint/eslint-plugin is breaking the build 🚨
## The devDependency [@typescript-eslint/eslint-plugin](https://github.com/typescript-eslint/typescript-eslint) was updated from `2.21.0` to `2.22.0`.

🚨 [View failing branch](https://github.com/vscode-icons/vscode-icons/compare/master...vscode-icons:greenkeeper%2F%40typescript-eslint%2Feslint-plugin-2.22.0).

This version is **covered** by your **current version range** and after updating it in your project **the build failed**.

@typescript-eslint/eslint-plugin is a devDependency of this project. It **might not break your production code or affect downstream projects**, but probably breaks your build or test tools, which may **prevent deploying or publishing**.

<details>
<summary>Status Details</summary>

- ❌ **continuous-integration/appveyor/branch:** AppVeyor build failed ([Details](https://ci.appveyor.com/project/robertohuertasm/vscode-icons/builds/31188332)).
- ❌ **continuous-integration/travis-ci/push:** The Travis CI build failed ([Details](https://travis-ci.org/vscode-icons/vscode-icons/builds/657414067?utm_source=github_status&utm_medium=notification)).
</details>

---

<details>
<summary>Release Notes for v2.22.0</summary>

<h1><a href="https://urls.greenkeeper.io/typescript-eslint/typescript-eslint/compare/v2.21.0...v2.22.0">2.22.0</a> (2020-03-02)</h1>
<h3>Bug Fixes</h3>
<ul>
<li><strong>eslint-plugin:</strong> [ban-types] add option extendDefaults (<a href="https://urls.greenkeeper.io/typescript-eslint/typescript-eslint/issues/1379" data-hovercard-type="pull_request" data-hovercard-url="/typescript-eslint/typescript-eslint/pull/1379/hovercard">#1379</a>) (<a href="https://urls.greenkeeper.io/typescript-eslint/typescript-eslint/commit/ae7f7c5637124b1167efd63755df92e219bbbb24">ae7f7c5</a>)</li>
<li><strong>eslint-plugin:</strong> [default-param-last] handle param props (<a href="https://urls.greenkeeper.io/typescript-eslint/typescript-eslint/issues/1650" data-hovercard-type="pull_request" data-hovercard-url="/typescript-eslint/typescript-eslint/pull/1650/hovercard">#1650</a>) (<a href="https://urls.greenkeeper.io/typescript-eslint/typescript-eslint/commit/3534c6ea09f0cb2162017660a90c6a4ad704da6b">3534c6e</a>)</li>
<li><strong>eslint-plugin:</strong> [no-implied-eval] correct logic for ts3.8 (<a href="https://urls.greenkeeper.io/typescript-eslint/typescript-eslint/issues/1652" data-hovercard-type="pull_request" data-hovercard-url="/typescript-eslint/typescript-eslint/pull/1652/hovercard">#1652</a>) (<a href="https://urls.greenkeeper.io/typescript-eslint/typescript-eslint/commit/33e3e6f79ea21792ccb60b7f1ada74057ceb52e9">33e3e6f</a>)</li>
</ul>
<h3>Features</h3>
<ul>
<li><strong>eslint-plugin:</strong> [explicit-member-accessibility] autofix no-public (<a href="https://urls.greenkeeper.io/typescript-eslint/typescript-eslint/issues/1548" data-hovercard-type="pull_request" data-hovercard-url="/typescript-eslint/typescript-eslint/pull/1548/hovercard">#1548</a>) (<a href="https://urls.greenkeeper.io/typescript-eslint/typescript-eslint/commit/dd233b52dcd5a39d842123af6fc775574abf2bc2">dd233b5</a>)</li>
<li><strong>eslint-plugin:</strong> [typedef] add variable-declaration-ignore-function (<a href="https://urls.greenkeeper.io/typescript-eslint/typescript-eslint/issues/1578" data-hovercard-type="pull_request" data-hovercard-url="/typescript-eslint/typescript-eslint/pull/1578/hovercard">#1578</a>) (<a href="https://urls.greenkeeper.io/typescript-eslint/typescript-eslint/commit/fc0a55e8b78203972d01a7c9b79ed6b470c5c1a0">fc0a55e</a>)</li>
<li><strong>eslint-plugin:</strong> add new no-base-to-string rule (<a href="https://urls.greenkeeper.io/typescript-eslint/typescript-eslint/issues/1522" data-hovercard-type="pull_request" data-hovercard-url="/typescript-eslint/typescript-eslint/pull/1522/hovercard">#1522</a>) (<a href="https://urls.greenkeeper.io/typescript-eslint/typescript-eslint/commit/8333d41d5d472ef338fb41a29ccbfc6b16e47627">8333d41</a>)</li>
<li><strong>eslint-plugin:</strong> add prefer-readonly-parameters (<a href="https://urls.greenkeeper.io/typescript-eslint/typescript-eslint/issues/1513" data-hovercard-type="pull_request" data-hovercard-url="/typescript-eslint/typescript-eslint/pull/1513/hovercard">#1513</a>) (<a href="https://urls.greenkeeper.io/typescript-eslint/typescript-eslint/commit/3be98542afd7553cbbec66c4be215173d7f7ffcf">3be9854</a>)</li>
<li><strong>eslint-plugin:</strong> additional annotation spacing rules for va… (<a href="https://urls.greenkeeper.io/typescript-eslint/typescript-eslint/issues/1496" data-hovercard-type="pull_request" data-hovercard-url="/typescript-eslint/typescript-eslint/pull/1496/hovercard">#1496</a>) (<a href="https://urls.greenkeeper.io/typescript-eslint/typescript-eslint/commit/b097245df35114906b1f9c60c3ad4cd698d957b8">b097245</a>)</li>
</ul>
</details>

<details>
<summary>Commits</summary>
<p>The new version differs by 10 commits.</p>
<ul>
<li><a href="https://urls.greenkeeper.io/typescript-eslint/typescript-eslint/commit/5a097d316fb084dc4b13e87d68fe9bf43d8a9548"><code>5a097d3</code></a> <code>chore: publish v2.22.0</code></li>
<li><a href="https://urls.greenkeeper.io/typescript-eslint/typescript-eslint/commit/3be98542afd7553cbbec66c4be215173d7f7ffcf"><code>3be9854</code></a> <code>feat(eslint-plugin): add prefer-readonly-parameters (#1513)</code></li>
<li><a href="https://urls.greenkeeper.io/typescript-eslint/typescript-eslint/commit/b097245df35114906b1f9c60c3ad4cd698d957b8"><code>b097245</code></a> <code>feat(eslint-plugin): additional annotation spacing rules for va… (#1496)</code></li>
<li><a href="https://urls.greenkeeper.io/typescript-eslint/typescript-eslint/commit/33e3e6f79ea21792ccb60b7f1ada74057ceb52e9"><code>33e3e6f</code></a> <code>fix(eslint-plugin): [no-implied-eval] correct logic for ts3.8 (#1652)</code></li>
<li><a href="https://urls.greenkeeper.io/typescript-eslint/typescript-eslint/commit/fc0a55e8b78203972d01a7c9b79ed6b470c5c1a0"><code>fc0a55e</code></a> <code>feat(eslint-plugin): [typedef] add variable-declaration-ignore-function (#1578)</code></li>
<li><a href="https://urls.greenkeeper.io/typescript-eslint/typescript-eslint/commit/8333d41d5d472ef338fb41a29ccbfc6b16e47627"><code>8333d41</code></a> <code>feat(eslint-plugin): add new no-base-to-string rule (#1522)</code></li>
<li><a href="https://urls.greenkeeper.io/typescript-eslint/typescript-eslint/commit/dd233b52dcd5a39d842123af6fc775574abf2bc2"><code>dd233b5</code></a> <code>feat(eslint-plugin): [explicit-member-accessibility] autofix no-public (#1548)</code></li>
<li><a href="https://urls.greenkeeper.io/typescript-eslint/typescript-eslint/commit/baf7c98aa24cbc0a6c69ab41701acd3cf4fc36ad"><code>baf7c98</code></a> <code>docs(eslint-plugin): [consistent-type-assertion] improve docs (#1651)</code></li>
<li><a href="https://urls.greenkeeper.io/typescript-eslint/typescript-eslint/commit/ae7f7c5637124b1167efd63755df92e219bbbb24"><code>ae7f7c5</code></a> <code>fix(eslint-plugin): [ban-types] add option extendDefaults (#1379)</code></li>
<li><a href="https://urls.greenkeeper.io/typescript-eslint/typescript-eslint/commit/3534c6ea09f0cb2162017660a90c6a4ad704da6b"><code>3534c6e</code></a> <code>fix(eslint-plugin): [default-param-last] handle param props (#1650)</code></li>
</ul>
<p>See the <a href="https://urls.greenkeeper.io/typescript-eslint/typescript-eslint/compare/4eedd7f5713b4967fe975ab30bd8f6a8323c81d2...5a097d316fb084dc4b13e87d68fe9bf43d8a9548">full diff</a></p>
</details>

<details>
<summary>FAQ and help</summary>

There is a collection of [frequently asked questions](https://greenkeeper.io/faq.html). If those don’t help, you can always [ask the humans behind Greenkeeper](https://github.com/greenkeeperio/greenkeeper/issues/new).
</details>

---

Your [Greenkeeper](https://greenkeeper.io) Bot :palm_tree:

### PR DESCRIPTION
**Pull request by KingDarBoja**
_**Fixes #2396**_

**Changes proposed:**

- [ ] Add
- [ ] Delete
- [x] Fix
- [ ] Prepare

### CODE REVIEW

**Comment by JimiC** [comment]
We do mass updates before release. Usually.

**Comment by robertohuertasm** [comment]
Why closing this? I don't see the problem.

**Comment by JimiC** [comment]
@robertohuertasm do u want to have to write entries in change log for every dependency update? Be my guest. From my pov it's better to do mass dependency updates.

**Comment by robertohuertasm** [comment]
Generally speaking, I agree. But for this one, which included manual @KingDarBoja changes I thought it would be ok. I don't mind writing one extra log entry if that means saving anyone  from repeating again the same task.. 😊

**Comment by JimiC** [comment]
Even though it's best to keep dependencies updates tight. @KingDarBoja can include these changes on the mass update.

**Comment by JimiC** [comment]
Additional, I had a look at the release notes. The changes Manuel did to the rule are trivial as those are the default values.

**Comment by JimiC** [comment]
On the same note I plan on doing some cleanup on the rules. I already done so on my projects as a testing ground.

**Comment by robertohuertasm** [comment]
Fair enough! 👍🏻👌🏻

**Comment by KingDarBoja** [comment]
@JimiC Those changes seem to be the default values until you try to fix the spacing before the arrow (or after the colon?) and save the file, the lint-stage hook will automatically remove the space and once again, trigger the ESLint warning.

Also, the overrides of `variable` seems to do the work, as the colon setting doesn't work as stated on the docs.

**Comment by JimiC** [comment]
I'll have a look at it.

**Comment by robertohuertasm** [comment]
Shall we reopen this to not keep track of it?

**Comment by JimiC** [comment]
Give me some time pls.

**Comment by JimiC** [comment]
After testing it the rule has issues.

First of all the correct syntax when using options is:
```
"@typescript-eslint/type-annotation-spacing": [
      "error",
      {
        "overrides": {
          "arrow": {
            "before": true,
            "after": true
          }
        }
      }
    ],
```
but even using it, it produces the same error. My syggestion is to wait untill a fix is provided (I may get involved in this).

**Comment by JimiC** [comment]
The issue is caused by the rule not recognizing the `new` keyword.
`type Class = new (...args: any[]) => any;` fails but `type Class = (...args: any[]) => any;` passes but then the type annotation fails.

**Comment by JimiC** [comment]
https://github.com/typescript-eslint/typescript-eslint/pull/1664

**Pull request closed without merging**
