### PR TITLE
refactor(typings): add types folder icon

### PR DESCRIPTION
**Pull request by sasial-dev**
_I promise this is the last one for today_

**Changes proposed:**

Add `types` to the typings folder icon

### CODE REVIEW

**Comment by robertohuertasm** [comment]
😁 No problem @sasial-dev! Thank you for your hard work. I won't have time today for reviewing more PRs. I expect to have more time during the week. I'm going to make a release with what we have already merged and prepare a new one for this week (hopefully).

**Comment by DrJume** [comment]
Why did you chose the green typings icon over the regular blue TypeScript folder icon for types?

I think a folder named 'types' contains regular exported types and interfaces for TypeScript in `.ts` files.

**Comment by PAXANDDOS** [comment]
> Why did you choose the green typings icon over the regular blue TypeScript folder icon for types?
> 
> I think a folder named 'types' contains regular exported types and interfaces for TypeScript in `.ts` files.

I believe that blue TypeScript icons are for source files, where is the actual code stored (`.ts`). And green ones are made specifically for types (folders and `.d.ts` files). So that could be easy to tell them apart without reading the file extension.

**Review by robertohuertasm — APPROVED** [review]
LGTM 🚀 Thanks for your contribution ❤️

**Pull request merged**
