### PR TITLE
Add better support for Django

### PR DESCRIPTION
**Pull request by batisteo**
**Changes proposed:**

- [ ] Add
- [ ] Delete
- [x] Fix
- [ ] Prepare

Add the file type `django` for `django-html`.

The file type is introduce by the/my [extension vscode-django](https://github.com/vscode-django/vscode-django) which avoid shadowing the `html` file type.

### CODE REVIEW

**Comment by JimiC** [comment]
Why don't you add [django-txt](https://github.com/vscode-django/vscode-django/blob/master/package.json#L41) as well, while you are at it?

**Comment by batisteo** [comment]
@JimiC I actually wanted to, and then reverted my changes fearing that would slow the merging process.
I’ll happily add it!

**Comment by JimiC** [comment]
You do not need to declare new `ILanguage`. A simple array of `ids` on the existing declaration will suffice.

**Comment by JimiC** [comment]
Make 
```
django: { ids: 'django-html', defaultExtension: 'html' },
```
to
```
django: { ids: ['django-html', 'django-txt'], defaultExtension: 'html' },
```
and you are donw. Don't worry about `defaultExtension`. It's a helper attribute for our examples generator tool. Doesn't play any role in the extension.

**Comment by batisteo** [comment]
Oh I see, cool thanks!

**Comment by batisteo** [comment]
@JimiC Is it good like that?

_(Is the last check hung?)_

**Comment by batisteo** [comment]
@robertohuertasm I hope I’m not pushy if I ask what’s blocking for a new release. :slightly_smiling_face:

**Comment by robertohuertasm** [comment]
Don't worry! We were just discussing that. That's been my fault for this release (too much things going on outside of Github) but hopefully this will be solved with the new changes introduced by @JimiC allowing new releases from any team member.

The new version will be released today or tomorrow!

**Pull request merged**
