### PR TITLE
Support for cargo

### PR DESCRIPTION
**Pull request by robertohuertasm**
**_Fixes #1367_**

**Changes proposed:**

- [x] Add
- [ ] Prepare
- [ ] Delete
- [ ] Fix

**Things I've done:**

- [x] My pull request fixes an issue, I referenced the issue.

### CODE REVIEW

**Comment by JimiC** [comment]
I don't know where you got it but it's good. Saved me the trouble of creating one.

**Comment by robertohuertasm** [comment]
I've created it from scratch using Illustrator. I'm not so `Rusty` as I thought! I'm glad you like it!

**Comment by JimiC** [comment]
I'm impressed. 😮

**Comment by robertohuertasm** [comment]
The pity is that when viewed in `vscode` it loses a lot of detail and it's not really as good as it may seem at first sight... but at least is recognizable. 😉

**Comment by JimiC** [comment]
I knew this would be the case from the start and thought of proposing to use the `crate` icon but it doesn't represent `Cargo`, so I hashed.

**Comment by robertohuertasm** [comment]
Yep, that's the problem with complex icons. I think that the result is not optimum in this case also but I guess that is fairly acceptable given the circumstances.

**Comment by JimiC** [comment]
You know that those icons shine on a 4K 32" monitor, right?

**Comment by robertohuertasm** [comment]
😂 I don't happen to have a 4K 32" monitor... for the moment! 😂 I guess you are one of the lucky ones?

**Comment by JimiC** [comment]
You kidding me?!? It's not `Black Friday` yet.

**Pull request merged**
