### PR TITLE
Add support for T4 Text Templates

### PR DESCRIPTION
**Pull request by zbecknell**
**Changes proposed:**

- [x] Add
- [ ] Delete
- [ ] Fix
- [ ] Prepare

Adds support for [T4 Text Templates](https://docs.microsoft.com/en-us/visualstudio/modeling/code-generation-and-t4-text-templates), file extension `.tt`.

### CODE REVIEW

**Comment by JimiC** [comment]
@zbecknell Why not use your extensions `t4` `language id`?

**Comment by JimiC** [comment]
We will provide the proper icon.

**Comment by zbecknell** [comment]
Yes, apologies on the art or other inconsistencies, as I've not done this before.  I suppose I could've just done a request.  I thought perhaps that I could've used `t4` as the identifier but wasn't sure it tied in that way.  In other words, just ignorance of how vscode-icons integrates.

**Comment by JimiC** [comment]
We prefer `language ids` associations. Keeps us less busy.

**Comment by zbecknell** [comment]
Roger that, I definitely understand how it ties in now.

**Comment by JimiC** [comment]
If it's too much of a hassle for you just close this PR, open an icon request issue and we'll do the rest.

**Comment by zbecknell** [comment]
I can do the language association -- would you still provide the art?

**Comment by JimiC** [comment]
Yeap.

**Comment by zbecknell** [comment]
Should I name the icon property "t4" or "tt" -- apologies for all the questions, it's just ambiguous for me.

**Comment by JimiC** [comment]
I would use `t4tt`.

**Comment by zbecknell** [comment]
Whoops, I'll move the line down to its proper alphabetical location.

**Comment by JimiC** [comment]
You are also missing an entry in <https://github.com/vscode-icons/vscode-icons/blob/master/src/icon-manifest/languages.ts>.

**Comment by JimiC** [comment]
`languageCollection` needs proper sorting also.

**Comment by zbecknell** [comment]
I'm really knocking it out of the park today.  Thanks for your help even though you could've done it much quicker, I learned some things.  Is my art outside the guidelines due to the 2 pixel margin?  I could probably fix that instead of making you work on it.

**Comment by JimiC** [comment]
Good job there. Regarding the art, it's that the icon is just too flat and the color won't show well on dark themes. Just leave it to me. I'll come up with something.

**Comment by zbecknell** [comment]
Sounds good.  T4 is so marginal I never found anything resembling an official logo, so it was left to me (a programmer programmer without much design skill) to make something.  I'm sure you'll make something nice.  It's so nice to have all the different file types have their unique icons using this extension, that I just had to try and contribute this missing one.

**Comment by JimiC** [comment]
@zbecknell I'm uploading here also a `png` version in case you want to use it.
t4

**Comment by zbecknell** [comment]
@JimiC Awesome, I've updated my icon to the new one! Thanks for all your help!

**Pull request merged**
