### PR TITLE
Adding support for  .dockerignore extension

### PR DESCRIPTION
**Pull request by vnoitkumar**
**Changes proposed:**

- [X] Add
- [ ] Delete
- [ ] Fix
- [ ] Prepare

dockerignore

This adds support for the .dockerignore extension

### CODE REVIEW

**Comment by JimiC** [comment]
Use [Docker for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-docker).

**Comment by vnoitkumar** [comment]
> 
> 
> Use [Docker for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-docker).

But what if I don't want to install Docker for VSCode

**Comment by JimiC** [comment]
Use our customization feature. See wiki.

**Comment by tsraza** [comment]
Hi @JimiC. Thanks for the info. I'm curious, what was the original problem that led to removing support for .dockerignore in #2104?

**Pull request closed without merging**
