### PR TITLE
feat(glitter): add support for glitter

### PR DESCRIPTION
**Pull request by robertohuertasm**
Related to #2698 which was force-pushed by mistake and originally created by @Milo123459

The problem with this PR is that the icon is not pure SVG and includes an image. It's about 13Kb when we're now aiming for 2Kb.

It's true this would be just one file in a project... @Milo123459 is there a way to make this file size smaller and pure svg?

### CODE REVIEW

**Comment by Milo123459** [comment]
I wouldn't know, I just converted a PNG to a SVG

**Comment by robertohuertasm** [comment]
How did you created the icon? Did you used illustrator, photoshop, other?

**Comment by Milo123459** [comment]
I stole the windows default emoji. I'm very creative!

**Comment by robertohuertasm** [comment]
Then we'll have to work on an svg version for this before publishing. Is there any chance to get the windows default emoji source?

**Comment by Milo123459** [comment]
I doubt it

**Comment by robertohuertasm** [comment]
I've created it with illustrator:
image
7kb not ideal, but taking into account this will be just one file per project...

It will be released in the next deployment.

**Comment by Milo123459** [comment]
Sounds good.

**Comment by KingDarBoja** [comment]
I made a version from scratch based on the PNG:

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><title>file_type_glitter</title><path d="M29.7,18.775C29.552,14.634,27.222,9.9,22.774,4.7a2.5,2.5,0,0,0-3.515-.272,2.651,2.651,0,0,0-.24.234,16.83,16.83,0,0,0-8.5-2.66A8.453,8.453,0,0,0,4.366,4.344a8.7,8.7,0,0,0-2.3,7.009,18.65,18.65,0,0,0,2.226,9.3,24.506,24.506,0,0,0,4.764,6.3l.022.021.037.035a2.492,2.492,0,0,0,3.473.059,17.109,17.109,0,0,0,8.928,2.926,8.453,8.453,0,0,0,6.149-2.338C29.75,25.566,30.47,22.417,29.7,18.775Z"/><ellipse cx="16.007" cy="16.009" rx="9.022" ry="14.666" transform="translate(-6.631 15.995) rotate(-44.968)" style="fill:#0078d7"/><path d="M11.022,26a.74.74,0,0,1-.506-.215l-.09-.087a22.7,22.7,0,0,1-4.511-5.926A15.471,15.471,0,0,1,4.837,7.1a.723.723,0,0,1,.905-.429.674.674,0,0,1,.463.834L6.2,7.534c-2.9,8.287,2.7,14.8,5.245,17.206.057.054.1.093.12.117a.653.653,0,0,1,.008.925c-.011.012-.024.024-.036.035A.743.743,0,0,1,11.022,26Z" style="fill:#0078d7"/><path d="M21.113,25.836a14.464,14.464,0,0,1-10.627-4.891,4.767,4.767,0,0,1-.427-.571C4.927,12.317,6.347,8.868,8.445,7.393a4.659,4.659,0,0,1,3.346-.755c9.35,1.3,10.521,8.753,10.531,8.828a.68.68,0,0,1-1.346.2h0C20.937,15.4,19.91,9.147,11.6,7.99A3.311,3.311,0,0,0,9.224,8.5c-2.28,1.6-1.578,5.558,1.978,11.138a3.128,3.128,0,0,0,.3.4A12.925,12.925,0,0,0,23.2,24.3a3.407,3.407,0,0,0,2.289-1.449c1.414-2.112,2.627-7.009-5.138-16.083a.68.68,0,1,1,1-.924c.012.012.023.026.034.039,8.348,9.756,6.862,15.294,5.234,17.725a4.762,4.762,0,0,1-3.2,2.035A14.542,14.542,0,0,1,21.113,25.836Z" style="fill:#3a96dd"/><path d="M12.955,9.244h-.176a1.973,1.973,0,0,0-1.937,1.7,8.349,8.349,0,0,0-.061,1A8.828,8.828,0,0,0,14.17,18.57,10.148,10.148,0,0,0,20.835,21h.178a1.97,1.97,0,0,0,1.937-1.7,8.16,8.16,0,0,0,.062-1,8.609,8.609,0,0,0-3.056-6.5A10.626,10.626,0,0,0,12.955,9.244Z" style="fill:#b4a0ff"/><path d="M14.719,11.8h-.1a1.107,1.107,0,0,0-1.073.982,4.842,4.842,0,0,0-.034.577,5.4,5.4,0,0,0,5.57,5.217h.1a1.11,1.11,0,0,0,1.073-.982,5.283,5.283,0,0,0,.034-.576A5.4,5.4,0,0,0,14.719,11.8Z" style="fill:#fff"/></svg>
```

glitter_preview

**Comment by robertohuertasm** [comment]
Cool, my version was around 7kb. Let's go with this one.

**Pull request merged**
