### PR TITLE
feat(icon): add the supabase folder icon

### LINKED ISSUE #3307: [Icon Request]: Supabase
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Icon Type

- [ ] File Icon
- [X] Folder Icon

### Icon Type

- [ ] Extension
- [X] Filename
- [ ] Language ID

### Original Icon

supabase-logo-icon

### Icon Information

Official Supabase logo extracted from [Supabase Brand Assets](https://supabase.com/brand-assets).

When working with Supabase and  [Supabase cli](https://github.com/supabase/cli), you will need to create a folder named `supabase` in your directory root.

There's no icon for that folder right now. I suggest using the official Supabase icon.

### More Information:

_No response_

### PR DESCRIPTION
**Pull request by remcohaszing**
Closes #3307

_**Fixes #3307**_

**Changes proposed:**

- [x] Add
- [ ] Delete
- [ ] Fix
- [ ] Prepare

### CODE REVIEW

**Comment by KingDarBoja** [comment]
Will try to get the time to review this PR. Overall the folder icons are looking good but the supabase folder might need an extra contrast for the default mode 🤔

**Comment by remcohaszing** [comment]
I tried to follow https://github.com/vscode-icons/vscode-icons/wiki/Contributing, but using InkScape since I don’t have Illustrator.

**Comment by KingDarBoja** [comment]
> I tried to follow https://github.com/vscode-icons/vscode-icons/wiki/Contributing, but using InkScape since I don’t have Illustrator.

No worries, the colours do match the wiki steps, I have just added an extra outline to the supabase logo to make it distinguishable when rendered and minified per illustrator SVG settings.

**Review by KingDarBoja — APPROVED** [review]
LGTM 🚀

**Comment by remcohaszing** [comment]
> I have just added an extra outline to the supabase logo to make it distinguishable when rendered

I see. I like it :)

**Review by robertohuertasm — APPROVED** [review]
LGTM 🚀 Great icons! ❤️

**Pull request merged**
