### PR TITLE
Support for windows and x64 arch

### PR DESCRIPTION
**Pull request by robertohuertasm**
The `wallaby.js` file specifies the path to the node version assuming the user is using `nvm` and a non Windows machine. This PR avoids fixing the node version and relies on user's executing node version, provided that users and mantainers should know that our supported node version is 7.9.0.

### CODE REVIEW

**Comment by JimiC** [comment]
I have a solution. 
```
env: {
    type: "node",
    runner: process.platform === 'win32'
      ? `${process.env.APPDATA}\\nvm\\v7.9.0\\node`
      : `${require('os').homedir()}/.nvm/versions/node/v7.9.0/bin/node`
  },
```

**Comment by robertohuertasm** [comment]
@JimiC, I've used your code and added support for x64 architectures.

**Comment by JimiC** [comment]
We also need to change the title of the PR.

**Comment by robertohuertasm** [comment]
Done!

**Comment by JimiC** [comment]
@robertohuertasm Unfortunately, the `process.arch` switch isn't working when you have already used that `node` version (`nvm use <version>`). `node64.exe` gets renamed to `node.exe`.
Consider using the above-proposed code snippet.

**Pull request merged**
