### PR TITLE
Replace Matlab PNG icon with SVG

### LINKED ISSUE #1875: Suggestion: Change the Matlab icon from png to svg
- [x] I'm sure this issue is not a _duplicate_.

The current Matlab icon has **.png** extension and low quality if you start zooming in. I have done already (after 2 hours of work) an svg version. The file itself isn't perfect as I had to remove some points to reduce the size from 200 KB to 68 KB but the result can be seen below.

wut

Thoughts?

### PR DESCRIPTION
**Pull request by admvx**
_**Fixes #1875**_

**Changes proposed:**
- [x] Fix

Hey! I saw some of the discussion about this in the [corresponding issue](https://github.com/vscode-icons/vscode-icons/issues/1875), and I wanted to take a shot at recreating the logo while minimizing the SVG complexity as much as possible. This version is 4.55KB, so it doesn't meet the size target entirely, nor does it visually match the original when enlarged.

Hopefully the likeness is close enough, and size reduction significant enough, to warrant the replacement - but I'm happy to make modifications if not. Thanks for checking it out!

Screen Shot 2019-10-08 at 00 53 47

### CODE REVIEW

**Comment by JimiC** [comment]
Thanks for your effort but unfortunately the file size is unacceptable. Anything larger than 2K will cause serious rendering lags in `vscode`.

After all this time I'm leaning towards the solution of a minimalist version without gradients. That will reduce the file size a significant amount.

**Comment by admvx** [comment]
@JimiC @KingDarBoja Thank you for your responses! I hoped it might be good enough, but I completely understand the need to prioritize performance. Good luck @KingDarBoja! In case you can't shave enough off with your plans, I also wouldn't mind taking another pass at optimizing the current version.
Equally, I think a "flat" design would be a decent solution too. I won't do anything for the time being, but please tag me in if I can help :)

**Comment by KingDarBoja** [comment]
@JimiC @admvx By using the simplify tool, it didn't improve the file size and changing the settings would result in deformed logo.

So I went with the flatten strategy and removed most of the details but keeping the important ones.
```xml
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 32 32"><defs><linearGradient id="a" x1="16.803" y1="16.631" x2="15.013" y2="22.411" gradientTransform="matrix(1, 0, 0, -1, 0, 32)" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#512"/><stop offset="0.1" stop-color="#522"/><stop offset="0.23" stop-color="#523"/><stop offset="0.36" stop-color="#534"/><stop offset="0.51" stop-color="#645"/><stop offset="0.66" stop-color="#568"/><stop offset="0.81" stop-color="#38c"/><stop offset="0.84" stop-color="#29d"/></linearGradient><clipPath id="b"><path d="M20.8,3.3c-2.18,0-3.67,11.48-11.72,17.89,2.26-.37,4.22,5.24,5.12,7.51,4-.68,7.2-8.33,10.43-8.21,1.85.07,3.47,1.86,5.37,3.63C25.66,15,23.63,3.3,20.8,3.3Z" style="fill:none"/></clipPath><linearGradient id="d" x1="14.6" y1="17.631" x2="21.6" y2="15.301" gradientTransform="matrix(1, 0, 0, -1, 0, 32)" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#612"/><stop offset="0.3" stop-color="#822"/><stop offset="0.44" stop-color="#822" stop-opacity="0.8"/><stop offset="0.63" stop-color="#922" stop-opacity="0.52"/><stop offset="0.86" stop-color="#b33" stop-opacity="0.21"/><stop offset="1" stop-color="#c33" stop-opacity="0"/></linearGradient><linearGradient id="f" x1="27.169" y1="17.883" x2="22.119" y2="16.643" gradientTransform="matrix(1, 0, 0, -1, 0, 32)" gradientUnits="userSpaceOnUse"><stop offset="0.07" stop-color="#c33"/><stop offset="0.28" stop-color="#d43"/><stop offset="0.41" stop-color="#d43"/><stop offset="1" stop-color="#c33" stop-opacity="0"/></linearGradient><radialGradient id="h" cx="13.42" cy="1.94" r="10.64" gradientTransform="matrix(1, 0, 0, -1, 0, 32)" gradientUnits="userSpaceOnUse"><stop offset="0.17" stop-color="#ff4"/><stop offset="0.23" stop-color="#fe4"/><stop offset="0.36" stop-color="#fb4" stop-opacity="0.88"/><stop offset="0.55" stop-color="#e74" stop-opacity="0.76"/><stop offset="0.58" stop-color="#e74" stop-opacity="0.74"/><stop offset="0.8" stop-color="#f84" stop-opacity="0"/></radialGradient></defs><title>file_type_matlab_2</title><path d="M2,17.55l7.97-3.22a20.7,20.7,0,0,1,2.72-2.95c.66-.35,1.9-.16,4.17-2.98,2.2-2.75,2.9-5.1,3.93-5.1,1.63,0,2.83,3.52,4.65,8.85A115.629,115.629,0,0,0,30,24.12c-1.9-1.77-3.52-3.68-5.37-3.63-1.72.04-3.63,2.08-5.72,4.7-1.66,2.1-3.86,3.54-4.72,3.51,0,0-2.22-6.28-4.08-7.3a2.641,2.641,0,0,0-2.39.2L2,17.54Z" style="fill:#49d"/><path d="M19.8,4.02c-.67.9-1.48,2.55-2.94,4.38-2.27,2.82-3.5,2.63-4.17,2.98a19.674,19.674,0,0,0-2.72,2.95l3.3,2.41c2.8-3.82,4.3-7.96,5.47-10.64A13.579,13.579,0,0,1,19.8,4.02Z" style="fill:url(#a)"/><g style="clip-path:url(#b)"><path d="M8,3H31V29H8Z" style="fill:#f84"/></g><g style="clip-path:url(#b)"><path d="M8,3H31V29H8Z" style="fill:url(#d)"/></g><g style="clip-path:url(#b)"><path d="M8,3H31V29H8Z" style="fill:url(#f)"/></g><g style="clip-path:url(#b)"><path d="M8,3H31V29H8Z" style="fill:url(#h)"/></g></svg>
```

**File Size: 2.86 KB**

Full size preview:
image

**Comment by JimiC** [comment]
I like the 2.44 kB one. It's very close to the original. But size wise the 1.74 kB is preferable.

**Comment by KingDarBoja** [comment]
> I like the 2.44 kB one. It's very close to the original. But size wise the 1.74 kB is preferable.

Shall we vote for which version to pick up? I don't mind going with the lowest size version as it keep the details at small views.

**Comment by admvx** [comment]
Just wanted to say great work for paring it down & good luck settling on the final version! Looks like you can commit to my branch if you decide to, but please let me know if I can help :D

**Comment by robertohuertasm** [comment]
Do we have a winner? 1.74 or 2.44. I vote for the first one.

**Comment by robertohuertasm** [comment]
@KingDarBoja is this ok to be merged?

**Comment by KingDarBoja** [comment]
> @KingDarBoja is this ok to be merged?

Not yet, need to push the new icon to the branch.

**Pull request merged**
