### PR TITLE
Adding PDDL related file icons for Artificial Intelligence Planning.

### PR DESCRIPTION
**Pull request by jan-dolejsi**
_**Fixes #IssueNumber**_

**Changes proposed:**

- [x] Add
- [ ] Delete
- [ ] Fix
- [ ] Prepare

Adding support for Planning Domain Definition Language files:

`.pddl` -> planning models (domain model and planning problem specification)
`.plan` -> output of the planner - essentially a Gantt chart
`.happenings` -> output of the planner, where temporal actions are decomposed to start and end - so called _snap_ actions

For more info, see PDDL in wikipedia:
https://en.wikipedia.org/wiki/Planning_Domain_Definition_Language

### CODE REVIEW

**Comment by jan-dolejsi** [comment]
Thanks for the feedback. I think I understand how it works now. Please re-review.

**Comment by JimiC** [comment]
Found it! It's your extension! https://marketplace.visualstudio.com/items?itemName=jan-dolejsi.pddl

**Comment by jan-dolejsi** [comment]
Yes :)

**Comment by jan-dolejsi** [comment]
Is there anything else I should do, or can help with?

**Comment by JimiC** [comment]
@jan-dolejsi No. It will take some time to review all PRs cause I and @robertohuertasm are busy with real life.

**Pull request merged**
