### PR TITLE
Use webpack config typescript file

### PR DESCRIPTION
**Pull request by KingDarBoja**
_**Fixes None**_

**Changes proposed:**

- [x] Add
- [ ] Delete
- [ ] Fix
- [ ] Prepare

🚀

### CODE REVIEW

**Comment by JimiC** [comment]
@KingDarBoja I'm afraid that you have broken the `dist` script now.

**Comment by KingDarBoja** [comment]
> @KingDarBoja I'm afraid that you have broken the `dist` script now.

I didn't saw any problem after running the `test` script. Gonna test the `dist` one to find out if there are building errors.

**Comment by JimiC** [comment]
We never covered `npm` scripts via tests.

**Comment by KingDarBoja** [comment]
> We never covered `npm` scripts via tests.

I know, just saying what I did to test out if the extension was still working. Not sure what did you mean with the `dist` script but looks like it is changing the `package.json` properties `main` and `iconThemes.path`.

**Comment by JimiC** [comment]
I'll give you more details tomorrow when I'll be in the office.

**Comment by JimiC** [comment]
I made some improvements to your changes.

- Removed `allowSyntheticDefaultImports` as it requires `esModuleInterop` and we decided with @robertohuertasm to not use it.
- Removed old `prettier` `tslint` setting and replaced it with the new one.
- Transposed `webpack` config to a single function.

**Comment by KingDarBoja** [comment]
@JimiC It is okay if these lines in `package.json` changes after running `npm run dist`?

output dist

**Comment by JimiC** [comment]
Yes that's intended.

**Comment by JimiC** [comment]
If you are OK with my changes the PR is good for merging.

**Comment by KingDarBoja** [comment]
> If you are OK with my changes the PR is good for merging.

Yeah, please approve this as I can't do with my own PR 😆

**Pull request merged**
