### PR TITLE
feat(icon): support `playwright.config.mts`

### LINKED ISSUE #3589: [Icon Request]: playwright add mts suffix support
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Icon Type

- [X] File Icon
- [ ] Folder Icon

### Icon Type

- [ ] Extension
- [X] Filename
- [ ] Language ID

### Original Icon

playwright

### Icon Information

playwright

### More Information:

just add some extensions

https://github.com/microsoft/playwright/blob/a54ed48b42cdc898e6444f643ac8fb97cdb498f2/packages/playwright/src/common/configLoader.ts#L315-L321

### PR DESCRIPTION
**Pull request by tmkx**
_**Fixes #3589**_

**Changes proposed:**

- [x] Add
- [ ] Delete
- [ ] Fix
- [ ] Prepare

### CODE REVIEW

**Comment by tmkx** [comment]
https://github.com/microsoft/playwright/blob/a54ed48b42cdc898e6444f643ac8fb97cdb498f2/packages/playwright/src/common/configLoader.ts#L315-L321

**Comment by JimiC** [comment]
Please associate this PR with an issue for better tracking.

**Comment by tmkx** [comment]
issue added :）

**Comment by JimiC** [comment]
> issue added :）

Thank you

**Review by robertohuertasm — APPROVED** [review]
LGTM 🚀 Thanks for your contribution ❤️

**Pull request merged**
