### PR TITLE
Add support for Nx Workspace

### LINKED ISSUE #2536: [Icon Request] Add Support for Nx Workspace
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `nx-workspace`
  - Sample original Icon: logo-white logo-dark
  - Filenames: `nx.json`, `decorate-angular-cli.js`

- Language Extensions: https://github.com/nrwl/nx-console
- More info: The Nx workspaces let you manage multiple libraries/apps/schematics for different frameworks like Angular, Nest, React. All of this is being done by the `nx.json` file as explained at [Angular Nx Workspace](https://nx.dev/angular/workspace/workspace-overview) and [React Nx Workspace](https://nx.dev/react/workspace/workspace-overview).

Below is an example of how Nx Workspaces look like by selecting the Angular preset.

angular-nx-demo-tree

Would be great to provide the filename icon for these two files.

### PR DESCRIPTION
**Pull request by KingDarBoja**
_**Fixes #2536**_

**Changes proposed:**

- [x] Add
- [ ] Delete
- [ ] Fix
- [ ] Prepare

### CODE REVIEW

**Comment by JimiC** [comment]
@KingDarBoja I Personally I don't like the Gary color for dark themes. Any change to pick a revert blue color for that or even a lighter blue?

**Comment by KingDarBoja** [comment]
> @KingDarBoja I personally don't like the grey color for dark themes. Any chance to pick a revert blue color for that or even a lighter blue?

Was thinking the same, let me check if Nx has another blue colour for light themes, I remember they had one but couldn't find it.

**Comment by JimiC** [comment]
The original icon is fine for light themes. It's the dark themes one that I don't like.

**Comment by KingDarBoja** [comment]
> The original icon is fine for light themes. It's the dark themes one that I don't like.

Yes, I know, what I meant to say was about Nx having another variant for light themes which uses a lighter blue which should work for the dark one.

**Comment by JimiC** [comment]
Nope. I need to look into it personally after Wednesday.

**Review by robertohuertasm — APPROVED** [review]

**Comment by robertohuertasm** [comment]
Regarding this PR, I understand there were some points to solve before merging. Is that right? It looks good to me but just in case.

**Comment by JimiC** [comment]
Didn't got the time to look at it.

**Comment by robertohuertasm** [comment]
Superseded by https://github.com/vscode-icons/vscode-icons/pull/3045

**Pull request closed without merging**
