### PR TITLE
Add i18n support for command titles and config descriptions.

### LINKED ISSUE #780: [Task] Update translation generation to meet VSCode possibillities
**Checklist:**

- [X] I'm sure this issue is not a *duplicate*?

See https://github.com/Microsoft/vscode/blob/master/extensions/php/package.nls.json and https://github.com/Microsoft/vscode/issues/21458#issuecomment-282981962

### PR DESCRIPTION
**Pull request by JimiC**
***Fixes #780***

**Changes proposed:**
* [x] Add
* [x] Prepare

**Things I've done:**
* [x] My pull request fixes an issue, I referenced the issue.

`package.nls.json` is the default English messages.

The filename pattern for any other supported language messages is `package.nls.[language].json`.
Use the `template` file provided to start with translations.

More info @ https://github.com/Microsoft/vscode-nls-dev

@jens1o Would like your input on the German translation.
@robertohuertasm Could you please do the Spanish translation?
I'll ask my sis to do the French translation.

### CODE REVIEW

**Comment by jens1o** [comment]
I'll do it in the evening, but I'm busy atm.

**Comment by JimiC** [comment]
No problem. The translations can be added on another PR.

**Comment by jens1o** [comment]
Question: The english file should be called `package.nls.en-US.json` and `package.nls.en-GB.json`, shouldn't it? Since there are two language codes for English?

**Comment by JimiC** [comment]
[Those](https://code.visualstudio.com/docs/customization/locales) are the supported languages.

**Comment by jens1o** [comment]
Ah, so British English isn't supported. Anyway...

**Pull request merged**
