### PR TITLE
Update test workflow

### PR DESCRIPTION
**Pull request by JimiC**
- Upgrading node version
- Allow fail on non-essential node versions
- Cancel workflow when another commit is made on the same branch
- Run jobs on batch of 3
- Improving code coverage workflow
- Upload code coverage directly if development is being done withing the repo (only the dev team is allowed to do that), otherwise use artifacts and use another workflow to ensure no secrets are leaked

**Note: This is part 1 of 2 for the dependencies update. This PR must be merged first before the Dependencies Update PR can be submitted.**

### CODE REVIEW

**Comment by JimiC** [comment]
This is part 1 of 2 fro the dependencies update.

**Comment by JimiC** [comment]
@robertohuertasm No idea why the PR has no access to secrets although the checkbox for "Allow edits and access to secrets by maintainers" is checked.

**Comment by JimiC** [comment]
@robertohuertasm If you find some time pls do a review so we can merge this PR and iron out any issue that may lurk.

**Review by robertohuertasm — DISMISSED** [review]

**Comment by JimiC** [comment]
Oh crap. Now I have to work on the second part of the update. @robertohuertasm Pls hold any release until I submit the rest.

**Comment by robertohuertasm** [comment]
What do you need to do? Maybe I can help you with that.

**Comment by JimiC** [comment]
I have done it when I worked on the workflow update. I just have to bring it up to speed. Some rebase and potential fixes for issues that may have arise since. Hopefully I can resolve it in a couple of hours.

**Comment by robertohuertasm** [comment]
Ok, I'll try to fix some pending PRs in the meantime.

**Pull request merged**
