### PR TITLE
ci(coverage): add test coverage

### PR DESCRIPTION
**Pull request by robertohuertasm**
Based on previous work made by @Snazzah

### CODE REVIEW

**Comment by robertohuertasm** [comment]
@Snazzah, not sure why this didn't work in #2994... I've just reused your code and now it seems to do the trick.

We were getting this warning, though:

image

Not sure if that was ok so I added the `coverageLocations` and now we're getting this:

image

I've quickly checked code climate but still cannot see any information from today. Will check in a couple of hours and let you know if something changed.

**Comment by robertohuertasm** [comment]
Now I've seen that we've received a bot message stating that the coverage is 100% so I guess it works.

**Comment by robertohuertasm** [comment]
Merging this for the moment. Will keep an eye on it. Thanks again @Snazzah for your help on this matter!

**Comment by Snazzah** [comment]
@robertohuertasm You might need to set `coverageCommand` (which is what that warning is about) to `npm test`

**Comment by robertohuertasm** [comment]
I read the actions documentation and it’s not needed. It seems to be optional.

**Pull request merged**
