### PR TITLE
fix(progress): prolog extension collided with progress openedge

### PR DESCRIPTION
**Pull request by clement-brodu**
**Changes proposed:**
add missing extensions for progress openedge

- [x] Fix

### CODE REVIEW

**Comment by robertohuertasm** [comment]
@clement-brodu it seems that that extensions are already supported via language id. The icons should be there if you use [this other extension](https://marketplace.visualstudio.com/items?itemName=chriscamicas.openedge-abl). See how it is defined [here](https://github.com/chriscamicas/vscode-abl/blob/master/package.json#L51-L54)

Is it not working for you?

**Comment by robertohuertasm** [comment]
I'm closing this unless @clement-brodu confirms this is not working with language id.

**Comment by clement-brodu** [comment]
Hello, 

Even with the extension detecting the correct file type, the icon is not the correct one for `*.p` files.

image

**Comment by robertohuertasm** [comment]
That’s strange. Looks like a bug. I’ll try to reproduce it.

**Comment by robertohuertasm** [comment]
I see what's going on. Prolog has `P` as an extension and both are competing against that. Let me check if we can get rid of that prolog extension.

**Comment by robertohuertasm** [comment]
Let's get rid of the `P` extension in prolog and leave it to language extensions implementors to decide.

**Review by robertohuertasm — APPROVED** [review]

**Pull request merged**
