### PR TITLE
Change Angular preset to false.

### PR DESCRIPTION
**Pull request by JimiC**
As discussed.

### CODE REVIEW

**Comment by jens1o** [comment]
Why is bitHound not working?

**Comment by JimiC** [comment]
Because when I create the PR the analysis hasn't finished on my fork and it tries to create an analysis from the commit. If I `force` the PR again it will be fixed.

**Comment by JimiC** [comment]
See?

**Comment by robertohuertasm** [comment]
@JimiC we should change the readme accordingly 

> vsicons.presets.angular (true by default)

**Comment by jens1o** [comment]
Ah, I get it. Thanks.

**Pull request merged**
