### PR TITLE
Add support for goctl

### PR DESCRIPTION
**Pull request by codingfanlt**
**Changes proposed:**

- [x] Add
- [ ] Delete
- [ ] Fix
- [ ] Prepare

Add support for goctl,  goctl is go-zero's API definition and generation tool, which can generate Go, iOS, Android, Kotlin, Dart, TypeScript, JavaScript code with one click based on the defined api file. For more information, please refer [here](https://github.com/zeromicro/go-zero).

### CODE REVIEW

**Review by robertohuertasm — CHANGES_REQUESTED** [review]
Unfortunately, we cannot accept this icon. We don't support embedded images in svg. Maybe we could work using the go icon as the base and add something specific for this kind of extension?

**Comment by robertohuertasm** [comment]
image
would that work?

**Comment by robertohuertasm** [comment]
@codingfanlt as I'm preparing a new release, I'll go with that version, so you can have at least a temporary icon. We can work on this in the future.

**Comment by codingfanlt** [comment]
Thank you very much for the temporary icon. I will provide the composite request icon in the future, thanks again.

**Pull request merged**
