### PR TITLE
Add support for modules folder

### LINKED ISSUE #650: [Request] Specific folder icons
### We are keeping here a list of requested folder icons.
We are going to update this list as we go along adding icons.

Before requesting a folder icon make sure to check out the already [supported folder list](https://github.com/vscode-icons/vscode-icons/wiki/ListOfFolders).

**Any new requests SHOULD be submitted via comments on this issue and we'll update the list accordingly.**

- [ ] arangodb
- [ ] cmake
- [ ] console, cli, commandline
- [ ] controllers
- [ ] data
- [ ] enum
- [ ] environments
- [ ] gulp
- [ ] graphql
- [ ] grunt
- [ ] minikube
- [ ] `__mocks__`, mocks
- [ ] polyfills
- [ ] resources
- [ ] serializers
- [ ] services
- [ ] shared, common, core

### Debatable
`Debatable` are folder names that are debatable on whether we should provide a specific icon.

- [ ] vendor

### PR DESCRIPTION
**Pull request by KingDarBoja**
_**References #650**_

**Changes proposed:**

- [x] Add
- [ ] Delete
- [ ] Fix
- [ ] Prepare

This is a proposal for `modules` folder using the icon provided at #1022. Thoughts?

### CODE REVIEW

**Comment by JimiC** [comment]
I'm not 100% OK with the icon or the colors (something is bothering on it but I can't pinpoint it yet) but if the team agrees I'm OK with it.

**Comment by KingDarBoja** [comment]
> I'm not 100% OK with the icon or the colors (something is bothering on it but I can't pinpoint it yet) but if the team agrees I'm OK with it.

Feel free to change the colors. Regarding the icon, I think it was a proper choice because couldn't think anything for modules besides multiple boxes linked together... unless it is better for shared folder icon?

**Comment by robertohuertasm** [comment]
Personally, I don't dislike the icon. What I think is that the color combination is not the normal kind of combinations that we use. Normally we grab the color of the icon as a base for the color of the folder, but in this case I guess you chose a complementary. 

I would make it more monochromatic and choose whether purple or yellow as the base color for everything.

**Comment by KingDarBoja** [comment]
@robertohuertasm I am working on it right now using the steps provided by JimiC on the other PR.

**Comment by JimiC** [comment]
Looking at this in detail I believe the best course it to bind `modules` with the existing `components` folder icon. After all `modules` and `components` are similar in concept.

**Comment by robertohuertasm** [comment]
Certainly, the components icon could work also for modules. But since we already have this cool icon I don't see a reason not to use it. Components folder has a specific meaning in the UI world and modules seems to me more a backend construct, so I wouldn't mind having two separated icons.

**Comment by JimiC** [comment]
OK. I'm going to fix the contrast a bit. Don't merge yet.

**Comment by JimiC** [comment]
I decided to leave the contrast as is. Will iterate on them if any issue arises.

**Pull request merged**
