### PR TITLE
Add support for Ninja

### LINKED ISSUE #1579: [Icon Request] Support for Ninja
- [X] I'm sure this issue is not a _duplicate_.
- [X] I'm submitting an icon request:
  - Type: `file`
  - Icon Name: `ninja`
  - Sample original Icon: N/A
  - Extensions: ``
  - Filenames: `build.ninja`
  - Language ids: ``

- Language Extensions:
- More info:
[Ninja](https://en.wikipedia.org/wiki/Ninja_(build_system)) is a build system similar to `make` used as the prefered backend for Meson

### PR DESCRIPTION
**Pull request by KingDarBoja**
_**Fixes #1579**_

**Changes proposed:**

- [x] Add
- [ ] Delete
- [ ] Fix
- [ ] Prepare

There wasn't a official icon so I made a custom ninja face. However, the ninja color I choose is not going to be noticed on dark themes. Any suggestion or changes on the icon is required in order to merge this PR.

### CODE REVIEW

**Comment by Alhadis** [comment]
Should have used this sick logo I designed *just* for Ninja/GN (admittedly to kill time while building V8):

**Comment by KingDarBoja** [comment]
That's like a communist logo with some ninja touches hahaha but love the way it looks.

**Comment by Alhadis** [comment]
On the left is a Sai, a traditional Japanese sparring weapon, typically wielded in pairs. The large prongs are designed to catch an enemy's weapon and fling it from their hands.

On the right is a hammer, frequently used for denoting toolsets and building in technical interfaces.

Taken together, the logo reads **"Ninja Build"**, which is [literally what it is](https://ninja-build.org).

**Comment by Alhadis** [comment]
There's also a shuriken icon for representing the actual `.ninja` files themselves, complementing the GN icon:



Building V8 causes tonnes of these tiny files to be flung into your project's build directory, and very rapidly, so the choice of weapon is even appropriate. 😉

**Comment by KingDarBoja** [comment]
@Alhadis I was making fun of the way the icon look for non programmers, but I do feel like the concept fits pretty well. If the @vscode-icons/development Team is okay with that, we could use that one instead of mine.

Also, I tried the shuriken icon but came to my mind some history channel (or was Discovery one) documental about shurikens being used by samurais instead of ninjas due to the noise generated by carrying them. Of course, you don't want to make noise while on assassination mission 😆

**Comment by Alhadis** [comment]
> Of course, you don't want to make noise while on assassination mission 😆

Hey, don't look at me, I bludgeon my victims!

**Comment by dialex** [comment]
I would vote for @Alhadis version: 1) it fits the theme on ninja, 2) perfectly matches the shuriken icon, 3) it's easier to read on small sizes, 4) it's B&W so it easily matches any colour scheme.

**Pull request merged**
