### PR TITLE
refactor(azure): use new logo

### LINKED ISSUE #2991: [ Icon Request ] Add support for the newer, 2021 Azure logo
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `extension`
  - Icon Name: `Azure`
  - Sample original Icon: azure 2021 logo
  - Extensions: (folder) `azure`

- More info:

In 2021, Microsoft shifted the logo of their `Azure` cloud service from this: azure previous logo to a more "A" shaped logo, more fitting with their fluent design system.

### PR DESCRIPTION
**Pull request by sasial-dev**
_**Fixes #2991**_

**Changes proposed:**

Use the new azure logo

### CODE REVIEW

**Comment by hiteacheryouare** [comment]
Does this include the [Azure Folder?](https://github.com/vscode-icons/vscode-icons/wiki/ListOfFolders#azure)

**Comment by sasial-dev** [comment]
Good call!
I'll do them tonight

**Review by robertohuertasm — COMMENTED** [review]
The folder icons seem to have been moved. I'll fix this.

**Review by robertohuertasm — CHANGES_REQUESTED** [review]
These svg use png data. We should try to stick to plain svgs.

**Comment by robertohuertasm** [comment]
I've found a cool vector for this one. I'll refactor the icons.

**Review by robertohuertasm — APPROVED** [review]

**Pull request merged**
