### PR TITLE
feat: add commitizen icon

### LINKED ISSUE #2740: [Icon Request] Support for commitizen config files
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `czrc`
  - Sample original Icon: logo
  - Extensions: `.czrc`
  - Filenames: `.czrc`
  - Language ids: `.czrc`

- Language Extensions:
- More info:
    https://commitizen.github.io/cz-cli/
    https://github.com/commitizen/cz-cli/issues/800

### PR DESCRIPTION
**Pull request by fsmaia**
_**Fixes #2740**_

**Changes proposed:**

- [x] Add
- [ ] Delete
- [ ] Fix
- [ ] Prepare

### CODE REVIEW

**Review by robertohuertasm — COMMENTED** [review]
Thanks for this. The icon should be simplified though.  I will take care of it.

**Comment by robertohuertasm** [comment]
I've remove all those fancy bubbles... They add lot of complexity and weight to the final svg and they're barely noticeable in the IDE. Hope its ok for you!

**Review by robertohuertasm — APPROVED** [review]
LGTM 🚀 Thanks for your contribution ❤️

**Comment by fsmaia** [comment]
Sure, it will look better too! Huge thanks on your effort!

**Comment by robertohuertasm** [comment]
I'll prepare a new release probably today so this will be live soon! 🎉 Thanks again for the icon!

**Pull request merged**
