### PR TITLE
typo found

### PR DESCRIPTION
**Pull request by robertohuertasm**
Small typo in readme file

### CODE REVIEW

**Comment by robertohuertasm** [comment]
@JimiC, why is this yarn.lock file added to this branch about typos?

**Comment by JimiC** [comment]
Because I didn't wanted to open another PR just for this. And because this is a PR that fixes something I added it to it.

**Comment by JimiC** [comment]
@robertohuertasm If my action annoyed you, please act accordingly.

**Comment by robertohuertasm** [comment]
@JimiC, no annoyment! 😉 Just wanted to understand your reasoning. I seemed strange to me that you did that given that you like to do things in a more structured way. Certainly, I would have preferred to have a different PR but it's not an issue at all. Don't worry. All fine! 😄

**Comment by JimiC** [comment]
I'm not well today so I'm in "minimal" mode.

**Comment by robertohuertasm** [comment]
@JimiC! as I said, nothing to worry about. I hope you get better soon.

**Pull request merged**
