### PR TITLE
Add support for certificate folder

### PR DESCRIPTION
**Pull request by JimiC**
_**References #650**_

**Changes proposed:**

- [x] Add

### CODE REVIEW

**Comment by robertohuertasm** [comment]
What about changing the background color? Red seems strange given that we're talking about certificates and normally green is the color of choice for this.

**Comment by JimiC** [comment]
It's difficult now for me to do any changes. Let it out of this release and we can iterate on it later.

**Comment by robertohuertasm** [comment]
I will make a test

**Comment by JimiC** [comment]
Use the `src` colors. Just copy paste the values in `fill`.

**Comment by JimiC** [comment]
The `typings` folder colors are also a good choice.

**Comment by robertohuertasm** [comment]
image

After testing with green colors, they seem too similar to `src` folder, and considering that nowadays lots of repos have this folder I thought it would be better to go with a more common color for locks.

**Comment by JimiC** [comment]
I'm OK with it

**Pull request merged**
