### PR TITLE
Add support for Nix

### PR DESCRIPTION
**Pull request by DavSanchez**
_**Fixes https://github.com/vscode-icons/vscode-icons/issues/2542**_

**Changes proposed:**

- [x] Add
- [ ] Delete
- [ ] Fix
- [ ] Prepare

### CODE REVIEW

**Comment by JimiC** [comment]
Where's the related issue???

**Comment by DavSanchez** [comment]
Sorry there’s not. I thought about adding the Nix icon directly without filing an issue first. Should I open an issue and link it here?

**Comment by JimiC** [comment]
It's mandatory.

**Comment by DavSanchez** [comment]
Sorry about that. Just added an issue according to the wiki and linked it in the description, am I missing anything?

**Comment by JimiC** [comment]
Much better now. Thanks.

**Comment by JimiC** [comment]
Can you point out with `extension` uses `nixos` as `language id`?

**Comment by DavSanchez** [comment]
> Can you point out which `extension` uses `nixos` as `language id`?

Ah, that slipped by, sorry. It's only `nix` (NixOS is the operating system related to `nix` files but the language is just called Nix.)

**Comment by JimiC** [comment]
OK. The last thing I need is for @KingDarBoja to process the icon according to our guidelines.

**Comment by KingDarBoja** [comment]
I made the changes but can't push to your repo, did you allowed edit for maintainers?

**Comment by DavSanchez** [comment]
> I made the changes but can't push to your repo, did you allowed edit for maintainers?

Hi @KingDarBoja , if your comment is to me, sorry I have not made any modification to the repo, it's a normal fork. Where can I allow this?

**Comment by KingDarBoja** [comment]
> > I made the changes but can't push to your repo, did you allowed edit for maintainers?
> 
> Hi @KingDarBoja , if your comment is to me, sorry I have not made any modification to the repo, it's a normal fork. Where can I allow this?

At the right side, scroll down and there should be a checkbox with the label "Allow Edit for maintainers".

**Comment by KingDarBoja** [comment]
I got lazy so used GitHub to edit the icon, now it is ready to merge! 🚀

**Comment by DavSanchez** [comment]
Thanks @KingDarBoja !

Anyway, I also checked the PR and the edit by maintainers was already enabled, maybe it was another thing.

**Pull request merged**
