### PR TITLE
Add Nearley Grammar icon

### PR DESCRIPTION
**Pull request by Floffah**
_**Fixes none**_

**Changes proposed:**

- [x] Add

Adds the .ne (Nearley grammar file) icon. Couldn't find an icon so I made my own one.

### CODE REVIEW

**Comment by JimiC** [comment]
I strongly suggest to open an issue (please follow the [instructions](https://github.com/vscode-icons/vscode-icons/wiki/Issue)) for this and let us decide on the icon.

**Comment by KingDarBoja** [comment]
Just to reference the issue: #2079 

Also the vscode-icons team is strongly against using letter for icons unless the official documentation made use of it.

So after a quick search: [Nearly Proposed Logo](https://github.com/kach/nearley/pull/215).

Cheers!

**Comment by Floffah** [comment]
Correction:
Name is Nearley not nearly.
extension is .ne not .nearly.

**Comment by JimiC** [comment]
Don't worry only the icon name is wrong.

**Pull request merged**
