### PR TITLE
Add support for Portuguese (Brazil) and Turkish

### PR DESCRIPTION
**Pull request by JimiC**
**Changes proposed:**

- [x] Add

Honestly, I was surprised finding out that although we had the translations for so long we didn't use them.

For `v9` I'm working on a new language resourse manager that will automate the inclusion of any new language.

### CODE REVIEW

**Comment by JimiC** [comment]
I will have to do some additional changes to this.

**Comment by JimiC** [comment]
@robertohuertasm I didn't want you to merge it yet

**Comment by JimiC** [comment]
Never mind more work for me now.

**Comment by robertohuertasm** [comment]
Sorry, I didnt see the message. We could use WIP in the PR title to be explicit about this.

**Comment by JimiC** [comment]
I saw the addition a bit late and thought by leaving a comment I could prevent you from merging. Don't feel bad about it,

**Pull request merged**
