### PR TITLE
Add support for TTCN-3

### LINKED ISSUE #1732: [Icon Request] Support for 'ttcn-3'
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `extension`
  - Icon Name: `ttcn3`
  - Sample original Icon: logo
  - Extensions: `ttcn`, `ttcn3`, `ttcnpp`
  - Language ids: `ttcn`

- Language Extensions: [TTCN-3 Language Support for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=ealap.language-ttcn)
- More info: [TTCN-3](http://www.ttcn-3.org/index.php/about/introduction)

### PR DESCRIPTION
**Pull request by ealap**
_**Fixes #1732**_

**Changes proposed:**

- [x] Add
- [ ] Delete
- [ ] Fix
- [ ] Prepare

### CODE REVIEW

**Comment by KingDarBoja** [comment]
@ealap I did a fast check on the svg file and to be honest, it is almost okay but need some fixes according to guidelines. The height is like 29px and hence, it doesn't satisfy the 2px margin for every side.

I did a little fix on the svg but too lazy to clone the branch, so I will let the code here:
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><title>file_type_ttcn</title><path d="M12.086,2c-.718,0-.816.015-.377.062a21.978,21.978,0,0,1,2.389.4,16.45,16.45,0,0,1,7.714,3.824,12.314,12.314,0,0,1,3.786,7.4,15.018,15.018,0,0,1,.173,2.622,10.656,10.656,0,0,1-.039,1.3,14,14,0,0,1-.593,2.767,12.573,12.573,0,0,1-2.129,3.965,13.634,13.634,0,0,1-5.43,4A22.264,22.264,0,0,1,11.2,29.889c-.192.019-.348.038-.345.038.02.017.7.057,1.146.068v0c5.659.133,10.343-1.764,13.2-5.347a13.86,13.86,0,0,0,1.336-2.031,15.056,15.056,0,0,0,1.4-4.548A14.655,14.655,0,0,0,25.1,7.18a6.935,6.935,0,0,0-.92-1.04,14.645,14.645,0,0,0-5.655-3.214A21.205,21.205,0,0,0,12.086,2Zm6.68,10.8,0,0,.107.071c-.044-.028-.07-.051-.105-.073Zm.214.175.02.015v0l-.02-.013Zm.2,3.227,0,0,0,.018,0,0Zm-1.543,3.659-.008.016-.006.016.008-.016Zm-6.3,1.037-.025.02-.02.016.027-.018Z" style="fill:#00adee"/><path d="M4.76,23.949a1.5,1.5,0,0,1-.644-.875,2.1,2.1,0,0,1,.434-1.346A4.823,4.823,0,0,1,5.734,21h7.432c0-.089.9-.338.987-1.112.068-.6.437-1.63-.007-1.82C14.01,18.01,11.224,18,11.224,18l-2.29-.019L8.79,17.9a1.053,1.053,0,0,1-.534-1.028,1.889,1.889,0,0,1,.205-1.053,1.59,1.59,0,0,1,.62-.624c.345-.176.33-.175,2.924-.2l2.253-.02.205-.094a1.509,1.509,0,0,0,.81-1.04,2.31,2.31,0,0,0,.015-1.076,1.13,1.13,0,0,0-.7-.689L10.954,12l-3.442-.016-.158-.069a1.315,1.315,0,0,1-.737-1.3,1.751,1.751,0,0,1,.732-1.53L7.5,9l5.2,0c4.048,0,5.184,0,5.283.031a.9.9,0,0,1,.49.385,1.365,1.365,0,0,1,.044.979c-.139.636-.079.964.223,1.217A1.934,1.934,0,0,0,20,12h2a59.766,59.766,0,0,1-3,8s-.506.01-.993.007c-.536,0-.833.53-1.029.971-.209.472-.748,1.769-.956,2.063a2.7,2.7,0,0,1-1.054.991c-.119.043-.426-.009-4.929,0C5.816,24.035,4.881,23.984,4.76,23.949Z" style="fill:#949494"/></svg>
```

Cheers!

**Comment by JimiC** [comment]
`language ids` should ONLY be used when a `vscode` extension exists that declares and use it.

**Comment by ealap** [comment]
> @ealap I did a fast check on the svg file and to be honest, it is almost okay but need some fixes according to guidelines. The height is like 29px and hence, it doesn't satisfy the 2px margin for every side.
> 
> I did a little fix on the svg but too lazy to clone the branch, so I will let the code here:
> 
> ```
> <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><title>file_type_ttcn</title><path d="M12.086,2c-.718,0-.816.015-.377.062a21.978,21.978,0,0,1,2.389.4,16.45,16.45,0,0,1,7.714,3.824,12.314,12.314,0,0,1,3.786,7.4,15.018,15.018,0,0,1,.173,2.622,10.656,10.656,0,0,1-.039,1.3,14,14,0,0,1-.593,2.767,12.573,12.573,0,0,1-2.129,3.965,13.634,13.634,0,0,1-5.43,4A22.264,22.264,0,0,1,11.2,29.889c-.192.019-.348.038-.345.038.02.017.7.057,1.146.068v0c5.659.133,10.343-1.764,13.2-5.347a13.86,13.86,0,0,0,1.336-2.031,15.056,15.056,0,0,0,1.4-4.548A14.655,14.655,0,0,0,25.1,7.18a6.935,6.935,0,0,0-.92-1.04,14.645,14.645,0,0,0-5.655-3.214A21.205,21.205,0,0,0,12.086,2Zm6.68,10.8,0,0,.107.071c-.044-.028-.07-.051-.105-.073Zm.214.175.02.015v0l-.02-.013Zm.2,3.227,0,0,0,.018,0,0Zm-1.543,3.659-.008.016-.006.016.008-.016Zm-6.3,1.037-.025.02-.02.016.027-.018Z" style="fill:#00adee"/><path d="M4.76,23.949a1.5,1.5,0,0,1-.644-.875,2.1,2.1,0,0,1,.434-1.346A4.823,4.823,0,0,1,5.734,21h7.432c0-.089.9-.338.987-1.112.068-.6.437-1.63-.007-1.82C14.01,18.01,11.224,18,11.224,18l-2.29-.019L8.79,17.9a1.053,1.053,0,0,1-.534-1.028,1.889,1.889,0,0,1,.205-1.053,1.59,1.59,0,0,1,.62-.624c.345-.176.33-.175,2.924-.2l2.253-.02.205-.094a1.509,1.509,0,0,0,.81-1.04,2.31,2.31,0,0,0,.015-1.076,1.13,1.13,0,0,0-.7-.689L10.954,12l-3.442-.016-.158-.069a1.315,1.315,0,0,1-.737-1.3,1.751,1.751,0,0,1,.732-1.53L7.5,9l5.2,0c4.048,0,5.184,0,5.283.031a.9.9,0,0,1,.49.385,1.365,1.365,0,0,1,.044.979c-.139.636-.079.964.223,1.217A1.934,1.934,0,0,0,20,12h2a59.766,59.766,0,0,1-3,8s-.506.01-.993.007c-.536,0-.833.53-1.029.971-.209.472-.748,1.769-.956,2.063a2.7,2.7,0,0,1-1.054.991c-.119.043-.426-.009-4.929,0C5.816,24.035,4.881,23.984,4.76,23.949Z" style="fill:#949494"/></svg>
> ```
> Cheers!

thanks! I will try to implement this.

**Comment by ealap** [comment]
> `language ids` should ONLY be used when a `vscode` extension exists that declares and use it.

Actually, there is an extension for TTCN-3. It's a [syntax highlighter](https://marketplace.visualstudio.com/items?itemName=ealap.language-ttcn) which I made :)

**Comment by JimiC** [comment]
> Actually, there is an extension for TTCN-3. It's a [syntax highlighter](https://marketplace.visualstudio.com/items?itemName=ealap.language-ttcn) which I made :)
Then why didn't you mentioned it in your OP? The template is there for a reason.

**Comment by JimiC** [comment]
> Is there an additional step I need to do to implement this with `language ids`? I am getting this debug prints and I feel like it's related to your comment.

No. Other than what you did, it's fine, Can't think of reasons for the debug prints you are seeing.

**Comment by KingDarBoja** [comment]
I think it would be caused by this line:

```xml
 {
      icon: 'ttcn',
      extensions: [],
      languages: [languages.ttcn],
      filename: true, <-- // This line
      format: FileFormat.svg,
 },
```

As stated on the comments inside `IFileExtension`:
_"filename?: boolean; // set to true if the extension represents the whole file name."_

The extension doesn't represent the whole filename since you have files with some name followed by the `.ttcn` extension. Also, you should put the other two extension (`ttcn`, `ttcnpp`) on the **Extensions Array** like as: `extensions: ['ttcn', 'ttcnpp']`.

**Comment by JimiC** [comment]
@KingDarBoja Nice catch there, but you are wrong about adding the extra file extensions, as that will defeat the point of adding the `language id`. By using `language id` to associate the icon it's the `vscode` extension's responsibility to declare the file extensions it supports (like done in the [said extension](https://github.com/ealap/vscode-language-ttcn/blob/master/package.json#L46))

**Comment by KingDarBoja** [comment]
@JimiC My fault, didn't checked the provided extension and assumed the vscode-icons to work in another way. Now I learned something new regarding how this vs code extension works.

**Comment by ealap** [comment]
> entioned it in your OP? The templa

Right, I should have updated that. I created that ticket last year before I even started creating the extension that's why I left it blank.

**Comment by ealap** [comment]
As it turns out the debug print was caused by another extension! Oops! Sorry about that. But at least I get to more understand how the extension works, too. I got rid of the incorrect setting 'filename:true'.

**Pull request merged**
