### PR TITLE
Added tfvars, tfstate and tfstate.backup to terraform extensions

### PR DESCRIPTION
**Pull request by supergibbs**
Just added a few more terraform extensions

### CODE REVIEW

**Comment by robertohuertasm** [comment]
@supergibbs can you make the suggested change so we can merge your PR? 
You can use [custom icon associations](https://github.com/vscode-icons/vscode-icons#fine-tuning) for the `tfstate.backup` file.

**Comment by JimiC** [comment]
@robertohuertasm IF this doesn;t get followed up by the weekend I'm going to add the `tfstate` support on an upcoming PR and close this unmerged.

**Comment by robertohuertasm** [comment]
@JimiC agreed.

**Comment by supergibbs** [comment]
Sorry for the delay, I've removed those two extensions.

**Comment by robertohuertasm** [comment]
Thanks @supergibbs! @JimiC while we're at it... what do you think about including `tfvars` considering that we're removing non-native language ids support in the near releases?

**Comment by JimiC** [comment]
If `vscode` fixes the language id bug then there is no need to remove our feature. That's why I have this rollback on hold.

**Comment by robertohuertasm** [comment]
I thought we were removing this feature no matter what `vscode` team did because of 3rd party language id extensions not being consistent: `flow` extension using `javascript` as an id and so on.

**Comment by JimiC** [comment]
Still not sure how this is going to play out. I'll just give it some time.

**Comment by robertohuertasm** [comment]
Ok then! Merging this PR! Thanks @supergibbs! 👍

**Pull request merged**
