### PR TITLE
Add support for package.

### LINKED ISSUE #951: Support for PKG file
Hi,
it's possible to have support for file.pkg?

Support for PLSQL file #949

Thanks.

### PR DESCRIPTION
**Pull request by JimiC**
***Fixes #951***

Also, adds support for `packages` folder icon requsted in #650.

**Changes proposed:**
* [x] Add

### CODE REVIEW

**Comment by jens1o** [comment]
so #958 is obsolete now?

**Comment by JimiC** [comment]
No #958 is for `F#` `paket`. This is for `pkg` file extension and `packages` folder.

**Comment by jens1o** [comment]
When will you publish a new version?

**Comment by robertohuertasm** [comment]
Maybe today if I have time and you feel like it's a good time for it. Or do you have anything your working on? I can hold it until it's needed.

**Comment by jens1o** [comment]
No, I just want to get these fancy icons. :)

**Pull request merged**
