### PR TITLE
Update dependecies.

### PR DESCRIPTION
**Pull request by JimiC**

### CODE REVIEW

**Comment by jens1o** [comment]
maybe install @greenkeeper for this project?

**Comment by JimiC** [comment]
bithound marks it as `OUTDATED` but as I linked in the second commit there is a potential bug with `tslint 5.0.0`.

`Greenkeeper` looks as a good addition to the DevOps.

**Comment by JimiC** [comment]
From Travis-CI Status:
>Investigating - We're investigating build delays affecting all public repositories running at travis-ci.org. 
Apr 3, 17:12 UTC

**Comment by jens1o** [comment]
Shall we wait for it?

**Comment by JimiC** [comment]
Mandatory. It's a `Required` task.

**Comment by jens1o** [comment]
travis is back in service.

**Pull request merged**
