### PR TITLE
feat: add a few extra tsconfig paths

### PR DESCRIPTION
**Pull request by Bas950**
Adds a few extra tsconfig paths.

**Changes proposed:**

- [x] Add
- [ ] Delete
- [ ] Fix
- [ ] Prepare

### CODE REVIEW

**Comment by robertohuertasm** [comment]
@Bas950 can you elaborate why adding these paths?

**Comment by Bas950** [comment]
> @Bas950 can you elaborate why adding these paths?

Some repos use the .cjs and .esm to define what it should compile their typescript package too, they will run both builds to support both esm and cjs importing.

**Comment by Bas950** [comment]
And mjs is the same as esm just a different way of writing it.

**Comment by robertohuertasm** [comment]
Can you point me out to some of these repos?

**Comment by Bas950** [comment]
> Can you point me out to some of these repos?

Example of [Prisma](https://www.prisma.io/) using it in one of their repos (they have it in a lot):
https://github.com/prisma-labs/kontexture/blob/main/tsconfig.cjs.json
https://github.com/prisma-labs/kontexture/blob/main/tsconfig.esm.json

A tutorial about it: https://thesametech.com/how-to-build-typescript-project/

**Comment by Bas950** [comment]
`tsconfig.types.json` also gets used relatively often, if you want I can add that too.

**Comment by robertohuertasm** [comment]
@Bas950 thank you very much for the examples and the links! Really appreciate it! Regarding `tsconfig.types.json`, feel free to add it and I will approve. Let's merge this and ship it with this release.

**Comment by Bas950** [comment]
@robertohuertasm added it, thank you for your continuous responses this past hour, good night for now tho.

**Review by robertohuertasm — APPROVED** [review]
LGTM 🚀 Thanks for your contribution ❤️

**Pull request merged**
