### PR TITLE
Fix project autodetection on standalone files

### PR DESCRIPTION
**Pull request by zackschuster**
**Changes proposed:**

- [ ] Add
- [ ] Prepare
- [ ] Delete
- [x] Fix

**Things I've done:**

- [ ] My pull request fixes an issue, I referenced the issue.

currently throws here with "path must be a string or Buffer" error.

this PR introduces a simple `Array#filter` call to guard against that.

(as an aside, this could be caught with `--strictNullChecks` enabled :) )

### CODE REVIEW

**Comment by zackschuster** [comment]
note: i'll add a test later to make codecov happy. popped this up because i noticed the error when i was checking on something else from Running Extensions (which i guess displays uncaught errors now -- handy!)

**Comment by jens1o** [comment]
lgtm, waiting for @JimiC 's response

**Comment by JimiC** [comment]
@zackschuster Thanks for the PR but I have my doubts about it. `IVSCodeUri` is a reflected interface of `VSCodeUri` which is already strongly typed, meaning that `fspath` is always of type `string`. So your guard clause doesn't make sense. On the other hand, a `null` check guard clause makes more sense, considering also your mention about `--strictNullChecks` compiler option.

**Comment by zackschuster** [comment]
ah, my apologies -- the stack trace pointed to `readFileSync` throwing, so i assumed that was the culprit. it's not throwing on my machine anymore either, so problem solved? enough to close the PR, anyway.

that being said, i think `--strictNullChecks` would be great to add to the codebase. would you mind a PR at a later time attempting that?

thanks for your time :)

**Pull request closed without merging**
