### PR TITLE
Add support for .webp files

### PR DESCRIPTION
**Pull request by uu1t**
**Changes proposed:**

- [x] Add

Add support for .webp image files, which have been officially supported (Microsoft/vscode#35502).

### CODE REVIEW

**Comment by JimiC** [comment]
I believe that it would be best to assign that to a new icon ([icon](https://developers.google.com/speed/webp/images/webp-devsite-icon.png)) since `png`, `jpg` files and `webp` ones can reside side by side.

**Comment by uu1t** [comment]
Sorry for replying late.
I added a WebP icon which is downloaded from [Wikipedia](https://en.wikipedia.org/wiki/File:Webp-logo-wordmark.svg) and modified by myself.

I found that there is transparent blur around the icon and it seems smaller than other icons when resized to 28x28 px.
jpg-vs-webp
Should I fix it?

**Comment by JimiC** [comment]
I will review the icon and fix it if need be.

**Comment by uu1t** [comment]
Thanks, but I recreated a little bigger one whose content width is almost 28 px.
Please review new one.

**Pull request merged**
