### PR TITLE
feat(icon): add wikitext icon

### LINKED ISSUE #3051: [Icon Request]: WikiText
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Icon Type

- [X] File Icon
- [ ] Folder Icon

### Icon Type

- [X] Extension
- [X] Filename
- [X] Language ID

### Original Icon

image

### Icon Information

Language ID: `wikitext`
Extensions: `.wt`
aliases: `WikiText`, `wt`, `wikitext`, `Wikitext`
Icon Name: `wt`

### More Information:

https://en.wikipedia.org/wiki/Help:Wikitext

### PR DESCRIPTION
**Pull request by PAXANDDOS**
_**Fixes #3051**_

**Changes proposed:**

- [X] Add

### CODE REVIEW

**Review by sasial-dev — CHANGES_REQUESTED** [review]
That doesn't seem to match the icon in original issue...
Make the inside transparent, and provide a light icon with #d2d2d2

**Comment by PAXANDDOS** [comment]
> Make the inside transparent, and provide a light icon with #d2d2d2

Didn't get it really, you mean to make the transparent inside (which is now `#d2d2d2`) and use that color instead of black borders and a letter?

**Comment by robertohuertasm** [comment]
@PAXANDDOS thanks for this! I think if we keep the background white, the logo will work both for dark & light themes. WDYT?

**Comment by PAXANDDOS** [comment]
> @PAXANDDOS thanks for this! I think if we keep the background white, the logo will work both for dark & light themes. WDYT?

That's what I was thinking when creating the icon! If the background was transparent, we would need to add an alternative version for the other theme. Also, with transparent background icon would look weird since the letter "W" is in the box

**Comment by robertohuertasm** [comment]
Cool, then if you change this gray color for white I guess we're good to merge this one.

**Review by robertohuertasm — APPROVED** [review]

**Pull request merged**
