### PR TITLE
Support for CodeQL language

### LINKED ISSUE #2734: [Icon Request] Support for CodeQL
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `extension`, `languageId `
  - Icon Name: `codeql`
  - Sample original Icon: logo
  - Extensions: `ql, qll`
  - Language ids: `ql`

- Language Extensions: https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-codeql

### PR DESCRIPTION
**Pull request by lrecknagel**
_**Fixes #2734**_

**Changes proposed:**

- [x] Add

I´ve added CodeQL as language, taken the icon from the official VSCode CodeQL extention (https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-codeql)

### CODE REVIEW

**Review by KingDarBoja — APPROVED** [review]
Fixed the icon according to the guidelines.

**Comment by robertohuertasm** [comment]
Pending language id change as per [this comment](https://github.com/vscode-icons/vscode-icons/issues/2734#issuecomment-812519634)

**Review by robertohuertasm — CHANGES_REQUESTED** [review]
Language id should be `ql`

**Review by robertohuertasm — APPROVED** [review]
Thanks for this! Unfortunately, we've just cut a new release. We'll have to wait for the next one for this to be shipped.

**Review by robertohuertasm — APPROVED** [review]

**Pull request merged**
