### PR TITLE
feat(icon): add master-co icons

### LINKED ISSUE #2880: [Icon Request] Support for @master/cli
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `master`
  - Sample original Icon: logo
  - Filenames: `master.json`, `master.js`, `master.mjs`

- More info: Support for configuration file of @master/cli

### LINKED ISSUE #2984: [Icon Request] Support for @master/styles
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `master`
  - Sample original Icon: logo
  - Filenames: `master.styles.js`, `master.styles.ts`

- More info: 
Support for configuration file of @master/styles.

A Virtual CSS language with enhanced syntax

Homepage: [https://styles.master.co](https://styles.master.co)
Repository: [https://github.com/master-co/styles](https://github.com/master-co/styles)

The following is the configuration content of master.styles.js :
```js
/* 1. Prevent @master/styles from initializing automatically */
window.MasterStylesManual = true;
/* 2. Access APIs */
import { init } from '@master/styles';
import { Style } from '@master/style';
/* 3. Configure your initial options here ... */
Style.extend('classes', {
    btn: 'font:14 text:center h:40'
});
/* 4. Manually initialize */
init();
```

### PR DESCRIPTION
**Pull request by sasial-dev**
_**Fixes #2984
Fixes #2880**_

**Changes proposed:**

Add icon for master.styles & master config files.
More info at https://master.co/.

### CODE REVIEW

**Comment by sasial-dev** [comment]
@0Miles, can you review?

**Review by 0Miles — CHANGES_REQUESTED** [review]
Maybe the icon name can be changed to master-styles?
master-ui is a series.

**Review by 0Miles — APPROVED** [review]

**Comment by sasial-dev** [comment]
Problem with `master-styles` is that https://master.co/ indicates they plan on adding _much_ more

**Comment by 0Miles** [comment]
Then it is more suitable to use ``master`` or ``master-co`` for the icon name.
Not only master-ui , all other master series packages will also use this icon.

**Comment by sasial-dev** [comment]
Renamed to `master-co`, didn't want to use `master` as I didn't want a conflict :)

**Comment by 0Miles** [comment]
OK
Thanks a lot 👍

**Review by 0Miles — DISMISSED** [review]

**Comment by 0Miles** [comment]
@sasial-dev Hi,
Our project ``@master/styles`` has been renamed to ``@master/css``. Could you help rename ``master.styles.js`` and ``master.styles.ts`` to ``master.css.js`` and ``master.css.ts``?

**Review by 0Miles — APPROVED** [review]

**Review by robertohuertasm — APPROVED** [review]
LGTM 🚀 Thanks for your contribution ❤️

**Review by robertohuertasm — APPROVED** [review]

**Pull request merged**
