### PR TITLE
Update package.json with aspnetcorerazor code

### PR DESCRIPTION
**Pull request by Guar1**
Not sure if correct, first commit on outside project.

_**Fixes #IssueNumber**_
#1771
**Changes proposed:**

- [x] Add
- [ ] Delete
- [ ] Fix
- [ ] Prepare

### CODE REVIEW

**Comment by robertohuertasm** [comment]
@Guar1, sorry but this PR doesn't make any sense and hence it cannot be accepted as it is. 

Here you are the steps you should be following for this PR to be accepted:
1. Revert the changes to the `package.json` file
1. Go to this [line](https://github.com/vscode-icons/vscode-icons/blob/master/src/iconsManifest/languages.ts#L157) and let's modified it.
1. Take [ln 147](https://github.com/vscode-icons/vscode-icons/blob/master/src/iconsManifest/languages.ts#L147) as an  example. You'll have to add a new language id called `aspnetcorerazor` to line 157.
1. That's all! :wink: 

Waiting for your refactor!

Thanks for your contribution!

**Comment by Guar1** [comment]
Not sure how to "revert". Is it prerequisite?

**Comment by robertohuertasm** [comment]
Just undo what you did. Don't worry about reverting the commit. In the end we will squish it so it won't be a problem.

**Comment by JimiC** [comment]
Closing in favour of #1799

**Pull request closed without merging**
