### PR TITLE
Icon for the .spe extension of the spacengine template engine.

### LINKED ISSUE #2595: Icon for the .spe extension of the spacengine template engine.
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `png`
  - Icon Name: `spe`
  - Sample original Icon: logo
  - Extensions: `.spe`
  - Filenames: `*`
  - Language ids: `html`

- Language Extensions: .spe
- More info:

### PR DESCRIPTION
**Pull request by ceyrex20**
_**Fixes #2595**_

**Changes proposed:**

- [x] Add
- [ ] Delete
- [ ] Fix
- [ ] Prepare

### CODE REVIEW

**Review by ceyhun770 — APPROVED** [review]

**Review by ceyhun770 — DISMISSED** [review]

**Review by JimiC — CHANGES_REQUESTED** [review]
The icon is unacceptable. An `SVG` one is preferable.

**Comment by JimiC** [comment]
@ceyrex20 Let @KingDarBoja deal with the icon.

**Comment by ceyrex20** [comment]
> @ceyrex20 Let @KingDarBoja deal with the icon.

**Comment by ceyrex20** [comment]
> The icon is unacceptable. An `SVG` one is preferable.

How do I make svg from png?

**Comment by JimiC** [comment]
@ceyrex20 I already said, let the icon creation to us.

**Review by JimiC — CHANGES_REQUESTED** [review]
Unacceptable icon.

**Review by JimiC — CHANGES_REQUESTED** [review]
Unacceptable icon.

**Pull request closed without merging**
