### PR TITLE
Use 'TSLint' instead of 'ESLint'.

### PR DESCRIPTION
**Pull request by JimiC**

### CODE REVIEW

**Comment by JimiC** [comment]
Not sure where this file is used though.

**Comment by jens1o** [comment]
In fact, is was planned in the early stages with the extension. Orginnally, it was my idea. But I think it's obsolete.

**Comment by JimiC** [comment]
That's what I thought. @robertohuertasm Does this go to the `Trash Bin`?

**Comment by robertohuertasm** [comment]
This is from when we used `vanilla js`. It has no sense now.

**Comment by jens1o** [comment]
Why did you merged this? Shouldn't it removed? 😄

**Comment by JimiC** [comment]
Apparently, it has  sentimental value to @robertohuertasm 🤣

**Comment by robertohuertasm** [comment]
Do you want to remove the file? I thought you were talking about the Eslint reference.

**Comment by jens1o** [comment]
nah, we want to remove the line. 😆

**Comment by JimiC** [comment]
Why not remove the file entirely?

**Comment by jens1o** [comment]
Because maybe someone does not know the common conventions when creating PRs?

**Comment by robertohuertasm** [comment]
This document is the one everyone creating an issue or a PR has access to via a link:
image

Why do you want to remove it?

**Comment by JimiC** [comment]
PRs have their own `md`.

**Comment by JimiC** [comment]
So that where it's used, finally. So either we keep the line with reference to `TSLint` or we remove the line as linting is embedded in the CI.

**Comment by jens1o** [comment]
Hmm, I would let it there. So the PR is just fine.

**Comment by robertohuertasm** [comment]
I'll keep the reference so they are advised to test it locally before arriving to CI.

**Pull request merged**
