### PR TITLE
Unused local variables removed.

### PR DESCRIPTION
**Pull request by robertohuertasm**
--no-unused-locals added to `tsconfig.json`.

### CODE REVIEW

**Comment by JimiC** [comment]
It's recommended to also use `noUnusedParameters` option.

**Comment by robertohuertasm** [comment]
I didn't want to be so restrictive... but wtf!

**Comment by JimiC** [comment]
You're playing with my OCD mate, aren't you?

**Comment by JimiC** [comment]
You need to also run `yarn upgrade` to update the `yarn.lock` file.

**Comment by robertohuertasm** [comment]
I don't really use `yarn`... but you're right. I'll do it.

**Comment by JimiC** [comment]
It's the only tool I use from `Facebook`. Once you work with it you are going to appreciate it.

**Comment by robertohuertasm** [comment]
I've already tried it. But I'm really used to old npm quirks. 😜

**Comment by JimiC** [comment]
As they say "Can't teach an old dog new tricks". Btw, I'm amazed we had so many redundant variables in the code.

**Comment by robertohuertasm** [comment]
Yes, me too. I was playing with it the other day and noticed it and thought that it was a nice thing to have the check into the `typescript` compiler configuration.

**Comment by JimiC** [comment]
To be honest I stumbled on them today when I was working on the [ng-dygraphs](https://www.npmjs.com/package/ng-dygraphs) package.

**Comment by robertohuertasm** [comment]
Are you using it for work or a side project?

**Comment by JimiC** [comment]
On a work project.

**Comment by robertohuertasm** [comment]
That might be of my interest... nice library. I'm starting to work on a new project to provide Agile charts for Gitlab and custom boards and I was looking for a nice Angular 2 chart library. Thanks for the link!

**Comment by JimiC** [comment]
I thought it may interest you. I was looking for Angular 2 chart libraries for that project and amongst others `dygraphs` is really awesome.

**Pull request merged**
