### PR TITLE
feat(icon): add pulumi icon

### PR DESCRIPTION
**Pull request by PAXANDDOS**
**Changes proposed:**

- [X] Add

More info at [pulumi.com](https://www.pulumi.com/)
Also changed the order of the closest objects, they were not alphabetical.

@robertohuertasm Can you also check [my other PRs](https://github.com/vscode-icons/vscode-icons/pulls/paxanddos) please? I've made quite a lot last month and yet none of them has been reviewed 😢 Some of them are meant to close some of the other PRs (which have been stuck here for a long time), and some of the old PRs are already closed, thanks to devs' understanding.

### CODE REVIEW

**Review by robertohuertasm — APPROVED** [review]
LGTM 🚀 Thanks for your contribution ❤️

**Comment by robertohuertasm** [comment]
@PAXANDDOS I optimized the icon a little bit. Note that this project is under low maintenance mode these days and most of the icons PR must be reviewed manually. Most of the time, they're ok, but the icons are usually not optimized so it requires some time for us to review. 

I'm planning on doing small releases and clean the PR queue, but it all depends on the free time I have which is not that much. Please, be patient as all the PR will eventually be merged or closed.

**Comment by PAXANDDOS** [comment]
Got it, thanks ❤️ 

But also,
> Most of the time, they're ok, but the icons are usually not optimized so it requires some time for us to review.

How do you optimize icons? I'm always trying to keep them clean while working in AI/Figma, but I guess you do use something else to make code shorter

**Comment by robertohuertasm** [comment]
Yes, we use Illustrator and we export it for web. Normally it is ok if they're 2kb or less. See [here the guide in the wiki](https://github.com/vscode-icons/vscode-icons/wiki/Contributing#recommended-settings-for-adobe-illustrator). 
I'd like to provide a non-proprietary guide too, possibly with Inkscape. Hopefully soon! ;D

**Comment by robertohuertasm** [comment]
BTW, maaaany thanks for your contributions!!! ❤️ ⭐

**Pull request merged**
