### PR TITLE
Add default webpack extensions

### LINKED ISSUE #837: Additional default extensions for webpack
Hello,

**Current state**: 
webpack

**Action**: Add a couple default extensions for webpack configuration files to support webpack icon wo/ plugin's config customization.

**Motivation** to include more default suffixes for default prefix `webpack.config*`:

- `*.base.js` : As mentioned in official webpack [docs](https://webpack.js.org/guides/production-build/) such name convention is acceptable for basic configuration which is inheritable and extensible;

- `*.development.js`: Similar extension suffix exists for production configuration file (`*.prod.js`, `.production.js`);

- for all mentioned extensions: Such naming convention is observed in several boilerplates for webpack configuration, for example [srn/react-webpack-boilerplate](https://github.com/srn/react-webpack-boilerplate) ;

**Pull request**: #836

Thanks.

- [x] I'm sure this issue is not a *duplicate*?

### PR DESCRIPTION
**Pull request by AntonYaskevich**
***Fixes #837***

**Changes proposed:**
* [x] Add
* [ ] Prepare
* [ ] Delete
* [ ] Fix

**Things I've done:**
* [x] My pull request fixes an issue, I referenced the issue.

Add several default extensions for webpack configuration files to support webpack icon wo/ plugin's config customization.

### CODE REVIEW

**Comment by JimiC** [comment]
@jens1o It's fine. They aren't in an alphabetic order either now. I was planning to do this on another PR where I'll put the `ts` and `coffee` versions.

**Comment by jens1o** [comment]
Yes, I know. I thought when he's modifying the extensions, it may be a good moment to order them.

**Comment by JimiC** [comment]
It's really trivial. No need to block the PR for that.

**Comment by AntonYaskevich** [comment]
Hello @jens1o , 

I've pushed some changes that u had mentioned. But I've sorted extensions items in semantic order respectively to environments prefixes like `*.dev.*`, `*.prod.*` and etc, and suffixes `*.js`, `*.babel.js`, `*.ts`, `*.coffee`. I've also added `development` env prefix for `babel` suffix and replaced double quotes with single quotes fro common convention.

What do u thinks about this?

**Comment by jens1o** [comment]
I'm fine with this. Thanks!

**Pull request merged**
