### PR TITLE
Update Vlang logo

### PR DESCRIPTION
**Pull request by Delta456**
Update V lang logo as per [now](https://github.com/vlang)

Site would be updated with the new logo soon. 

**Changes proposed:**

- [ ] Add
- [ ] Delete
- [x] Fix
- [ ] Prepare

### CODE REVIEW

**Comment by Delta456** [comment]
Should I close this then?

**Comment by KingDarBoja** [comment]
> Should I close this then?

No no, keep it open, I will make the changes and push to your branch. The only thing that bother me is that the current logo was taken from the PNG since it is not available as svg. I submitted an issue on the vlang repo in order to request the svg version.

It will help us to keep the quality of the logo since it has some effects that are not easily reproducible and to be honest, I am too lazy right now to do it.

**Comment by donnisnoni95** [comment]
@KingDarBoja I'm here to fix this ... BTW Where can I see the guidelines?

**Comment by donnisnoni95** [comment]
@KingDarBoja Thank you so much  👌

**Comment by Delta456** [comment]
Thanks

**Comment by ylluminate** [comment]
This is great, why hasn't it been merged yet?

**Comment by Delta456** [comment]
@ylluminate It's merged

**Pull request merged**
