### PR TITLE
Replace ${workspaceRoot} with ${workspaceFolder}

### PR DESCRIPTION
**Pull request by torn4dom4n**
VSCode is deprecating `${workspaceRoot}` and have introduced a new substitution variable `${workspaceFolder}`. This variable will get substituted to the absolute path of the workspace folder containing the appropriate `launch.json` or `tasks.json`.

### CODE REVIEW

**Comment by JimiC** [comment]
@torn4dom4n Please sync your `master` branch before submitting a PR.

**Comment by JimiC** [comment]
Please revert.

**Comment by JimiC** [comment]
@robertohuertasm Did you test it?

**Comment by torn4dom4n** [comment]
@JimiC You can read about it at [here](https://code.visualstudio.com/updates/v1_17#_workspacefolder-in-launchjson-and-tasksjson).

**Comment by JimiC** [comment]
@torn4dom4n I know about the deprication but changes as this should be tested never the less.

**Comment by JimiC** [comment]
And after all, there is no hurry. `workspaceRoot` will be kept for backwards compatibility.

**Comment by torn4dom4n** [comment]
I see VSCode 1.18 (Next version) also announced [it](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_18.md#variable-names).

**Comment by robertohuertasm** [comment]
I've tried it and it seems to be working as expected. No issues with this change as far as I can see.

**Comment by JimiC** [comment]
OK, then. There is also a change needed in `tasks.json` while we are on replacing deprecated keys.

**Pull request merged**
