### PR TITLE
Add support for Gitpod config file

### LINKED ISSUE #2695: [Icon Request] Support for Gitpod
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `gitpod`
  - Sample original Icon: logo
  - Filenames: `gitpod.yaml`, `gitpod.yml`, `.gitpod.yaml`, `.gitpod.yml`

- More info:
  - [Homepage](https://www.gitpod.io/)
  - [Config file docs](https://www.gitpod.io/docs/config-gitpod-file/)
  - [Config file name variants discussion](https://github.com/gitpod-io/gitpod/issues/729#issuecomment-772506083)

### PR DESCRIPTION
**Pull request by mikenikles**
_**Fixes #2695**_

**Changes proposed:**

- [x] Add
- [ ] Delete
- [ ] Fix
- [ ] Prepare

### CODE REVIEW

**Comment by gtsiolis** [comment]
Hey @robertohuertasm! Feel free to take a look at this or forward to someone. 🏀

**Review by robertohuertasm — CHANGES_REQUESTED** [review]
Could you remove the white background of the icon?

**Comment by carlocorradini** [comment]
> Could you remove the white background of the icon?

I've found the image in SVG format in the media Kit: <https://www.gitpod.io/media-kit>

**Comment by carlocorradini** [comment]
> > Could you remove the white background of the icon?
> 
> I've found the image in SVG format in the media Kit page: https://www.gitpod.io/media-kit

SVG source:
```xml
data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI4MS43ODQiIGhlaWdodD0iOTQuNDYxIiB2aWV3Qm94PSIwIDAgODEuNzg0IDk0LjQ2MSI+PGRlZnM+PHN0eWxlPi5he2ZpbGw6IzAwODdiZX0uYntmaWxsOiMxYWE2ZTR9LmN7ZmlsbDojMDA5MmNmfTwvc3R5bGU+PC9kZWZzPjxwYXRoIGQ9Ik00MC44NjksMTEyLjkyNyw4LjEsOTQuMTYyVjU2LjMxNGguMDQ2TDAsNTEuNlY5OC44MzFIMGw0MC44NjksMjMuNjE1aDBaIiBjbGFzcz0iYSIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMCAtMjcuOTg1KSIvPjxwYXRoIGQ9Ik02MC4yMzEsODYuNDQyaDBMMzUuNzQ2LDcyLjNIMzUuN3YyOC4zMjlsMjQuNTMxLDE0LjA1WiIgY2xhc3M9ImEiIHRyYW5zZm9ybT0idHJhbnNsYXRlKC0xOS4zNjEgLTM5LjIxMSkiLz48cGF0aCBkPSJNODEuNzg0LDIzLjYxNSw0MC44NjksMCwwLDIzLjYxNUgwbDguMTQ2LDQuNzE0LDMyLjcyMy0xOC45TDczLjY4MywyOC4yODNsOC4xLTQuNjY4WiIgY2xhc3M9ImIiLz48cGF0aCBkPSJNODQuODYxLDU1LjQ0Miw2MC4zMzEsNDEuMywzNS44LDU1LjQ4Nyw2MC4yODUsNjkuNjI5WiIgY2xhc3M9ImIiIHRyYW5zZm9ybT0idHJhbnNsYXRlKC0xOS40MTYgLTIyLjM5OSkiLz48cGF0aCBkPSJNODkuMyw4Ni4zODdoMEwxMTMuODc2LDcyLjJoMFoiIGNsYXNzPSJjIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgtNDguNDMxIC0zOS4xNTcpIi8+PHBhdGggZD0iTTE2MSw1Ni4yNjhoMGw4LjEtNC42NjhoMFoiIGNsYXNzPSJjIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgtODcuMzE3IC0yNy45ODUpIi8+PHBhdGggZD0iTTEzMC4yMTUsNTEuNmwtOC4xLDQuNjY4LTguMjM4LDQuNzZMODkuMyw3NS4yMTVoMHY0LjIxaDBWOTAuNjM4aDB2MTIuODE1aDBsMjQuNTc2LTE0LjFWODAuMDIxTDk3LjQsODkuNFY3OS44ODNsMjQuNzE0LTE0LjA1Vjk0LjE2Mkw4OS4zLDExMi45Mjd2OS41MTlsNDAuOTE1LTIzLjYxNWgwWiIgY2xhc3M9ImMiIHRyYW5zZm9ybT0idHJhbnNsYXRlKC00OC40MzEgLTI3Ljk4NSkiLz48L3N2Zz4=
```

**Comment by KingDarBoja** [comment]
I have fixed the icon according to guidelines. cc @robertohuertasm

**Review by ghuntley — COMMENTED** [review]
Gitpod now has a new logo. Please don't merge this until pending commits ship. Thanks :)

**Comment by carlocorradini** [comment]
> Gitpod now has a new logo. Please don't merge this until pending commits ship. Thanks :)

Which is the new logo? I'm curious 😁

The image is taken directly from <https://www.gitpod.io/media-kit>

**Comment by mikenikles** [comment]
🎉  I pushed the new logo. Thanks for holding off with merging that PR.

**Pull request merged**
