### PR TITLE
Fix opening urls.

### PR DESCRIPTION
**Pull request by JimiC**
URLs don't reside in `i18n` manager anymore. My bad for not correcting the code in the first place.

### CODE REVIEW

**Comment by JimiC** [comment]
While at it I'd like to propose to change the welcome message and introduce an `Activate` button. Thoughts?

**Comment by jens1o** [comment]
@JimiC Technically, we can do that. Because then we modify the user settings, and boom, we're activated... But I don't know whether this fits ethically...

Okay. As long as we're sticking to that question, it's fine for me, when thinking about that there are well-watched videos on YouTube on how to activate our theme, where I think... wut?

**Comment by robertohuertasm** [comment]
@JimiC, I think [material icons](https://marketplace.visualstudio.com/items?itemName=PKief.material-icon-theme) already does that:
image

I guess we could follow the lead.

**Comment by JimiC** [comment]
@robertohuertasm Exactly what I saw and came up with the proposal.

**Comment by robertohuertasm** [comment]
note that they also add a new setting:
image

It's ok for me.

**Comment by robertohuertasm** [comment]
@JimiC, I accept this PR and you'll do that in another one?

**Comment by JimiC** [comment]
This PR and the proposal are diff things.

**Comment by JimiC** [comment]
@robertohuertasm You can accept this any time now.

**Pull request merged**
