### PR TITLE
Clarifies the config setting for default folder and file icon.

### LINKED ISSUE #1130: Unclear configurations settings.
### This issue references #1129 PR.
While translating the configurations I was not really sure about what those settings do and how :   

- _configuration.associations.fileDefault.file.description_  
- _configuration.associations.fileDefault.file_light.description_  
- _configuration.associations.fileDefault.folder.description_  
- _configuration.associations.fileDefault.folder_light.description_

The description being: _"This setting will let you change default dark file icon."_  

What I understand from it is that by giving a path you can define custom icon for the dark file icon.  
 
I think the description should be changed independently of this being wrong or not as I was unable to figure out what the setting was even by reading it.

### PR DESCRIPTION
**Pull request by JimiC**
***Fixes #1130***

**Changes proposed:**
* [x] Fix

**Things I've done:**
* [x] My pull request fixes an issue, I referenced the issue.

**This PR**:
1. is a suggestion to clarify what the configuration settings, related to setting the default icon for folders and files in `dark` and `light` themes, does.
2. ~~is a draft and is subjected to changes.~~ has been finalized.
3. needs changes to translations upon finalization.

### CODE REVIEW

**Comment by robertohuertasm** [comment]
@MonsieurMan, can you give us your feedback before merging this?

**Comment by robertohuertasm** [comment]
I guess every language should be checked again to follow the new texts.

**Comment by JimiC** [comment]
@robertohuertasm Already mentioned in the PR description.

**Comment by JimiC** [comment]
Respected translation contributors please provide an update for these changes.

German: @jens1o
Italian: @sabinrimni @mariotsi 
Russian: @ksvitkovsky 
Spanish: @robertohuertasm
Simplified Chinese: @g-plane @iFun

**Comment by mariotsi** [comment]
* configuration.associations.fileDefault.file.description: Questa impostazione ti permette di cambiare l'icona predefinita per i file nei temi scuri.
* configuration.associations.fileDefault.file_light.description: Questa impostazione ti permette di cambiare l'icona predefinita per i file nei temi chiari.
* configuration.associations.folderDefault.folder.description: Questa impostazione ti permette di cambiare l'icona predefinita per le cartelle nei temi scuri.
* configuration.associations.folderDefault.folder_light.description: Questa impostazione ti permette di cambiare l'icona predefinita per le cartelle nei temi chiari.

**Comment by g-plane** [comment]
configuration.associations.fileDefault.file.description: 这项设置会更改深色主题默认的文件图标
configuration.associations.fileDefault.file_light.description: 这项设置会更改浅色主题默认的文件图标
configuration.associations.folderDefault.folder.description: 这项设置会更改深色主题默认的文件夹图标
configuration.associations.folderDefault.folder_light.description: 这项设置会更改浅色主题默认的文件夹图标

**Comment by jens1o** [comment]
```json
"configuration.associations.fileDefault.file.description": "Diese Einstellung macht es dir möglich, ein benutzerdefiniertes Datei-Icon für dunkle Themes zu verwenden.",
"configuration.associations.fileDefault.file_light.description": "Diese Einstellung macht es dir möglich, ein benutzerdefiniertes Datei-Icon für helle Themes zu verwenden.",
"configuration.associations.folderDefault.folder.description": "Diese Einstellung macht es dir möglich, ein benutzerdefiniertes Ordner-Icon für dunkle Themes zu verwenden.",
"configuration.associations.folderDefault.folder_light.description": "Diese Einstellung macht es dir möglich, ein benutzerdefiniertes Ordner-Icon für helle Themes zu verwenden."
```

**Comment by ksvitkovsky** [comment]
```
"configuration.associations.fileDefault.file.description": "Настройка позволяет переопределить значок файла по-умолчанию для темной темы",
"configuration.associations.fileDefault.file_light.description": "Настройка позволяет переопределить значок файла по-умолчанию для светлой темы",
"configuration.associations.folderDefault.folder.description": "Настройка позволяет переопределить значок папки по-умолчанию для темной темы",
"configuration.associations.folderDefault.folder_light.description": "Настройка позволяет переопределить значок папки по-умолчанию для светлой темы"
```

**Comment by robertohuertasm** [comment]
@JimiC, the Spanish translations was already saying what the English translation says now so there's no need to update that language.

**Pull request merged**
