### PR TITLE
Update vscode logo to new one. Keep old as alternative.

### LINKED ISSUE #1146: [Task] Update to new vscode logo
- [x] I'm sure this issue is not a *duplicate*?

`vscode` is getting a new logo, noticeable in the latest insiders version ([press release](https://mspoweruser.com/visual-studio-code-getting-new-logo/)). 

Main logo
----
logo

Context menu logo
----
logo

For better visibility and clarity I suggest we use the "Context menu logo" for `vscode` related files.

@robertohuertasm @jens1o Thoughts?

### PR DESCRIPTION
**Pull request by JimiC**
***Fixes #1146***

**Changes proposed:**
* [x] Add

**Things I've done:**
* [x] My pull request fixes an issue, I referenced the issue.

Kept old logo as an alternative.

### CODE REVIEW

**Comment by JimiC** [comment]
Not understanding what you mean.

**Comment by jens1o** [comment]
I mean, in this pr our extension logo is not updated... Do you intend to make the change, and if yes, in a later pr?

**Comment by JimiC** [comment]
Wow. You totally right. Missed that. Will update the PR asap.

**Comment by JimiC** [comment]
Boggers. Need to change the folder icon too.

**Comment by JimiC** [comment]
@robertohuertasm `vscode v1.16` was released and logo didn't change. So hold this PR until the logo switch is done.

**Comment by JimiC** [comment]
I've been wondering if it's worth implementing `vscode` version detection and enable the `vscode` icon depending on it. We could utilize PAD to that.

Thoughts?

**Comment by JimiC** [comment]
Looking at the way to implement a `vscode` version detection and load the appropriate `vscode` icon according to it, I have some concerns about it. You see, adding such a functionality will introduce another "Restart" info message and action. Taking into account the UX I can't stop wondering, "is it worth it?".

**Comment by robertohuertasm** [comment]
In my opinion it's not worth it. 

A less invasive approach would be to use different manifests depending on our vscode version (stable or insiders) but I think we should wait and see what happens with all this logo issue.

**Comment by KamasamaK** [comment]
The new icon has now shipped with version 1.17

**Comment by JimiC** [comment]
@KamasamaK Thanks for letting us know.

**Comment by KamasamaK** [comment]
FYI, the icon is being changed back: https://code.visualstudio.com/blogs/2017/10/24/theicon

**Comment by jens1o** [comment]
I just wanted to push this again with the exact same topic. BUT I (really) loved the new icon. Please let us keep the `new` one as an alternative. I just got used to it and do not want to miss it. :)

**Comment by JimiC** [comment]
The color is changing not the icon. And changing the color is really a trivial task.

**Comment by jens1o** [comment]
Programmers are quite lazy? 😉

**Comment by JimiC** [comment]
You know that there is a distinguishable difference between a developer and a programmer, right?

**Comment by jens1o** [comment]
Can you elaborate on this? Sorry :(

**Comment by JimiC** [comment]
I'll let you figure this one out yourself.

**Pull request merged**
