### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by robertohuertasm**
Enjoy!

### CODE REVIEW

**Comment by JimiC** [comment]
@robertohuertasm Care to provide the missing Spanish translations?

**Comment by robertohuertasm** [comment]
@JimiC done!

**Comment by JimiC** [comment]
Hold the merge

**Comment by JimiC** [comment]
I have to reconstruct all missing translations now. It will take some time.

**Comment by JimiC** [comment]
Please DO NOT merge.

**Pull request closed without merging**
