### PR TITLE
feat(icon): add funding icon

### LINKED ISSUE #3013: [Icon Request]: Support for funding.yml
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `sponsors`
  - Sample original Icon: logo
  - Filenames: `funding.yml`

- More info:

  The sample original icon comes from GitHub sponsors. More funding platforms are supported.

  https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

### PR DESCRIPTION
**Pull request by sasial-dev**
_**Fixes #3013**_

**Changes proposed:**

Add icon for `funding.yml`

### CODE REVIEW

**Review by robertohuertasm — COMMENTED** [review]
@sasial-dev not sure why, but I can't see this svg with Illustrator. It's not the first time it happens. I'm wondering if there's an easy fix for this.

**Comment by robertohuertasm** [comment]
Are you using Inkscape to generate these icons?

**Review by robertohuertasm — APPROVED** [review]
I've standardized the svg. Thanks for this!

**Comment by sasial-dev** [comment]
I've been using boxy-svg, but was wanted to move over to ilistrator!
Sorry about that! 😔

**Comment by robertohuertasm** [comment]
No problem at all @sasial-dev. You don't have to apologize for that. I'm grateful to you for your considerable contribution to this repository! 👏🏻 👍🏻

**Pull request merged**
