### PR TITLE
feat(icon): add phpstan icon

### LINKED ISSUE #3040: [Icon Request]: Support for PHPStan
### Housekeeping

- [X] I'm sure this issue is _not_ a duplicate

### Icon Type

- [X] File Icon

### Icon Type

- [X] Filename

### Original Icon

file_type_phpstan

### Icon Information

Since PHPStan does not provide its logo in SVG format, it was drawn in Adobe Illustrator with PNG reference

Filenames: `phpstan.neon`, `phpstan.neon.dist`, `phpstan.dist.neon` ([Source](https://phpstan.org/config-reference#config-file))

### More Information:

https://phpstan.org/

### PR DESCRIPTION
**Pull request by PAXANDDOS**
_**Fixes #3040**_

**Changes proposed:**

- [x] Add

Since PHPStan does not provide its logo in SVG format, it was drawn in Adobe Illustrator with PNG reference

### CODE REVIEW

**Review by robertohuertasm — COMMENTED** [review]
LGTM 🚀 Thanks for your contribution ❤️

**Review by robertohuertasm — DISMISSED** [review]

**Comment by PAXANDDOS** [comment]
@robertohuertasm Oh wait! I think you just broke the icon... 😵 
image

**Comment by robertohuertasm** [comment]
Yes! you're totally right! let me fix it

**Comment by robertohuertasm** [comment]
Now it should be fixed! Good catch!

**Review by robertohuertasm — APPROVED** [review]

**Pull request merged**
