### PR TITLE
version bump

### PR DESCRIPTION
**Pull request by robertohuertasm**
How do you feel about the installations number? I would like to know your thoughts before merging this PR. :wink:

### CODE REVIEW

**Comment by JimiC** [comment]
Putting it politely. :-1:
But if you feel like adding them I would add the installs per version.

**Comment by robertohuertasm** [comment]
The thing is that I don't know the installs per version. We need the difference to know it. That's why I thought that this could be useful but I also have my doubts about it.

**Comment by robertohuertasm** [comment]
I'll write this down somewhere and leave this for future consideration.

**Comment by JimiC** [comment]
The thing is that you are the only one that knows those numbers and if anyone else wants to compile a new changelog entry will not know that info.

**Comment by robertohuertasm** [comment]
It's public information. At least I thought it was. I get the information from [here](https://marketplace.visualstudio.com/items?itemName=robertohuertasm.vscode-icons)

**Comment by JimiC** [comment]
Oh. Then the number will not be accurate. How do you know the exact number of the version until you actually push the new one? I mean from the time you add the info, commit, publish some more installations have been done.

**Comment by robertohuertasm** [comment]
It's not accurate, that's for sure. It's an orientative figure.  I get the number just before using the `vsce` tool. Normally, after a week of a release, the number of installs slows down so it's not a huge error margin. This would be for statistical purposes only so we could know the growing trends of the extension and evaluate if people is adopting or running away whenever we change something.

**Comment by robertohuertasm** [comment]
I'll keep this info noted outside the repo for our information for the moment.

**Comment by jens1o** [comment]
We may round the numbers?

**Comment by JimiC** [comment]
Insights Analytics.

**Comment by JimiC** [comment]
I used to use GA for monitoring in another project.

**Comment by robertohuertasm** [comment]
Never mind guys. I didn't want to be invasive by installing analytics. Let's leave it like it is.

**Comment by JimiC** [comment]
Yeah, that's a tricky thing.

**Pull request merged**
