### PR TITLE
Fix babelrc extension

### PR DESCRIPTION
**Pull request by zalishchuk**
**Changes proposed:**
Rename `babelrc.js` to `.babelrc.js`, because `baberc.js` filename is not supported according to [cosmiconfig](https://github.com/davidtheclark/cosmiconfig) specification.

- [ ] Add
- [ ] Delete
- [x] Fix
- [ ] Prepare

### CODE REVIEW

**Comment by robertohuertasm** [comment]
Maybe it would be better to keep the former extension for retro-compatibility's sake. What do you think @JimiC, @jens1o?

**Comment by robertohuertasm** [comment]
By the way, thank you @zalishchuk for this PR! 😉

**Comment by zalishchuk** [comment]
As it turned out, Babel is not using cosmiconfig to load configuration files. According to [this](https://github.com/babel/babel/blob/master/packages/babel-core/src/config/files/configuration.js#L19) file, icon should be supported on these filenames:
- `.babelrc`
- `.babelrc.js`
- `.babelignore`
- `babel.config.js`

**Comment by JimiC** [comment]
Backwards compatibility should be used whenever possible.

**Comment by zalishchuk** [comment]
@JimiC check this out - https://github.com/vscode-icons/vscode-icons/pull/1621/commits/3747ce011d63885cfd16494a1c33893b859b9f9d

**Pull request merged**
