### PR TITLE
Add Vala & vapi

### PR DESCRIPTION
**Pull request by ZanderBrown**
[Vala](https://wiki.gnome.org/Projects/Vala) is a language and vapi are it's "header" files

Vala doesn't have an official icon so that of [Valadoc.org](https://valadoc.org/) has been used

**Changes proposed:**

- [X] Add
- [ ] Delete
- [ ] Fix
- [ ] Prepare

### CODE REVIEW

**Comment by JimiC** [comment]
My only objection is that the `stroke`s of the icons seems like they haven't been outlined. I may have to modify the icons to fit our art guidelines.

Other than that, nice work, @ZanderBrown, and thanks for your contribution.

**Comment by ZanderBrown** [comment]
Sure play with the outlines, they where added because the `vala` icon was disappearing on dark backgrounds. Whilst `vala` uses the colour from the Valadoc.org icon `vapi` is arbitrarily coloured just to be different from `vala`

**Comment by ZanderBrown** [comment]
The `<path>` `style=` was generated by Inkscape, I've now simplified them. Does that relieve your concerns?

**Comment by JimiC** [comment]
Just leave them as they are. When I find some time I'm going to adjust them.

**Comment by gavr123456789** [comment]
On black themes icons have white border  
image

**Comment by gavr123456789** [comment]
Also main Vala color was changed https://twitter.com/elementary/status/1262095965210554368  
to 7d37aeff.  
It is lighter so the icon will be better visible.

**Comment by KingDarBoja** [comment]
Hi @gavr123456789 

Please open a new issue with the changes being proposed for Vala icon.

**Pull request merged**
