### PR TITLE
Enable your extension to run on VS Code for the web

### PR DESCRIPTION
**Pull request by tanhakabir**
References #2826 

Hello! 👋

I'm part of the VS Code team and we recently launched VS Code for the web with github.dev! You can read the full guide for extension authors creating and migrating extensions here: Web Extensions

In hopes to help you migrate I attempted to help make the changes necessary to make your extensions work on the web. Unfortunately many of your dependencies (like `cosmicconfig` and `is-docker`) use node libraries that are not available in the browser. 

Creating and closing a PR anyways as a general guidance of what needs to be done!

The changes I made:

- Modify webpack bundling to add configurations for web versions of entry extension script and uninstall extension script
- Add fallback of `path` to `path-browserify` in web context
- Add constants for web-context entry and uninstall files
- Replace usage of `fs` with the [VS Code FileSystemProvider](https://github.com/microsoft/vscode/blob/fc41c9fb60ccb9d9aaa2c62165ed979d69256adc/src/vs/vscode.d.ts#L7190)

### CODE REVIEW

**Comment by tanhakabir** [comment]
cc @robertohuertasm @KingDarBoja

**Comment by robertohuertasm** [comment]
Hi @tanhakabir! Thank you very much for this! We'll have to study this and see if the effort is worth it as we're now in a very low maintenance availability.

**Comment by HKalbasi** [comment]
Is anyone actively working on this? If not, I like to take a look at it.

**Comment by robertohuertasm** [comment]
Hi @HKalbasi, not really. You can take a look if you want! 🙌🏻

**Comment by tanhakabir** [comment]
Reopening this PR just for visibility!

**Comment by barnuri** [comment]
please add support to github.dev

**Review by barnuri — APPROVED** [review]

**Comment by robertohuertasm** [comment]
@barnuri maybe this answer comes a little bit late. Sorry for that. I started the migration to adding support for the web. I hope to have it working soon.

**Comment by barnuri** [comment]
> @barnuri maybe this answer comes a little bit late. Sorry for that. I started the migration to adding support for the web. I hope to have it working soon.

thanks :)

**Comment by robertohuertasm** [comment]
Closing this one as the extension now offers a limited but functional version for the web.

**Pull request closed without merging**
