### PR TITLE
feat(stryker): add icon for stryker

### PR DESCRIPTION
**Pull request by nicojs**
**Changes proposed:**

- [x] Add
- [ ] Delete
- [ ] Fix
- [ ] Prepare

See 
https://stryker-mutator.io/docs/stryker-js/config-file#setup
https://stryker-mutator.io/docs/stryker-net/configuration#use-a-config-file
https://stryker-mutator.io/docs/stryker4s/configuration

### CODE REVIEW

**Review by robertohuertasm — APPROVED** [review]
LGTM 🚀 Thanks for your contribution ❤️

**Comment by nicojs** [comment]
Thank you for letting me contribute our logo! 💕

**Comment by nicojs** [comment]
@robertohuertasm thanks for releasing `v11.9.0`

I don't see my icon, is there any obvious reason why it isn't working? 
image

**Comment by robertohuertasm** [comment]
Let me check it.

**Comment by robertohuertasm** [comment]
I see what's happening. The extensions were published as normal extensions. 

image

The fix is simple. I'll create a PR with it. Thanks for pointing this out!

If those

**Comment by robertohuertasm** [comment]
@nicojs a new release is on its way 😉

**Pull request merged**
