### PR TITLE
Update file_type_nuxt.svg

### PR DESCRIPTION
**Pull request by Atinux**
**Changes proposed:**

- [ ] Add
- [ ] Delete
- [x] Fix
- [ ] Prepare

Update the logo to latest Nuxt logo 😄

### CODE REVIEW

**Comment by JimiC** [comment]
@KingDarBoja Can you please adjust the icon?

**Comment by robertohuertasm** [comment]
I updated the icon with Illustrator.

**Comment by JimiC** [comment]
Great!

**Comment by KingDarBoja** [comment]
I am right now at the office so couldn't fix it at time :cry:

**Comment by JimiC** [comment]
No worries.

**Comment by robertohuertasm** [comment]
Don't worry! I was able to access to Illustrator. 👍

**Pull request merged**
