### PR TITLE
Replace nim dark theme icon

### PR DESCRIPTION
**Pull request by 747**
**Changes proposed:**

- [X] Add
- [ ] Delete
- [X] Fix
- [ ] Prepare

The current Nim icon contains some black texture which obviously has little visibility in a darker background.
I propose to divert it to the light theme and place a new dark theme icon I took from official https://github.com/nim-lang/website repository.

### CODE REVIEW

**Comment by KingDarBoja** [comment]
We have to fix the icon to follow our guidelines.

**Comment by JimiC** [comment]
`Nim` logo now is old gold-ish https://nim-lang.org/
@KingDarBoja Replace it with those colors.

**Comment by KingDarBoja** [comment]
> `Nim` logo now is old gold-ish https://nim-lang.org/
> @KingDarBoja Replace it with those colors. No light version.

I think we should keep the light version as stated on the [nim-lang assets](https://github.com/nim-lang/assets#nim-assets) page.

**Comment by JimiC** [comment]
@KingDarBoja Fair.

**Comment by 747** [comment]
@JimiC Hi, is perhaps your comment suggesting that I should do something? If that's the case, what should I do in particular?

**Comment by KingDarBoja** [comment]
@747 Don't worry, I will make the correction as stated by JimiC :)

**Comment by JimiC** [comment]
@KingDarBoja I though that the current icon (with the black bottom) would be used as a `light` version and the all "gold" for dark themes.

**Comment by KingDarBoja** [comment]
@JimiC thought the same until checking the most recent svg on that assets repo, which display the light and dark version being gold-ish: [logo-design](https://github.com/nim-lang/assets/blob/master/Art/logo-design.svg).

nim-logo

**Comment by JimiC** [comment]
Whatever.

**Pull request merged**
