### PR TITLE
Add support for middleware folder

### PR DESCRIPTION
**Pull request by KingDarBoja**
_**References #650**_

**Changes proposed:**

- [x] Add
- [ ] Delete
- [ ] Fix
- [ ] Prepare

Yesterday, I was working on my own middleware icon, after taking some inspiration on some Google search and ended up with this:

middleware_old

Unfortunately, I felt it wasn't clear about the `middleware` meaning so decided to stick with the common `puzzle` icon.

### CODE REVIEW

**Comment by JimiC** [comment]
As odd as it may sound I like the one in the screenshot.

**Comment by KingDarBoja** [comment]
> As odd as it may sound I like the one in the screenshot.

I will let the svg here just in case: 
```xml
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><title>folder_type_middleware</title><path d="M27.5,5.5H18.2L16.1,9.7H4.4V26.5H29.6V5.5Zm0,4.2H19.3l1.1-2.1h7.1Z" style="fill:#bc5572"/><path d="M18.054,18.5a.843.843,0,1,1-.843-.852A.848.848,0,0,1,18.054,18.5Zm-.843-4.636a.852.852,0,1,0,.843.852A.848.848,0,0,0,17.211,13.864Zm2.791,0h5.692v5.488H20Zm7.068-1.046v8.438H14.93V12.818a.458.458,0,0,1,.45-.454H26.62A.458.458,0,0,1,27.07,12.818ZM18.616,18.5a1.405,1.405,0,1,0-1.405,1.42A1.414,1.414,0,0,0,18.616,18.5Zm0-3.784a1.405,1.405,0,1,0-1.405,1.42A1.415,1.415,0,0,0,18.616,14.716Zm7.64-1.136a.283.283,0,0,0-.281-.285H19.721a.283.283,0,0,0-.281.285v6.056a.283.283,0,0,0,.281.284h6.254a.283.283,0,0,0,.281-.284ZM14.93,24.182a.458.458,0,0,0,.45.454H26.62a.458.458,0,0,0,.45-.454V22.393H14.93Zm2.281-10.318a.852.852,0,1,0,.843.852A.848.848,0,0,0,17.211,13.864Zm2.791,0h5.692v5.488H20Zm7.068-1.046v8.438H14.93V12.818a.458.458,0,0,1,.45-.454H26.62A.458.458,0,0,1,27.07,12.818ZM18.616,18.5a1.405,1.405,0,1,0-1.405,1.42A1.414,1.414,0,0,0,18.616,18.5Zm0-3.784a1.405,1.405,0,1,0-1.405,1.42A1.415,1.415,0,0,0,18.616,14.716Zm7.64-1.136a.283.283,0,0,0-.281-.285H19.721a.283.283,0,0,0-.281.285v6.056a.283.283,0,0,0,.281.284h6.254a.283.283,0,0,0,.281-.284ZM14.93,24.182a.458.458,0,0,0,.45.454H26.62a.458.458,0,0,0,.45-.454V22.393H14.93Z" style="fill:#f4f4f4"/><path d="M17.211,16.136a1.421,1.421,0,1,0-1.4-1.42A1.415,1.415,0,0,0,17.211,16.136Zm0-2.272a.852.852,0,1,1-.843.852A.848.848,0,0,1,17.211,13.864Zm0,6.056a1.42,1.42,0,1,0-1.4-1.42A1.415,1.415,0,0,0,17.211,19.92Zm0-2.272a.852.852,0,1,1-.843.852A.848.848,0,0,1,17.211,17.648Zm2.51,2.272h6.254a.283.283,0,0,0,.281-.284V13.58a.283.283,0,0,0-.281-.285H19.721a.283.283,0,0,0-.281.285v6.056A.283.283,0,0,0,19.721,19.92ZM20,13.864h5.692v5.488H20ZM30.555,28.5H22.972a2.039,2.039,0,0,0-1.41-1.513V26H26.62a1.811,1.811,0,0,0,1.8-1.818V12.818A1.811,1.811,0,0,0,26.62,11H15.38a1.811,1.811,0,0,0-1.8,1.818V24.182A1.811,1.811,0,0,0,15.38,26h5.058v.991a2.039,2.039,0,0,0-1.41,1.513H11.445a.451.451,0,0,0,0,.9h7.583a2.017,2.017,0,0,0,3.944,0h7.583a.451.451,0,0,0,0-.9ZM15.38,12.364H26.62a.458.458,0,0,1,.45.454v8.438H14.93V12.818A.458.458,0,0,1,15.38,12.364Zm-.45,11.818v-1.79H27.07v1.79a.458.458,0,0,1-.45.454H15.38A.458.458,0,0,1,14.93,24.182ZM21,30.091a1.137,1.137,0,1,1,1.124-1.136A1.13,1.13,0,0,1,21,30.091Z" style="fill:#ff0844"/></svg>
```

**Comment by JimiC** [comment]
I vote to switch to that one.

**Comment by JimiC** [comment]
The puzzle icon is already used for the `plugin` folder.

**Comment by KingDarBoja** [comment]
Argh! Wasn't aware of the puzzle icon being used for another folder.

Anyway, reverted the icon to the old one. 👍

**Pull request merged**
