### PR TITLE
chore(11.1.0): prepare new release

### PR DESCRIPTION
**Pull request by robertohuertasm**
Ready to do the first release of the year!

### CODE REVIEW

**Comment by carlocorradini** [comment]
I can't wait for this new version to be available 🎉🎉🎉

**Comment by robertohuertasm** [comment]
Hopefully we'll have it during the day! Thanks for your contribution @carlocorradini!

**Comment by robertohuertasm** [comment]
Travis new policies hit us... It's definitely time to consider alternatives

image

**Comment by robertohuertasm** [comment]
@vscode-icons/development I think we'll have to do a manual release this time. @JimiC did you ever started the GitHub actions migration? If you started with that I can take your work where you left it in case you're too busy.

**Comment by carlocorradini** [comment]
> @vscode-icons/development I think we'll have to do a manual release this time. @JimiC did you ever started the GitHub actions migration? If you started with that I can take your work where you left it in case you're too busy.

Noooooooooooooooooooooooooooo 😢😢😢😢😢

2020 (1) strikes again 😂

**Comment by robertohuertasm** [comment]
I've sent an email to Travis support to see if we can get more extra minutes. If not, I'll go for a classic manual release for this one and start working on the GitHub actions migration.

**Comment by robertohuertasm** [comment]
Ok. I'm going to do a manual release for this. I have some time now and I'm not sure when I'll have it again so...

**Comment by robertohuertasm** [comment]
**Extension released: ok**
image

**Icon wiki: ok**
image

**Docker images: ok**
image

**Comment by robertohuertasm** [comment]
Just for the sake of having all the information here. I received an email from Travis yesterday and they seem to be willing to provide us free minutes. I'm still in conversations. I'll keep you posted.

**Comment by KingDarBoja** [comment]
GitHub Actions migration shouldn't be hard to do, however I remember @JimiC saying that it was lacking some nodejs support at the Slack channel, but can't remember exactly the issue.

**Pull request merged**
