### PR TITLE
feat(icon): add WDIO icon

### PR DESCRIPTION
**Pull request by AnthonyQuy**
_**Fixes #IssueNumber**_

**Changes proposed:**

- [x] Add
- [ ] Delete
- [ ] Fix
- [ ] Prepare

### CODE REVIEW

**Review by iFreilicht — CHANGES_REQUESTED** [review]
Your icon does not follow [the guidelines](https://github.com/vscode-icons/vscode-icons/wiki/Contributing). It is not scaled to 32x32 pixels and does not have a 2 pixel margin around the outside.

**Comment by AnthonyQuy** [comment]
> Your icon does not follow [the guidelines](https://github.com/vscode-icons/vscode-icons/wiki/Contributing). It does not have a 2 pixel margin around the outside.

Thanks for pointing out, updated!

**Review by robertohuertasm — APPROVED** [review]
LGTM 🚀 Thanks for your contribution ❤️

**Comment by christian-bromann** [comment]
Thanks @AnthonyQuy and @robertohuertasm

**Pull request merged**
