### PR TITLE
Add support for Rego Policies

### PR DESCRIPTION
**Pull request by leefaus**
Adding support for Open Policy Agent (OPA) file types.

image

_**Fixes #IssueNumber**_
No Issue at this time

**Changes proposed:**

- [X] Add
- [ ] Delete
- [ ] Fix
- [ ] Prepare

### CODE REVIEW

**Comment by JimiC** [comment]
Please open an issue and reference it to the OP. Thanks,

**Comment by KingDarBoja** [comment]
Seems to be based on this extension: https://marketplace.visualstudio.com/items?itemName=tsandall.opa

**Comment by robertohuertasm** [comment]
The svg should be optimized according to our procedures before merging this.

**Review by robertohuertasm — APPROVED** [review]
Thanks for this PR

**Pull request merged**
