### PR TITLE
feat(icon): add icons for libreoffice

### LINKED ISSUE #2558: [Icon Request] Support for Open Document Format for Presentation (Libreoffice Impress)
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `extension`
  - Icon Name: `Open Document Format for Presentation`
  - Sample original Icon:
odp

  - Extensions: `odp`, `otp`

- More info:  `odp` are ODF alternatives of `pptx`/`ppt` files

### LINKED ISSUE #2559: [Icon Request] Support for Open Document Format for Text-document (Libreoffice Write)
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `extension`
  - Icon Name: `Open Document Format for Text-Document`
  - Sample original Icon: 
odt

  - Extensions: `odt`, `ott` (template file)

- More info:  `odt` are ODF alternatives of `docx`/`doc` files

### LINKED ISSUE #2560: [Icon Request] Support for Open Document Format for Sheet (Libreoffice Calc)
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `extension`
  - Icon Name: `Open Document Format for Sheets`
  - Sample original Icon: 
ods

  - Extensions: `ods`, `ots`

- More info:  `ods` is ODF alternatives of `xslx`/`xsl` files

### PR DESCRIPTION
**Pull request by remcohaszing**
The LibreOffice icons are applied to each matching open document file extension.

_**Fixes #2558**_  
_**Fixes #2559**_  
_**Fixes #2560**_

**Changes proposed:**

- [x] Add
- [ ] Delete
- [ ] Fix
- [ ] Prepare

### CODE REVIEW

**Review by robertohuertasm — CHANGES_REQUESTED** [review]
Some icons are huge (up to 10Kb). We should try to minimize them somehow. Our guidelines speak about 2Kb. We can relax that sometimes, especially if the icon is going to be applied to a few files in a code base (a configuration file, for example).

**Comment by remcohaszing** [comment]
There are quite a lot of subtle gradients. Replacing those with solid colors should make quite a difference.

I can't do this right now though. It's going to be somewhere next week.

**Comment by robertohuertasm** [comment]
Ok @remcohaszing! There's no rush. Take the time it needs. This PR is fantastic!

**Comment by remcohaszing** [comment]
I managed to significantly reduce the original file sizes, but some still exceed the guidelines for the size limit.

**Review by robertohuertasm — APPROVED** [review]
LGTM 🚀Great work on this one.

**Pull request merged**
