### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by JimiC**

### CODE REVIEW

**Comment by JimiC** [comment]
@robertohuertasm Think is I didn't make any changes to the translations. This PR was auto-generated by `Crowdin`. Although it seems correct I propose we test it against any parsing code errors, just to be on the safe side.

**Comment by robertohuertasm** [comment]
It seems to work in French, so I'll assume this works also for Italian and Japanese:
image

**Comment by robertohuertasm** [comment]
Italian:
image

**Comment by JimiC** [comment]
I'm relieved.

**Pull request merged**
