### PR TITLE
Add support for Gradle folder

### PR DESCRIPTION
**Pull request by KingDarBoja**
**Changes proposed:**

- [x] Add
- [ ] Delete
- [ ] Fix
- [ ] Prepare

### CODE REVIEW

**Comment by robertohuertasm** [comment]
@KingDarBoja I guess you've tested it but I'm wondering that giving that the folder color is light, the same icon may work both for light and dark themes. I'm referring to the light one with the elephant in dark green.

**Comment by KingDarBoja** [comment]
> @KingDarBoja I guess you've tested it but I'm wondering that giving that the folder color is light, the same icon may work both for light and dark themes. I'm referring to the light one with the elephant in dark green.

I just want to avoid some elephant parts not being seen on dark themes, like the paws for example.

I will give a try and post a screen of how it looks.

Cheers!

**Comment by KingDarBoja** [comment]
@robertohuertasm I am still not confident about how the dark gradle logo looks on dark themes even with the light folder as shown below:

Gradle folder dark theme

**Comment by JimiC** [comment]
Use the light version of the elephant

**Pull request merged**
