### PR TITLE
Add Org Mode icon support

### PR DESCRIPTION
**Pull request by zacherybohon**
This pull request adds support for the org icon (unicorn) for `*.org` files.

References:
* http://orgmode.org/
* https://github.com/jsonreeder/vscode-org-mode

### CODE REVIEW

**Comment by JimiC** [comment]
Ensure that the icon is of size 32x32 with a 2px margin.

**Comment by zacherybohon** [comment]
@JimiC, I'll take care of that and revise tonight.

**Comment by zacherybohon** [comment]
@JimiC, I ran into some issues with getting SVG to work correctly (I don't have access to photoshop), and so I've swapped it out for a png instead. Is that acceptable?

**Comment by JimiC** [comment]
No worries. We'll do it for you.

**Comment by JimiC** [comment]
@zacherybohon Please rebase your changes on a branch other than `master`.

**Comment by JimiC** [comment]
@zacherybohon So here what I need from you.
1. Revert the changes you made and re-support SVG.
2. Move changes to a branch other than `master`.
3. Squash all commits into one.

I have generated the SVG icon to comply with our art guidelines. Once you've done the above I'll commit the icon on that branch.

Changing branch will require that you close this PR and create another.

**Comment by robertohuertasm** [comment]
@JimiC I've already pushed to his master and the change is here in the PR. If it's ok for you I'll merge it.

**Comment by JimiC** [comment]
I don't want to sound like a prick but the proper way to submit a PR is from a branch other than `master`. Never the less...

**Comment by JimiC** [comment]
@robertohuertasm Just FYI here is the setting.

>Require status checks to pass before merging
Choose which status checks must pass before branches can be merged into master. When enabled, commits must first be pushed to another branch, then merged or pushed directly to master after status checks have passed.

If it's enabled then there must be some kind of bug in the GitHub flow.

**Comment by robertohuertasm** [comment]
@JimiC, we have not pushed directly to our master and his master is, indeed, a foreign branch. The Github check basically assures that you cannot force push, that before merging some checks are passed and that you cannot delete the branch. This can be applied to master or to whatever other branch you have in your repo.

There's no restriction regarding the foreign branch (the one bringing the PR changes). It can be named with whatever name you want. The changes happening in @zacherybohon's master are only there, not in our master, so... nothing to worry about about how we merge things. The status checks are still in place and working as expected. As you said:

> When enabled, commits must first be pushed to another branch, then merged or pushed directly to master after status checks have passed.

And that's exactly what I've done. Commits were pushed to another branch `zacherybohon/master` and then merged into our `master` (which is the part of the process that still lefts to accomplish).

Hope it's clearer now. 😉

**Comment by robertohuertasm** [comment]
In case you wonder how the protection settings are set:

image

**Comment by JimiC** [comment]
That figures, but still, I prefer a cleaner branching flow. But that's just me.

**Comment by JimiC** [comment]
@robertohuertasm Apparently you miss ticked the checkboxes when checking the settings.
`appveyor` CI should be `Required` too.

**Comment by robertohuertasm** [comment]
Done!

**Pull request merged**
