### PR TITLE
Improve AppVeyor config

### PR DESCRIPTION
**Pull request by JimiC**
Simplified how `AppVeyor` installs latest `Yarn` version.

### CODE REVIEW

**Comment by jens1o** [comment]
sorry, wrong button has been clicked

**Comment by JimiC** [comment]
@jens1o Indeed. I like `bash` better. And to think that `Microsoft` is hoping users to switch from `bash` to `powershell` on `linux`. What a joke.

**Comment by JimiC** [comment]
This is temp until `Yarn` team agrees to accept the script and make it available from their website.

P.S.: Btw, @jens1o thanks for the vote of trust.

**Comment by jens1o** [comment]
> P.S.: Btw, @jens1o thanks for the vote of trust.

It's not like I don't trust you(you are doing awesome things for this project), but in my point of view anything related to this project should lay in the vscode-icons organization namespace.

**Comment by JimiC** [comment]
Well, it's exactly that. The script is meant to be made public to and used by, the whole community.

**Pull request merged**
