### PR TITLE
Add support for AsciiDoc

### LINKED ISSUE #2122: [Icon Request] Support for AsciiDoc
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `File`
  - Icon Name: `AsciiDoc`
  - Sample original Icon: logo It seems it doesn't have a proper icon and some people are using the one from [AsciiDoctor](https://github.com/asciidoctor/asciidoctor/issues/48#issuecomment-342081882)
  - Language ids: `asciidoc` see [here](https://github.com/asciidoctor/asciidoctor-vscode/blob/master/package.json#L44)

### PR DESCRIPTION
**Pull request by KingDarBoja**
_**Fixes #2122**_

**Changes proposed:**

- [x] Add
- [ ] Delete
- [ ] Fix
- [ ] Prepare

### CODE REVIEW

**Comment by JimiC** [comment]
No offence, but I don't like the square version.

**Comment by KingDarBoja** [comment]
> No offence, but I don't like the square version.

I wasn't sure which version to pick, if @robertohuertasm do rather prefer the rounded square one, I will make the changes 👍

**Comment by robertohuertasm** [comment]
Hey, I don't really have a preference. I'm ok with the square one, too. We already have similar square icons with plain colors: `JavaScript official`, `TypeScript official`...  Whatever you want, I'm ok with it.

**Comment by robertohuertasm** [comment]
@JimiC, it seems that you're the only one with some concerns about this icon. I don't have a strong preference so I don't really care if we made this one or the one with rounded corners available. The thing is that I don't have now access to Illustrator so I can't make the change even if I wanted to.

How do you want to proceed? We merge this in order to deploy v9 and we'll revisit this in the future? or we wait to merge it until we have rounded corners?

**Comment by JimiC** [comment]
No strong opinion. You may proceed.

**Pull request merged**
