### PR TITLE
feat : add support of .hypr & .hypr.live files

### PR DESCRIPTION
**Pull request by Temu4**
**Changes proposed:**

- [x] Add
- [ ] Fix
- [ ] Prepare
- [ ] Delete

Hi!
Can you please add support of the `.hypr` and `.hypr.live` files. They are used in [Kibo E-commerce platform](https://kibocommerce.com/).
Thanks in advance!

### CODE REVIEW

**Comment by KingDarBoja** [comment]
Hi @Temu4 

Can you provide a specific link on Kibo Documentation where these files are mentioned? Thanks!

Also these icons need a bit of fixing, I can do that right after verifying being mentioned by Kibo docs.

**Comment by Temu4** [comment]
Hey @KingDarBoja 
Yes, sure - [Kibo Themes syntax](https://www.mozu.com/docs/developer/themes/reference.htm)
If you need more info, please pink me 😄

**Comment by Temu4** [comment]
Hi @KingDarBoja! 
Do you need any more info?

**Review by Cl3r1k — APPROVED** [review]
Looks good

**Review by Cl3r1k — COMMENTED** [review]
Completed review

**Comment by KingDarBoja** [comment]
Sorry for the delay, was off this weekend, I will take a look at the urls you shared and also the PR to see if everything is okay according to guidelines.

Cheers!

**Comment by KingDarBoja** [comment]
Had to dig a bit more in order to understand why the extension was needed as Hyper is a terminal itself.

Anyway, found a vscode-syntax extension for that: https://marketplace.visualstudio.com/items?itemName=temu4.hypr-syntax

**Review by KingDarBoja — APPROVED** [review]

**Comment by Temu4** [comment]
Hey @KingDarBoja ! 

Thanks for your time! Just to be clear not `Hyper`, but `Hypr` (without `e`).

**Comment by KingDarBoja** [comment]
> Hey @KingDarBoja !
> 
> Thanks for your time! Just to be clear not `Hyper`, but `Hypr` (without `e`).

Yeah but Google results weren't clear about it and instead showed the Hyper terminal. At the end, managed to find the extension and also understand how it is used 🚀

**Review by robertohuertasm — APPROVED** [review]
Great work @KingDarBoja! 👍🏻

**Comment by robertohuertasm** [comment]
Also thanks for your contribution and work @Temu4!

**Comment by Temu4** [comment]
Thanks you too for cool extension!

**Pull request merged**
