### PR TITLE
feat(icon): add bun icons

### PR DESCRIPTION
**Pull request by Snazzah**
Adds icons for [Bun](https://bun.sh) including `.bun` and `.lockb` files and `bunfig.toml`.

**Changes proposed:**

- [x] Add
- [ ] Delete
- [ ] Fix
- [ ] Prepare

### CODE REVIEW

**Comment by sasial-dev** [comment]
I wonder if `lockb` should use the `bunfig` icon?

**Comment by robertohuertasm** [comment]
@sasial-dev I guess `lockb` may be similiar to `package-lock-json` according to the docs. If that's the case, then the usage of the icons would be the same as we have for `npm`. WDYT @Snazzah?

**Comment by Snazzah** [comment]
@robertohuertasm Yep, the default name for Bun's lock file is `bun.lockb` and is pretty much like `package-lock.json` and `yarn.lock` but in a different format.

**Review by robertohuertasm — APPROVED** [review]
LGTM 🚀 Thanks for your contribution ❤️

**Pull request merged**
