### PR TITLE
Add support for cli folder

### LINKED ISSUE #650: [Request] Specific folder icons
### We are keeping here a list of requested folder icons.
We are going to update this list as we go along adding icons.

Before requesting a folder icon make sure to check out the already [supported folder list](https://github.com/vscode-icons/vscode-icons/wiki/ListOfFolders).

**Any new requests SHOULD be submitted via comments on this issue and we'll update the list accordingly.**

- [ ] arangodb
- [ ] cmake
- [ ] console, cli, commandline
- [ ] controllers
- [ ] data
- [ ] enum
- [ ] environments
- [ ] gulp
- [ ] graphql
- [ ] grunt
- [ ] minikube
- [ ] `__mocks__`, mocks
- [ ] polyfills
- [ ] resources
- [ ] serializers
- [ ] services
- [ ] shared, common, core

### Debatable
`Debatable` are folder names that are debatable on whether we should provide a specific icon.

- [ ] vendor

### PR DESCRIPTION
**Pull request by KingDarBoja**
_**References #650**_

**Changes proposed:**

- [x] Add
- [ ] Delete
- [ ] Fix
- [ ] Prepare

The opened folder color isn't fitting for dark theme, so any suggestion or changes are welcome.
By the way, I based my work on [Angular Presskit](https://angular.io/presskit#cli) page.

### CODE REVIEW

**Comment by JimiC** [comment]
Personally, I would have used our [shell](https://github.com/vscode-icons/vscode-icons/wiki/ListOfFiles#shell) icon for the overlay. And I would add `commands` also to the namings.

**Comment by JimiC** [comment]
I decided to go with your icons. I like how they look in the editor. I just added the extra namings I proposed just to not keep @robertohuertasm waiting in case he wants to merge the PR.

**Comment by JimiC** [comment]
Spoke too soon. They are not visible in dark themes.

**Comment by JimiC** [comment]
image

**Comment by KingDarBoja** [comment]
Well, I couldn't find the shell icon on the wikia (because was searching by `command` instead) so decided to use a different one, but glad the one you made looks great too 😄

**Comment by JimiC** [comment]
Some times we have to bend the rules as you too have mentioned occasionally. I chose those colors because they contrast better since the overlaying icon has a yellow filling color.
That said feel free to do any changes. Right now it's impossible for me to do any changes.
Bottom line, leave it out of this release and we'll iterate on it later.

**Comment by JimiC** [comment]
The `typings` folder colors are also a good choice.

**Comment by robertohuertasm** [comment]
Never mind, I've tested it in the real editor and it looked nice! I tested other alternatives but I think I kind of like the current proposal in the end. Gooood job!

**Pull request merged**
