### PR TITLE
Merge travis matrix and jobs

### PR DESCRIPTION
**Pull request by JimiC**
Attempting to merge `travis` matrix with jobs. Hopefully, this will reinstate the generation of the wiki pages and the `docker` images.

### CODE REVIEW

**Comment by JimiC** [comment]
@robertohuertasm Could we merge this to see if things resume building?

**Comment by robertohuertasm** [comment]
I will change again the flag in travis to use the new beta validation then, which was the one causing all this issue. I'll let you know once it's done. Thanks for the quick fix.

**Comment by robertohuertasm** [comment]
I've changed the setting but I'm afraid we will have to wait for our next release to see if this works. Anyway, knowing what it is, I think it will be easy to fix on the spot if this hits us again.

**Comment by JimiC** [comment]
We don't need to wait for the next release. Wiki pages and `docker` images are generated every time we push to `master`.

**Comment by robertohuertasm** [comment]
I meant for the `publish` workflow, which was failing yesterday.

**Comment by JimiC** [comment]
It was `travis` messing up. Publish workflow should be operating as normal.

**Comment by JimiC** [comment]
What is bothering me is why the wiki pages and `docker` images generation have stopped.

**Comment by robertohuertasm** [comment]
It was the same issue that was affecting the publish pipeline. All jobs were ignored.

**Comment by robertohuertasm** [comment]
So we can assume that if by merging this, wiki and docker pipelines resume, the publish workflow will also work.

**Comment by JimiC** [comment]
Yes.

**Comment by JimiC** [comment]
There you go, wiki pages and `docker` images generation stages are showing again.

**Comment by robertohuertasm** [comment]
Perfect! We're `build config validation` proof! Thanks for this PR.

**Pull request merged**
