### PR TITLE
fix(vscode): use same version of the vscode engine to make vsce happy

### PR DESCRIPTION
**Pull request by robertohuertasm**
vsce fails: 

image

- [ ] Add
- [ ] Delete
- [x] Fix
- [ ] Prepare

### CODE REVIEW

**Comment by JimiC** [comment]
You should have changed the `vsce` version. Engine version indicates the minimum supported `vscode` version. Now it's all messed up.

**Comment by JimiC** [comment]
Just to be clear I'm not putting any blame here.

**Comment by robertohuertasm** [comment]
I tried to downgrade the @types lib to `1.26.1` but it didn't work so I upgraded the engine accordingly. What's the impact of this beyond not supporting old versions of vscode? Let's fix this and make a patch release.

**Comment by JimiC** [comment]
Yeah, my bad for not seeing this earlier. `@types/vscode` has no version for `1.26.1` but for `1.26.0`. I'm working on it as we speak.

**Comment by robertohuertasm** [comment]
Just to understand this, I'm seeing people reporting issues with versions greater than 1.36.0.

**Comment by JimiC** [comment]
That's a totally different issue. I will address it shortly.

**Pull request merged**
