### PR TITLE
fix(protobuf) use correct Protobuf icon, adds Buf

### PR DESCRIPTION
**Pull request by dimitropoulos**
_**Fixes #IssueNumber**_

**Changes proposed:**

- [x] Add
- [ ] Delete
- [x] Fix
- [ ] Prepare

I noticed that the icon for protobuf files (e.g. `api.proto`) was actually for a protobuf implementation library, [protobuf.js](https://buf.build/), and not the one used for [protobuf itself](https://www.google.com/search?q=protocol+buffers+icon&tbm=isch&ved=2ahUKEwiX5LyYqdL9AhV-STABHTPnB4sQ2-cCegQIABAA&oq=protocol+buffers+icon&gs_lcp=CgNpbWcQAzIFCAAQgAQ6BAgjECc6BwgAELEDEEM6CwgAEIAEELEDEIMBOgQIABBDOggIABCABBCxAzoGCAAQBxAeOggIABAFEAcQHlC8B1jEF2CkGGgAcAB4AIABbYgBvQ2SAQQxNC40mAEAoAEBqgELZ3dzLXdpei1pbWfAAQE&sclient=img&ei=NKMLZJf6G_6SwbkPs86f2Ag&bih=736&biw=1463#imgrc=ejuOyQ4H-_cAAM).  I updated that in the first commit.

While I was here I noticed that there was no icon for [Buf](https://buf.build/) (a protobuf tool) configs, so I added those.

### CODE REVIEW

**Review by fyockm — APPROVED** [review]

**Comment by robertohuertasm** [comment]
@dimitropoulos thanks for this PR. I think we chose that one because we didn't find any official `protobuf` icon. I've looked into the official website and there's not any logo. In any case, given that the icon you propose is being used in several places, I guess it makes sense.

**Comment by dimitropoulos** [comment]
thanks for taking a look @robertohuertasm.  Indeed, that's the closest thing to a "protobuf logo" that exists.

I'm not quite clear on why the CI is failing now after merging from master.  any suggestions?

**Comment by robertohuertasm** [comment]
There's a typo in the `buf` filename. It should be `icons/file_type.buf.svg` instead of `icons/file_type.buf.svg`

**Comment by dimitropoulos** [comment]
@robertohuertasm I updated the file name

**Review by robertohuertasm — APPROVED** [review]
I slightly modified the buf icon to comply with our guidelines.

LGTM 🚀 Thanks for your contribution ❤️

**Comment by dimitropoulos** [comment]
thanks @robertohuertasm!

**Pull request merged**
