### PR TITLE
Add prettier to keep a uniform format in our code

### PR DESCRIPTION
**Pull request by robertohuertasm**
I added a precommit hook so `prettier` is automatically applied to all staged files before pushing any code. By doing this we don't have to care anymore about code format.

I've also applied `prettier` to our current `*.ts` files.

### CODE REVIEW

**Comment by JimiC** [comment]
Not a fan of `Prettier`. Creates more issues than it solves.

**Comment by robertohuertasm** [comment]
Why do you say so? I've been using a lot this last year and I haven't found any issue.

**Comment by JimiC** [comment]
Tried to use it and my experience was negative. But I don't object in using it if this is what you prefer,

**Comment by robertohuertasm** [comment]
I would encourage you to use it and give it a try again! 😉 Let's try it. If it presents an issue I will be the first to remove it.

**Comment by JimiC** [comment]
Also, these lines (https://github.com/vscode-icons/vscode-icons/blob/master/.editorconfig#L19-L21) can be removed as `vsce` now uses `npm version` when updating the `package.json` (which preserves the used indentation).

**Pull request merged**
