### PR TITLE
added support for zh-CN

### LINKED ISSUE #526: [Task] Provide messages in available VSCode languages
- [x] I'm sure this issue is not a *duplicate*?

I know this was experimented on at some point but I think it will add value to this extension.

VSCode available languages:

- [x] English (US)	[en]
- [x] Simplified Chinese [zh-CN]
- [ ] Traditional Chinese [zh-TW]
- [x] French	[fr]
- [x] German	[de]
- [x] Italian	[it]
- [x] Japanese [ja]
- [ ] Korean	[ko]
- [x] Russian	[ru]
- [x] Spanish [es]

### PR DESCRIPTION
**Pull request by iFun**
***Reference #526***
**Changes proposed:**
* [x] Add
* [ ] Prepare
* [ ] Delete
* [ ] Fix

**Things I've done:**
* [x] My pull request fixes an issue, I referenced the issue.

let me know if there is any changes needed in this pr

### CODE REVIEW

**Comment by iFun** [comment]
I had to remove the double quotation for zh-CN in the langResourceCollection.ts file otherwise it gives me an error. is there a better way to do it?

**Comment by JimiC** [comment]
@iFun I fixed the issues for you. One question though isn't the `period` punctuation mark (.) used in Chinese?

**Comment by iFun** [comment]
@JimiC period in Chinese is “。” which is ugly and usually not in use. So if there is only one sentence the common practice is to avoid using “。”. “。” is only be used in long paragraph where sentence separation is necessary such as README.

**Comment by JimiC** [comment]
@iFun That's what I read when searching about punctuation marks usage in the Chinese language, but thought to ask to be sure. Thanks for the info.

**Pull request merged**
