### PR TITLE
Add Support for Include

### LINKED ISSUE #2216: [Icon Request] INC file
- [ X] I'm sure this issue is not a _duplicate_.
- [ X] I'm submitting an icon request:
  - Type: `INC`
  - Icon Name: `file_type_inc.svg`
  - Sample original Icon: "INC" (like ASP in dark color?)
file_type_inc
  - Extensions: `.inc`
  - Filenames: `*`
  - Language ids: interpreted as ASP/ text-file

- Language Extensions: .inc
- More info: this kind of files are used in Classic ASP for including external resource

### PR DESCRIPTION
**Pull request by KingDarBoja**
_**Fixes #2216**_

**Changes proposed:**

- [x] Add
- [ ] Delete
- [ ] Fix
- [ ] Prepare

This PR also makes pixel perfect the default file icon.

### CODE REVIEW

**Comment by JimiC** [comment]
Why is the default file changed?

**Comment by KingDarBoja** [comment]
> Why is the default file changed?

Just made it pixel perfect, it is a slighty change.

**Comment by JimiC** [comment]
Those changes better be addressed in a separate PR.

**Comment by KingDarBoja** [comment]
> Those changes better be addressed in a separate PR.

Okie dokie mate, just wanted to kill two birds in one shot because the `include` icon at the folder one was non-uniform with the existing default icon. So to keep everything at the same size and making those pixel perfect, I decided to put them together in this PR.

**Comment by JimiC** [comment]
I'm in favor of keeping the solid color of the background.

**Comment by KingDarBoja** [comment]
> I'm in favor of keeping the solid color of the background.

I do prefer keeping it transparent as the default file icon does for the same reason as stated above (uniformity).

@robertohuertasm @jens1o  Any thoughts about it?

**Comment by JimiC** [comment]
If you keep it like the `default file` icon the eye can be fooled in thinking it's the default file icon.

**Comment by JimiC** [comment]
Just for the record I still don't like it as it is.

**Comment by robertohuertasm** [comment]
For the record, this was an unintended merge. Something got weird with GitHub. I pressed `update branch` and somehow it got merged. I would have liked to solve this disagreement before merging it.

**Comment by robertohuertasm** [comment]
We can iterate through this again.

**Comment by JimiC** [comment]
Basically, we were waiting for your input as Jens approved it.

**Comment by robertohuertasm** [comment]
I don't have a strong opinion about this one. It's good enough for me but if someone comes up with a version that raises more consensus I'm fine with it, of course. Taking a look at the file tree it doesn't look that bad but you have a valid point.

image

**Comment by JimiC** [comment]
Giving it a background you are contrasting the arrow further which makes it even more distinguishable,

**Comment by JimiC** [comment]
Try it on a light theme.

**Comment by KingDarBoja** [comment]
> Try it on a light theme.

I just tried it and you are right, it is harder to recognize it at light themes, even with the arrow due to the gray color used.

Due to that, I have changed my mind and will be giving it a dark background as stated by @JimiC. However, looks like this PR got merged by accident so not sure how to proceed, just push the changes and merge again?

**Comment by JimiC** [comment]
Open new PR

**Pull request merged**
