### PR TITLE
chore: remove the language collection types

### PR DESCRIPTION
**Pull request by remcohaszing**
Thanks to the TypeScript `satisfies` operator, keys from `languages` can be accessed in a type-safe manner, without the need for the `ILanguageCollection` and `INativeLanguageCollection` types. This saves the need to track the languages in multiple places.

This will cause merge conflicts with existing pull requests that register a new language. I recommend to merge this last before making a new release, so only one merge conflict needs to be resolved.

### CODE REVIEW

**Comment by robertohuertasm** [comment]
@remcohaszing thanks for this! It's an improvement for new contributors! I'll approve and merge according to your recommendation.

**Comment by robertohuertasm** [comment]
@remcohaszing can you resolve the conflicts? Thanks!

**Comment by remcohaszing** [comment]
I rebased it.

**Review by robertohuertasm — APPROVED** [review]
LGTM 🚀

**Pull request merged**
