### PR TITLE
Added horusec-config file icon

### PR DESCRIPTION
**Pull request by lucasbrunozup**
**Changes proposed:**

- [X] Add
- [ ] Delete
- [ ] Fix
- [ ] Prepare

Icon for configuration of [Horusec](https://horusec.io/docs/overview/), this an open source tool that orchestrates other security tools and identifies security flaws or vulnerabilities in projects and put all results in a database for analysis and generation of metrics.

### CODE REVIEW

**Review by wiliansilvazup — APPROVED** [review]

**Comment by robertohuertasm** [comment]
@lucasbrunozup I tried to optimize it according to our guidelines but for some reason I can't use it in illustrator. It seems that it doesn't recognize de vector paths. @KingDarBoja can you take a look at it to see if it's something related to my illustrator version? Once this is solved we can merge it.

**Comment by lucasbrunozup** [comment]
> @lucasbrunozup I tried to optimize it according to our guidelines but for some reason I can't use it in illustrator. It seems that it doesn't recognize de vector paths. @KingDarBoja can you take a look at it to see if it's something related to my illustrator version? Once this is solved we can merge it.

I used figma to create it, maybe that's why.
What specifically are the adjustments that need to be made? I fix it, I send it again.

**Comment by KingDarBoja** [comment]
> > @lucasbrunozup I tried to optimize it according to our guidelines but for some reason I can't use it in illustrator. It seems that it doesn't recognize de vector paths. @KingDarBoja can you take a look at it to see if it's something related to my illustrator version? Once this is solved we can merge it.
> 
> I used figma to create it, maybe that's why.
> What specifically are the adjustments that need to be made? I fix it, I send it again.

We are using the following settings at Illustrator: https://github.com/vscode-icons/vscode-icons/wiki/Contributing
It is missing the title and since the icon is smaller, I don't think we need a gradient but rather plain colours.

**Comment by lucasbrunozup** [comment]
> > > @lucasbrunozup I tried to optimize it according to our guidelines but for some reason I can't use it in illustrator. It seems that it doesn't recognize de vector paths. @KingDarBoja can you take a look at it to see if it's something related to my illustrator version? Once this is solved we can merge it.
> > 
> > 
> > I used figma to create it, maybe that's why.
> > What specifically are the adjustments that need to be made? I fix it, I send it again.
> 
> We are using the following settings at Illustrator: https://github.com/vscode-icons/vscode-icons/wiki/Contributing
> It is missing the title and since the icon is smaller, I don't think we need a gradient but rather plain colours.

I adjusted the size and color of the icon.

**Comment by lucasbrunozup** [comment]
Do we have any more pending issues preventing the merge?

**Comment by KingDarBoja** [comment]
> Do we have any more pending issues preventing the merge?

Nope, just wait a little bit as we as maintainers are a bit busy at the time being for providing a new release 😊

**Review by KingDarBoja — APPROVED** [review]

**Pull request merged**
