### PR TITLE
feat(vscode-test): add vscode-test support

### PR DESCRIPTION
**Pull request by remcohaszing**
This adds the VS Code icon to `.vscode-test.{js,json,mjs}` files. This is the configuration file of the new experimental official command-line for running VS Code tests.

https://github.com/microsoft/vscode-test-cli

_**Fixes N/A**_

**Changes proposed:**

- [x] Add
- [ ] Delete
- [ ] Fix
- [ ] Prepare

### CODE REVIEW

**Comment by robertohuertasm** [comment]
Hi @remcohaszing I'm thinking if the icon for these files should have some sort of test indicator in the icon. Similar to what we have for `.test.ts` or something like that. WSYT?

**Comment by remcohaszing** [comment]
I like that idea. I’m definitely not a designer though. I know how to take existing icons, crop them, minify them, and tweak some simple variables in the SVG, but that’s about it.

**Comment by robertohuertasm** [comment]
No worries. I'll take a look. Thanks for the PR though! 🙌🏻

**Comment by robertohuertasm** [comment]
I'm reviewing the tests... not sure why it's not working.

**Comment by robertohuertasm** [comment]
It seems I may have merged a change in master that breaks the tests. Probably related to the node version.

**Review by robertohuertasm — APPROVED** [review]
LGTM 🚀 Thanks for your contribution ❤️

**Pull request merged**
