### PR TITLE
new logo for log

### PR DESCRIPTION
**Pull request by robertohuertasm**

### CODE REVIEW

**Comment by JimiC** [comment]
`title` still contains the file extension.

**Comment by robertohuertasm** [comment]
Check it now.

**Comment by JimiC** [comment]
Still there `<title>file_type_log.svg</title>`

**Comment by JimiC** [comment]
And I notice you use `stroke`. It would be better if you outline the strokes.
`Object > Path > Outline Stroke`.

**Comment by robertohuertasm** [comment]
What's the impact of using strokes vs outlining?

**Comment by JimiC** [comment]
Se previous comment. I updated it.

**Pull request merged**
