### PR TITLE
New Crowdin translations

### PR DESCRIPTION
**Pull request by robertohuertasm**
Enjoy!

### CODE REVIEW

**Comment by JimiC** [comment]
@robertohuertasm Do not merge until we have the translations for `lang.ja.json`.

**Comment by robertohuertasm** [comment]
@JimiC, do you mean this japanase translations are not correct?

**Comment by JimiC** [comment]
No, they are but they are of  `package.nls.json`. We lack the translations of `lang.en.json`. We don't want to ship half the translations, do we?

**Comment by robertohuertasm** [comment]
I didn't pay attention to the name of the file :wink: Let's wait then.

**Comment by jens1o** [comment]
When someone approves my translation, they could be merged, too.

**Comment by JimiC** [comment]
Actually we will have to `cherrypick` those commits.

**Comment by jens1o** [comment]
I hate `cherrypicking`. It's like all the times I forgot something.

**Comment by robertohuertasm** [comment]
@jens1o, your translations still have to be validated!

**Comment by robertohuertasm** [comment]
I see the same happens for Chinese. @JimiC, what happens with missing translations? Will they fallback to English? In case they don't, should we provide the English alternative via Crowdin? What's the usual way of action when using this service?

Btw, I'll validate the pending translations as I guess they just forgot to press the button 😉

**Comment by JimiC** [comment]
* Our translation service falls back to `English`. I'm sure what's happening with `nls` as this is a `vscode` service.
* The action in these cases is to `cherrypick` the completed translations.
* The translators don't have the ability to approve translations. This is the maintainers job.

**Comment by JimiC** [comment]
Also if we have translations more than 0% and there are empty translation strings in them, those should be included as they are (empty).

**Comment by JimiC** [comment]
My actions would be to open a new branch, cherrypick the commits I want and then merge that branch to master.

**Comment by JimiC** [comment]
Explaining `nls`: If a command placeholder is present in the default `nls` `json` (en) and that is absent from a translation `nls` (i.e. `es), then pressing `F1 > Icons` the command shows the key (i.e. `%commnad.hideExplorerArrowsPreset.title%` ). I have reported this to the `vscode-nls` but maintainer asked me to report it to `vscode-nls-dev`. Whenever I get some free time I'll get into providing a PR fix for that.

**Comment by JimiC** [comment]
Explaining our `i18n` service. If the key is absent in the translated `json` then we have a problem and the extension crashed. If the string is empty then it falls back to `English`.

Hoping I made it clear on how the translation services work.

**Comment by JimiC** [comment]
So it's absolutely crucial to include at least the key in the `lang.x.json` files.
About `nls` we can't do anything until someone fixes it, at least the fall back to `English` om empty strings.

**Comment by robertohuertasm** [comment]
So, basically, for `lang.xx.json` we don't have any problem if we commit unresolved translations as our system will default to English. On the contrary, due to a bug in vscode, `package.nls.xx.json` files should have all the translations because if they don't have them or they are empty strings the key will be shown.

In our case, that would mean that we cannot release until all the translations for `package.nls.xx.json` are completed.

French (@MonsieurMan) and Russian (@ksvitkovsky) are the ones with missing translations. Gentleman, we would really appreciate your help once more. 😉 

Thanks to @mariotsi, @jens1o and @g-plane for the latest translations! ❤️

**Comment by JimiC** [comment]
Exactly. And that means that we could also release the Japanese translations, but I would like for the `lang.ja.json` to be included too.

**Comment by ksvitkovsky** [comment]
Wow, that's convenient 👏 
Sorry for late reply though, got no notification.

**Pull request closed without merging**
