### PR TITLE
Update vscode icon to new color (blue).

### PR DESCRIPTION
**Pull request by JimiC**
**_Fixes #1287_**

**Changes proposed:**

- [x] Add

**Things I've done:**

- [x] My pull request fixes an issue, I referenced the issue.

### CODE REVIEW

**Comment by robertohuertasm** [comment]
Holding this until next vscode release with the new logo! Great work @JimiC!!

**Comment by JimiC** [comment]
Sure. Not to forget to update also the repo logo on due time.

**Comment by JimiC** [comment]
Did the new `vscode` stable got realized? If so @robertohuertasm please change the repo logo too (you know, the one shown on Github landing page).

**Comment by robertohuertasm** [comment]
Yes, this morning. I'm aware of the logo. I could have use this PR for the logo too but I got excited about it and merged this PR right away! 😁

**Comment by JimiC** [comment]
@robertohuertasm I'm referring to the organization account logo, in case I wasn't clear.

**Comment by robertohuertasm** [comment]
Oh, my bad!

**Comment by robertohuertasm** [comment]
Done!

**Comment by JimiC** [comment]
Np.

**Pull request merged**
