### PR TITLE
Add tmLanguage extensions

### PR DESCRIPTION
**Pull request by Gama11**

### CODE REVIEW

**Comment by robertohuertasm** [comment]
Hi @Gama11, I merged this but then I realized that this shouldn't be marked as an extension. `JSON` is supported via `language id` so you should manage it via `vscode` file associations. I removed it in #712 revision.

**Comment by JimiC** [comment]
@robertohuertasm Can you please revert all `tmLanguage` addition? This is not the correct way to support them.

**Comment by robertohuertasm** [comment]
I reverted it in #712

**Comment by JimiC** [comment]
Not all.

**Comment by robertohuertasm** [comment]
I see...

**Comment by JimiC** [comment]
https://github.com/vscode-icons/vscode-icons/blob/master/src/icon-manifest/supportedExtensions.ts#L355

https://github.com/vscode-icons/vscode-icons/blob/master/src/icon-manifest/supportedExtensions.ts#L357

**Comment by Gama11** [comment]
@robertohuertasm I don't think that works for me, since I'm using the vscode-tmLanguage extension. It registers these as separate languages to get proper highlighting (specific to the tmLanguage format, regexes etc) for them: https://github.com/Togusa09/vscode-tmlanguage/blob/master/package.json#L52-L75

**Comment by JimiC** [comment]
@Gama11 Just let us see how we can support it. I'll work on it tomorrow.

**Comment by robertohuertasm** [comment]
#714 opened by @JimiC

**Pull request merged**
