### PR TITLE
Add support for Informix 4GL

### LINKED ISSUE #1440: [Icon Request] Support for Informix 4GL
Hello, I find it interesting to add an icon for the informaix 4GL syntax

- [x] I'm sure this issue is not a _duplicate_.
- [X] I'm submitting an icon request:
  - Type: `Informix 4GL`
  - Icon Name: `Informix 4GL`
  - Sample original Icon: 4gl32
  - Extensions: `.4gl, .per, spsql`
  - Filenames: ``
  - Language ids: `4GL`

- Language Extensions:
https://marketplace.visualstudio.com/items?itemName=CristianRengifo.informix4gl

imagen

### PR DESCRIPTION
**Pull request by KingDarBoja**
_**Fixes #1440**_

**Changes proposed:**

- [x] Add
- [ ] Delete
- [ ] Fix
- [ ] Prepare

### CODE REVIEW

**Comment by JimiC** [comment]
Where did you get the icon from?

**Comment by KingDarBoja** [comment]
> Where did you get the icon from?

I did a google search and found these ones: [X-like IBM](https://www.virtual-dba.com/platforms/ibm-informix/) and placed it inside this [database icon](https://pngtree.com/free-icon/informix_961247).

The color is the same as the official IBM guidelines. Blue 70 if I am not mistaken.

**Comment by JimiC** [comment]
Nice. I would combine red and blue like the informix logo. And the db icon I would make it with more height and less width.

**Comment by KingDarBoja** [comment]
> Nice. I would combine red and blue like the informix logo. And the db icon I would make it with more height and less width.

Something like this: 
file_type_informix

**Comment by JimiC** [comment]
Keep the x blue

**Pull request merged**
