### PR TITLE
feat(icon): add nx icons

### LINKED ISSUE #2536: [Icon Request] Add Support for Nx Workspace
- [x] I'm sure this issue is not a _duplicate_.
- [x] I'm submitting an icon request:
  - Type: `filename`
  - Icon Name: `nx-workspace`
  - Sample original Icon: logo-white logo-dark
  - Filenames: `nx.json`, `decorate-angular-cli.js`

- Language Extensions: https://github.com/nrwl/nx-console
- More info: The Nx workspaces let you manage multiple libraries/apps/schematics for different frameworks like Angular, Nest, React. All of this is being done by the `nx.json` file as explained at [Angular Nx Workspace](https://nx.dev/angular/workspace/workspace-overview) and [React Nx Workspace](https://nx.dev/react/workspace/workspace-overview).

Below is an example of how Nx Workspaces look like by selecting the Angular preset.

angular-nx-demo-tree

Would be great to provide the filename icon for these two files.

### PR DESCRIPTION
**Pull request by PAXANDDOS**
_**Fixes #2536**_

_**Superior version of #2556**_ (PR meant to be closed if this one succeeds)

**Changes proposed:**

- [X] Add

**Regarding changes compared to the latest PR:**
- Filenames: `nx.json` ([Source](https://nx.dev/configuration/projectjson)). `decorate-angular-cli.js` which was proposed in the issue is no longer supported. Other supported files for Nx are `project.json` and `angular.json`, where the first one is for general purposes and the second is related mostly to Angular.
- Dark theme icon. I saw the conversation regarding the proposed icon and how difficult the choice was. I refreshed the colors for the light theme icon and was struggling with the dark theme one. Tried different accent colors, including ones used at [nx.dev](https://nx.dev/) and decided to keep it simple. Nx uses a white logo for the dark theme, and since guidelines do not allow the use of `#ffffff`, I used grey `#d2d2d2` and I think it looks pretty good!

It's kinda strange that this issue along with PR was here for 2 years 😵 But I hope I helped

### CODE REVIEW

**Review by robertohuertasm — APPROVED** [review]
LGTM 🚀 Thanks for your contribution ❤️

**Comment by robertohuertasm** [comment]
This is the latest one for today's release. Run out of time! @PAXANDDOS we'll merge the rest during the coming weeks! Promise 😊

**Comment by PAXANDDOS** [comment]
> This is the last one for today's release. Run out of time! @PAXANDDOS we'll merge the rest during the coming weeks! Promise 😊

It's OK, happy to help! 😄

**Comment by robertohuertasm** [comment]
Happy to be receiving your cool contributions! ❤️

**Pull request merged**
