### PR TITLE
Support all Serverless Framework configuration file extensions

### PR DESCRIPTION
**Pull request by carlocorradini**
Support for **all** *Serverless Framework* configuration **file extensions**.

For more information: <https://www.serverless.com/framework/docs/providers/aws/guide/intro/>

**Changes proposed:**

- [ ] Add
- [ ] Delete
- [X] Fix
- [ ] Prepare

### CODE REVIEW

**Review by robertohuertasm — APPROVED** [review]
Thanks for your contribution ❤️

**Comment by carlocorradini** [comment]
> Thanks for your contribution ❤️

It's a pleasure to help in this project 🤗

When the new changes/icons/folders will be available?

*I can't wait 🤩🤩🤩*

**Comment by robertohuertasm** [comment]
Let's see if we can deploy it during the day.

**Comment by robertohuertasm** [comment]
We are still blocked by Travis... but will try to do a manual deployment

**Pull request merged**
